// src/constants/profileOptions.ts

// --- Karachi Areas ---
// You can keep adding more here later.
export const KARACHI_AREAS = [
  'DHA Karachi',
  'Clifton',
  'Gulshan-e-Iqbal',
  'Gulistan-e-Johar',
  'Bahadurabad',
  'PECHS',
  'Federal B Area',
  'Nazimabad',
  'North Nazimabad',
  'North Karachi',
  'Korangi',
  'Landhi',
  'Malir',
  'Scheme 33',
  'Saddar',
  'Lyari',
  'Surjani Town',
  'Orangi Town',
  'Shah Faisal Colony',
  'Garden',
  'Defence View',
  'Kharadar',
  'Shahrah-e-Faisal',
  'Other (Karachi)',
] as const;

// --- Game options ---
export const GAME_OPTIONS = [
  { key: 'cs2', label: 'Counter-Strike 2' },
  { key: 'fc26', label: 'FC 26' },
  { key: 'tekken8', label: 'Tekken 8' },
] as const;

// --- CS2 roles ---
export const CS2_ROLES = [
  'Entry Fragger',
  'Support',
  'AWPer',
  'In-Game Leader (IGL)',
  'Lurker',
] as const;

// --- FC 26 formations (codes only, UI stays clean) ---
export const FC_FORMATIONS = [
  '3-1-4-2',
  '3-4-1-2',
  '3-4-2-1',
  '3-4-3',
  '3-4-3 Flat',
  '3-5-2',
  '4-1-2-1-2',
  '4-1-2-1-2 (2)',
  '4-1-2-1-2 Narrow',
  '4-1-2-1-2 Wide',
  '4-1-3-2',
  '4-1-4-1',
  '4-2-1-3',
  '4-2-2-2',
  '4-2-3-1',
  '4-2-3-1 (2)',
  '4-2-3-1 Narrow',
  '4-2-3-1 Wide',
  '4-2-4',
  '4-3-1-2',
  '4-3-2-1',
  '4-3-3',
  '4-3-3 (2)',
  '4-3-3 (3)',
  '4-3-3 (4)',
  '4-3-3 Attack',
  '4-3-3 Defend',
  '4-3-3 Flat',
  '4-3-3 Holding',
  '4-4-1-1 (2)',
  '4-4-1-1 Midfield',
  '4-4-2',
  '4-4-2 (2)',
  '4-4-2 Flat',
  '4-4-2 Holding',
  '4-5-1',
  '4-5-1 (2)',
  '4-5-1 Attack',
  '4-5-1 Flat',
  '5-2-1-2',
  '5-2-3',
  '5-3-2',
  '5-3-2 Holding',
  '5-4-1',
  '5-4-1 Flat',
] as const;

// --- Tekken 8 characters ---
export const TEKKEN_CHARACTERS = [
  'Kasuya Mishima',
  'Jin Kazama',
  'Jun Kazama',
  'Paul Phoenix',
  'Marshall Law',
  'King',
  'Lars Alexandersson',
  'Ling Xiaoyu',
  'Jack-8',
  'Nina Williams',
  'Asuka Kazama',
  'Leroy Smith',
  'Hwoarang',
  'Lili',
  'Bryan Fury',
  'Claudio Serafino',
  'Azucena',
  'Raven',
  'Leo Kliesen',
  'Steve Fox',
  'Kuma',
  'Yoshimitsu',
  'Shaheen',
  'Dragunov',
  'Feng Wei',
  'Panda',
  'Devil Jin',
  'Zafina',
  'Alisa Bosconovitch',
  'Lee Chaolan',
  'Victor Chevalier',
  'Reina',
  'Eddy Gordo',
  'Lidia Sobieska',
] as const;
