// src/constants/profileOptions.ts

export const CITY_OPTIONS = [
  "Karachi",
  "Lahore",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Peshawar",
  "Quetta",
  "Hyderabad",
  "Other",
] as const;

// --- Karachi Areas ---
// You can keep adding more here later.
export const KARACHI_AREAS = [
  "DHA Karachi",
  "Clifton",
  "Gulshan-e-Iqbal",
  "Gulistan-e-Johar",
  "Bahadurabad",
  "PECHS",
  "Federal B Area",
  "Nazimabad",
  "North Nazimabad",
  "North Karachi",
  "Korangi",
  "Landhi",
  "Malir",
  "Scheme 33",
  "Saddar",
  "Lyari",
  "Surjani Town",
  "Orangi Town",
  "Shah Faisal Colony",
  "Garden",
  "Defence View",
  "Kharadar",
  "Shahrah-e-Faisal",
  "Other (Karachi)",
] as const;

// --- Game options ---
export const GAME_OPTIONS = [
  { key: "cs2", label: "Counter-Strike 2" },
  { key: "fc26", label: "FC 26" },
  { key: "tekken8", label: "Tekken 8" },
] as const;

// --- CS2 roles ---
export const CS2_ROLES = [
  "Entry Fragger",
  "Support",
  "AWPer",
  "In-Game Leader (IGL)",
  "Lurker",
] as const;

// --- FC 26 formations (codes only, UI stays clean) ---
export const FC_FORMATIONS = [
  "3-1-4-2",
  "3-4-1-2",
  "3-4-2-1",
  "3-4-3",
  "3-4-3 Flat",
  "3-5-2",
  "4-1-2-1-2",
  "4-1-2-1-2 (2)",
  "4-1-2-1-2 Narrow",
  "4-1-2-1-2 Wide",
  "4-1-3-2",
  "4-1-4-1",
  "4-2-1-3",
  "4-2-2-2",
  "4-2-3-1",
  "4-2-3-1 (2)",
  "4-2-3-1 Narrow",
  "4-2-3-1 Wide",
  "4-2-4",
  "4-3-1-2",
  "4-3-2-1",
  "4-3-3",
  "4-3-3 (2)",
  "4-3-3 (3)",
  "4-3-3 (4)",
  "4-3-3 Attack",
  "4-3-3 Defend",
  "4-3-3 Flat",
  "4-3-3 Holding",
  "4-4-1-1 (2)",
  "4-4-1-1 Midfield",
  "4-4-2",
  "4-4-2 (2)",
  "4-4-2 Flat",
  "4-4-2 Holding",
  "4-5-1",
  "4-5-1 (2)",
  "4-5-1 Attack",
  "4-5-1 Flat",
  "5-2-1-2",
  "5-2-3",
  "5-3-2",
  "5-3-2 Holding",
  "5-4-1",
  "5-4-1 Flat",
] as const;

// --- FC 26 leagues + teams ---
export const FC_LEAGUES = [
  {
    id: "premier_league",
    name: "Premier League",
    teams: [
      "Arsenal",
      "Aston Villa",
      "Barnsley",
      "Birmingham City",
      "Blackburn Rovers",
      "Blackpool",
      "Bolton Wanderers",
      "Bournemouth",
      "Bradford City",
      "Brentford",
      "Brighton and Hove Albion",
      "Burnley",
      "Cardiff City",
      "Charlton Athletic",
      "Chelsea",
      "Coventry City",
      "Crystal Palace",
      "Derby County",
      "Everton",
      "Fulham",
      "Huddersfield Town",
      "Hull City",
      "Ipswich Town",
      "Leeds United",
      "Leicester City",
      "Liverpool",
      "Luton Town",
      "Manchester City",
      "Manchester United",
      "Middlesbrough",
      "Newcastle United",
      "Norwich City",
      "Nottingham Forest",
      "Oldham Athletic",
      "Portsmouth",
      "Queens Park Rangers",
      "Reading",
      "Sheffield United",
      "Sheffield Wednesday",
      "Southampton",
      "Stoke City",
      "Sunderland",
      "Swansea City",
      "Swindon Town",
      "Tottenham Hotspur",
      "Watford",
      "West Bromwich Albion",
      "West Ham United",
      "Wigan Athletic",
      "Wimbledon",
      "Wolverhampton Wanderers",
    ],
  },
  {
    id: "laliga",
    name: "LaLiga",
    teams: [
      "Alavés",
      "Athletic",
      "Atlético Madrid",
      "Barcelona",
      "Betis",
      "Celta Vigo",
      "Elche",
      "Espanyol",
      "Getafe",
      "Girona",
      "Levante",
      "Mallorca",
      "Osasuna",
      "Oviedo",
      "Rayo Vallecano",
      "Real Madrid",
      "Real Sociedad",
      "Sevilla",
      "Valencia",
      "Villarreal",
    ],
  },
  {
    id: "serie_a",
    name: "Serie A",
    teams: [
      "Bologna",
      "Fiorentina",
      "Juventus",
      "Milan",
      "Napoli",
      "Roma",
      "Torino",
      "Inter",
      "Lazio",
      "Lecce",
      "Udinese",
      "Verona",
      "Atalanta",
      "Cagliari",
      "Genoa",
      "Como",
      "Parma",
      "Sassuolo",
      "Cremonese",
      "Empoli",
      "Monza",
    ],
  },
  {
    id: "bundesliga",
    name: "Bundesliga",
    teams: [
      "Bayern Munich",
      "Eintracht Frankfurt",
      "FC Koln",
      "Borussia Dortmund",
      "FC St. Pauli",
      "VfL Wolfsburg",
      "FC Augsburg",
      "VfB Stuttgart",
      "TSG Hoffenheim",
      "Union Berlin",
      "RB Leipzig",
      "Bayer 04 Leverkusen",
      "Mainz",
      "Borussia Mönchengladbach",
      "Hamburger SV",
      "Werder Bremen",
      "Heidenheim",
      "SC Freiburg",
    ],
  },
  {
    id: "ligue_1",
    name: "Ligue 1",
    teams: [
      "Lyon",
      "Marseille",
      "Monaco",
      "Nantes",
      "Nice",
      "PSG",
      "Strasbourg",
      "Auxerre",
      "Lens",
      "Lille",
      "Rennes",
      "Toulouse",
      "Le Havre",
      "Angers",
      "Metz",
      "Lorient",
      "Saint-Etienne",
      "Bordeaux",
    ],
  },
] as const;

// --- Tekken 8 characters ---
export const TEKKEN_CHARACTERS = [
  "Kasuya Mishima",
  "Jin Kazama",
  "Jun Kazama",
  "Paul Phoenix",
  "Marshall Law",
  "King",
  "Lars Alexandersson",
  "Ling Xiaoyu",
  "Jack-8",
  "Nina Williams",
  "Asuka Kazama",
  "Leroy Smith",
  "Hwoarang",
  "Lili",
  "Bryan Fury",
  "Claudio Serafino",
  "Azucena",
  "Raven",
  "Leo Kliesen",
  "Steve Fox",
  "Kuma",
  "Yoshimitsu",
  "Shaheen",
  "Dragunov",
  "Feng Wei",
  "Panda",
  "Devil Jin",
  "Zafina",
  "Alisa Bosconovitch",
  "Lee Chaolan",
  "Victor Chevalier",
  "Reina",
  "Eddy Gordo",
  "Lidia Sobieska",
] as const;

// --- Offline sports options (futsal, indoor cricket, padel, pickleball) ---

export const SPORT_OPTIONS = [
  { key: "futsal", label: "Futsal" },
  { key: "indoor_cricket", label: "Indoor Cricket" },
  { key: "padel", label: "Padel" },
  { key: "pickleball", label: "Pickleball" },
] as const;

export const FUTSAL_POSITIONS = [
  "Goalkeeper",
  "Defender",
  "Midfielder",
  "Winger",
  "Striker",
] as const;

export const INDOOR_CRICKET_ROLES = [
  "Batsman",
  "Bowler",
  "All-rounder",
  "Wicket-keeper",
] as const;

// NEW: sub-roles for indoor cricket
export const INDOOR_CRICKET_BOWLING_STYLES = [
  "Fast bowler",
  "Medium pace",
  "Spinner",
] as const;

export const INDOOR_CRICKET_BATTING_STYLES = [
  "Aggressive",
  "Anchor",
] as const;


export const PADEL_ROLES = [
  "Aggressive net player",
  "Defensive back player",
  "Balanced / either side",
] as const;

export const PICKLEBALL_ROLES = [
  "Singles",
  "Doubles – left side",
  "Doubles – right side",
  "Doubles – either side",
] as const;
