import { authTables } from "@convex-dev/auth/server";
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  ...authTables,
  users: defineTable({
    uid: v.optional(v.string()),
    legacyId: v.optional(v.string()),
    name: v.optional(v.string()),
    image: v.optional(v.string()),
    email: v.optional(v.string()),
    emailVerificationTime: v.optional(v.number()),
    pendingEmail: v.optional(v.string()),
    fullName: v.optional(v.string()),
    displayName: v.optional(v.string()),
    username: v.optional(v.string()),
    usernameLower: v.optional(v.string()),
    phone: v.optional(v.string()),
    phoneVerificationTime: v.optional(v.number()),
    isAnonymous: v.optional(v.boolean()),
    accountType: v.optional(v.string()),
    role: v.optional(v.string()),
    isOnline: v.optional(v.boolean()),
    trustScore: v.optional(v.number()),
    walletBalance: v.optional(v.number()),
    city: v.optional(v.string()),
    ageRange: v.optional(v.string()),
    areasPreferred: v.optional(v.array(v.string())),
    playsCs2: v.optional(v.boolean()),
    playsFc: v.optional(v.boolean()),
    playsTekken: v.optional(v.boolean()),
    playsFutsal: v.optional(v.boolean()),
    playsIndoorCricket: v.optional(v.boolean()),
    playsPadel: v.optional(v.boolean()),
    playsPickleball: v.optional(v.boolean()),
    cs2Role: v.optional(v.string()),
    fcTeam: v.optional(v.string()),
    fcFormation: v.optional(v.string()),
    tekkenFavorites: v.optional(v.array(v.string())),
    futsalPosition: v.optional(v.string()),
    futsalPositions: v.optional(v.array(v.string())),
    indoorCricketRole: v.optional(v.string()),
    indoorCricketBowlingStyle: v.optional(v.string()),
    indoorCricketBattingStyle: v.optional(v.string()),
    padelRole: v.optional(v.string()),
    pickleballRole: v.optional(v.string()),
    steamProfileUrl: v.optional(v.string()),
    steamId: v.optional(v.string()),
    steamPersonaName: v.optional(v.string()),
    steamCs2Hours: v.optional(v.number()),
    steamTekken8Hours: v.optional(v.number()),
    steamFc26Hours: v.optional(v.number()),
    steamStats: v.optional(v.any()),
    faceitProfileUrl: v.optional(v.string()),
    faceitId: v.optional(v.string()),
    faceitNickname: v.optional(v.string()),
    faceitGame: v.optional(v.string()),
    faceitElo: v.optional(v.number()),
    faceitSkillLevel: v.optional(v.number()),
    psnOnlineId: v.optional(v.string()),
    psnAccountId: v.optional(v.string()),
    psnStats: v.optional(v.any()),
    skillScores: v.optional(v.any()),
    teamsByGame: v.optional(v.any()),
    hideAreasPublicly: v.optional(v.boolean()),
    hidePlatformsPublicly: v.optional(v.boolean()),
    restrictInvitesToFriends: v.optional(v.boolean()),
    onboardingStep: v.optional(v.number()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  })
    .index("email", ["email"])
    .index("by_uid", ["uid"])
    .index("phone", ["phone"])
    .index("by_usernameLower", ["usernameLower"])
    .index("by_steamId", ["steamId"])
    .index("by_faceitId", ["faceitId"])
    .index("by_psnAccountId", ["psnAccountId"])
    .index("by_role", ["role"])
    .index("by_accountType", ["accountType"])
    .index("by_createdAt", ["createdAt"])
    .searchIndex("search_displayName", {
      searchField: "displayName",
      filterFields: ["accountType"],
    }),

  userFriends: defineTable({
    legacyId: v.optional(v.string()),
    userId: v.string(),
    friendId: v.string(),
    username: v.optional(v.string()),
    since: v.optional(v.number()),
    createdAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  })
    .index("by_userId", ["userId"])
    .index("by_userId_friendId", ["userId", "friendId"])
    .index("by_friendId", ["friendId"])
    .index("by_createdAt", ["createdAt"]),

  walletTransactions: defineTable({
    legacyId: v.optional(v.string()),
    userId: v.string(),
    type: v.optional(v.string()),
    amount: v.optional(v.number()),
    status: v.optional(v.string()),
    source: v.optional(v.string()),
    intentId: v.optional(v.string()),
    matchroomId: v.optional(v.string()),
    createdAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  })
    .index("by_userId", ["userId"])
    .index("by_createdAt", ["createdAt"]),

  teams: defineTable({
    legacyId: v.optional(v.string()),
    teamId: v.optional(v.string()),
    name: v.string(),
    nameLower: v.optional(v.string()),
    description: v.optional(v.string()),
    game: v.optional(v.string()),
    logoUrl: v.optional(v.string()),
    captainUid: v.string(),
    captainUsername: v.optional(v.string()),
    memberUids: v.optional(v.array(v.string())),
    memberCount: v.optional(v.number()),
    maxMembers: v.optional(v.number()),
    visibility: v.optional(v.string()),
    stats: v.optional(v.any()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  })
    .index("by_captainUid", ["captainUid"])
    .index("by_memberUid", ["memberUids"])
    .index("by_visibility", ["visibility"])
    .index("by_game", ["game"])
    .index("by_nameLower", ["nameLower"])
    .index("by_createdAt", ["createdAt"])
    .searchIndex("search_name", {
      searchField: "name",
      filterFields: ["visibility", "game"],
    }),

  teamMembers: defineTable({
    legacyId: v.optional(v.string()),
    teamId: v.string(),
    memberUid: v.string(),
    username: v.optional(v.string()),
    role: v.optional(v.string()),
    joinedAt: v.optional(v.number()),
    invitedByUid: v.optional(v.string()),
    invitedAt: v.optional(v.number()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  })
    .index("by_teamId", ["teamId"])
    .index("by_memberUid", ["memberUid"])
    .index("by_createdAt", ["createdAt"]),

  zones: defineTable({
    legacyId: v.optional(v.string()),
    ownerUid: v.string(),
    ownerFullName: v.optional(v.string()),
    venueBrandName: v.optional(v.string()),
    contactEmail: v.optional(v.string()),
    contactPhone: v.optional(v.string()),
    type: v.optional(v.string()),
    status: v.optional(v.string()),
    rejectionReason: v.optional(v.string()),
    onboardingStep: v.optional(v.number()),
    primaryBranch: v.optional(v.any()),
    primaryArea: v.optional(v.string()),
    games: v.optional(v.any()),
    capacity: v.optional(v.any()),
    pricing: v.optional(v.any()),
    branches: v.optional(v.any()),
    notes: v.optional(v.string()),
    searchText: v.optional(v.string()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  })
    .index("by_ownerUid", ["ownerUid"])
    .index("by_status", ["status"])
    .index("by_primaryArea", ["primaryArea"])
    .index("by_createdAt", ["createdAt"])
    .searchIndex("search_text", {
      searchField: "searchText",
      filterFields: ["status", "type"],
    }),

  zoneBranches: defineTable({
    legacyId: v.optional(v.string()),
    zoneId: v.string(),
    branchDisplayName: v.optional(v.string()),
    city: v.optional(v.string()),
    areaLabel: v.optional(v.string()),
    addressLine1: v.optional(v.string()),
    googleMapsUrl: v.optional(v.string()),
    source: v.optional(v.string()),
    games: v.optional(v.any()),
    pricing: v.optional(v.any()),
    notes: v.optional(v.string()),
    specs: v.optional(v.string()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  })
    .index("by_zoneId", ["zoneId"])
    .index("by_areaLabel", ["areaLabel"])
    .index("by_createdAt", ["createdAt"]),

  zoneResources: defineTable({
    legacyId: v.optional(v.string()),
    zoneId: v.string(),
    branchId: v.string(),
    kind: v.optional(v.string()),
    lifecycleStatus: v.optional(v.string()),
    label: v.optional(v.string()),
    roomLabel: v.optional(v.string()),
    assetType: v.optional(v.string()),
    tier: v.optional(v.string()),
    surface: v.optional(v.string()),
    isActive: v.optional(v.boolean()),
    heldUntil: v.optional(v.number()),
    holdRequestId: v.optional(v.string()),
    allocation: v.optional(v.any()),
    statusChangedBy: v.optional(v.string()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  })
    .index("by_zoneId", ["zoneId"])
    .index("by_branchId", ["branchId"])
    .index("by_lifecycleStatus", ["lifecycleStatus"]),

  zonePricingRules: defineTable({
    legacyId: v.optional(v.string()),
    zoneId: v.string(),
    name: v.optional(v.string()),
    isEnabled: v.optional(v.boolean()),
    assetType: v.optional(v.string()),
    branchId: v.optional(v.string()),
    tier: v.optional(v.string()),
    surface: v.optional(v.string()),
    ruleType: v.optional(v.string()),
    value: v.optional(v.number()),
    daysOfWeek: v.optional(v.array(v.number())),
    timeStart: v.optional(v.string()),
    timeEnd: v.optional(v.string()),
    validFrom: v.optional(v.string()),
    validTo: v.optional(v.string()),
    priority: v.optional(v.number()),
    createdByUid: v.optional(v.string()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  })
    .index("by_zoneId", ["zoneId"])
    .index("by_isEnabled", ["isEnabled"])
    .index("by_assetType", ["assetType"]),

  matchrooms: defineTable({
    legacyId: v.optional(v.string()),
    hostUid: v.string(),
    hostName: v.optional(v.string()),
    game: v.optional(v.string()),
    title: v.optional(v.string()),
    description: v.optional(v.string()),
    status: v.optional(v.string()),
    maxPlayers: v.optional(v.number()),
    currentPlayers: v.optional(v.number()),
    players: v.optional(v.any()),
    playerUids: v.optional(v.array(v.string())),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    location: v.optional(v.string()),
    coordinates: v.optional(v.any()),
    locationMode: v.optional(v.string()),
    broadcastAreas: v.optional(v.array(v.string())),
    zoneId: v.optional(v.string()),
    zoneOwnerUid: v.optional(v.string()),
    startTime: v.optional(v.number()),
    scheduledDate: v.optional(v.string()),
    scheduledTime: v.optional(v.string()),
    scheduledAt: v.optional(v.number()),
    scheduledStartAt: v.optional(v.number()),
    durationMinutes: v.optional(v.number()),
    pricing: v.optional(v.any()),
    matchCode: v.optional(v.string()),
    flexibility: v.optional(v.string()),
    bookingSource: v.optional(v.string()),
    skipBookingRequest: v.optional(v.boolean()),
    format: v.optional(v.string()),
    seriesType: v.optional(v.string()),
    durationHours: v.optional(v.number()),
    selectedMaps: v.optional(v.array(v.string())),
    skillLevel: v.optional(v.string()),
    hostSkillScore: v.optional(v.number()),
    hostSkillTier: v.optional(v.string()),
    hostRole: v.optional(v.string()),
    hostSkillContext: v.optional(v.any()),
    avgSkillScoreLive: v.optional(v.number()),
    totalSkillSum: v.optional(v.number()),
    ratedPlayerCount: v.optional(v.number()),
    playstyle: v.optional(v.string()),
    rankRequirement: v.optional(v.string()),
    overs: v.optional(v.number()),
    sidePreference: v.optional(v.string()),
    composition: v.optional(v.string()),
    battingOrder: v.optional(v.string()),
    battingStyle: v.optional(v.string()),
    bowlingStyle: v.optional(v.string()),
    bowlingOrder: v.optional(v.string()),
    ruleset: v.optional(v.any()),
    slotsA: v.optional(v.any()),
    slotsB: v.optional(v.any()),
    captainUidA: v.optional(v.string()),
    captainUidB: v.optional(v.string()),
    teamMode: v.optional(v.string()),
    teamId: v.optional(v.string()),
    teamName: v.optional(v.string()),
    reservedSlots: v.optional(v.number()),
    teamPaymentMode: v.optional(v.string()),
    assignedTeamMembers: v.optional(v.any()),
    isPrivate: v.optional(v.boolean()),
    isLocked: v.optional(v.boolean()),
    lockedAt: v.optional(v.number()),
    lockAt: v.optional(v.number()),
    expiresAt: v.optional(v.number()),
    zoneAdminApproved: v.optional(v.boolean()),
    paymentStatus: v.optional(v.string()),
    paymentAmount: v.optional(v.number()),
    paymentReservedSlots: v.optional(v.number()),
    paymentCurrency: v.optional(v.string()),
    resultVerification: v.optional(v.any()),
    walkIn: v.optional(v.any()),
    searchText: v.optional(v.string()),
    legacy: v.optional(v.any()),
  })
    .index("by_status", ["status"])
    .index("by_scheduledAt", ["scheduledAt"])
    .index("by_hostUid", ["hostUid"])
    .index("by_playerUid", ["playerUids"])
    .index("by_zoneId", ["zoneId"])
    .index("by_teamId", ["teamId"])
    .index("by_createdAt", ["createdAt"])
    .searchIndex("search_text", {
      searchField: "searchText",
      filterFields: ["game"],
    }),

  chatrooms: defineTable({
    legacyId: v.optional(v.string()),
    matchroomId: v.optional(v.string()),
    zoneId: v.optional(v.string()),
    participantUids: v.optional(v.array(v.string())),
    lastMessage: v.optional(v.any()),
    lastReadBy: v.optional(v.any()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  }).index("by_matchroomId", ["matchroomId"]),

  chatMessages: defineTable({
    legacyId: v.optional(v.string()),
    chatroomId: v.string(),
    text: v.optional(v.string()),
    senderUid: v.optional(v.string()),
    senderName: v.optional(v.string()),
    createdAt: v.optional(v.number()),
    replyTo: v.optional(v.any()),
    deletedFor: v.optional(v.array(v.string())),
    legacy: v.optional(v.any()),
  }).index("by_chatroomId_createdAt", ["chatroomId", "createdAt"]),

  teamMatchChallenges: defineTable({
    legacyId: v.optional(v.string()),
    challengerTeamId: v.string(),
    challengerTeamName: v.optional(v.string()),
    opponentTeamId: v.string(),
    opponentTeamName: v.optional(v.string()),
    captainAUid: v.optional(v.string()),
    captainAName: v.optional(v.string()),
    captainBUid: v.optional(v.string()),
    captainBName: v.optional(v.string()),
    gameKey: v.optional(v.string()),
    format: v.optional(v.string()),
    seriesType: v.optional(v.string()),
    maxPlayers: v.optional(v.number()),
    scheduledDate: v.optional(v.string()),
    scheduledTime: v.optional(v.string()),
    scheduledAt: v.optional(v.number()),
    pricePerPlayer: v.optional(v.number()),
    message: v.optional(v.string()),
    status: v.optional(v.string()),
    commonAreas: v.optional(v.array(v.string())),
    proposedVenueByCaptainA: v.optional(v.any()),
    alternativeVenueByCaptainB: v.optional(v.any()),
    captainVenueChoices: v.optional(v.any()),
    confirmedVenue: v.optional(v.any()),
    chatId: v.optional(v.string()),
    matchroomId: v.optional(v.string()),
    bookingRequestId: v.optional(v.string()),
    adminReviewStatus: v.optional(v.string()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  })
    .index("by_challengerTeamId", ["challengerTeamId"])
    .index("by_opponentTeamId", ["opponentTeamId"])
    .index("by_status", ["status"])
    .index("by_scheduledAt", ["scheduledAt"])
    .index("by_captainAUid", ["captainAUid"])
    .index("by_captainBUid", ["captainBUid"])
    .index("by_createdAt", ["createdAt"]),

  teamMatchChats: defineTable({
    legacyId: v.optional(v.string()),
    challengeId: v.string(),
    participantUids: v.optional(v.array(v.string())),
    rolesByUid: v.optional(v.any()),
    lastMessage: v.optional(v.any()),
    lastReadBy: v.optional(v.any()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  }).index("by_challengeId", ["challengeId"]),

  teamMatchMessages: defineTable({
    legacyId: v.optional(v.string()),
    chatId: v.string(),
    senderUid: v.optional(v.string()),
    senderName: v.optional(v.string()),
    text: v.optional(v.string()),
    createdAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  }).index("by_chatId_createdAt", ["chatId", "createdAt"]),

  bookingRequests: defineTable({
    legacyId: v.optional(v.string()),
    userId: v.string(),
    userName: v.optional(v.string()),
    gameKey: v.optional(v.string()),
    title: v.optional(v.string()),
    description: v.optional(v.string()),
    maxPlayers: v.optional(v.number()),
    format: v.optional(v.string()),
    seriesType: v.optional(v.string()),
    durationHours: v.optional(v.number()),
    selectedMaps: v.optional(v.array(v.string())),
    skillLevel: v.optional(v.string()),
    overs: v.optional(v.string()),
    hostSkillScore: v.optional(v.number()),
    hostSkillTier: v.optional(v.string()),
    hostSkillContext: v.optional(v.any()),
    teamMode: v.optional(v.string()),
    teamId: v.optional(v.string()),
    reservedSlots: v.optional(v.number()),
    preferredDate: v.optional(v.any()),
    preferredTime: v.optional(v.string()),
    flexibilityWindow: v.optional(v.string()),
    locationMode: v.optional(v.string()),
    zoneId: v.optional(v.string()),
    zoneOwnerUid: v.optional(v.string()),
    preferredAreas: v.optional(v.array(v.string())),
    budgetPerPlayer: v.optional(v.number()),
    currency: v.optional(v.string()),
    status: v.optional(v.string()),
    acceptedOfferId: v.optional(v.string()),
    matchroomId: v.optional(v.string()),
    paymentStatus: v.optional(v.string()),
    paymentAmount: v.optional(v.number()),
    paymentReservedSlots: v.optional(v.number()),
    paymentCurrency: v.optional(v.string()),
    lifecycleStatus: v.optional(v.string()),
    allocationSnapshot: v.optional(v.any()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    expiresAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  })
    .index("by_status", ["status"])
    .index("by_userId", ["userId"])
    .index("by_zoneId", ["zoneId"])
    .index("by_zoneOwnerUid", ["zoneOwnerUid"])
    .index("by_matchroomId", ["matchroomId"])
    .index("by_createdAt", ["createdAt"]),

  bookingOffers: defineTable({
    legacyId: v.optional(v.string()),
    requestId: v.string(),
    requestOwnerUid: v.optional(v.string()),
    zoneId: v.optional(v.string()),
    zoneName: v.optional(v.string()),
    zoneOwnerUid: v.optional(v.string()),
    zoneAdminId: v.optional(v.string()),
    branchId: v.optional(v.string()),
    branchName: v.optional(v.string()),
    proposedDate: v.optional(v.any()),
    proposedTime: v.optional(v.string()),
    pricePerPlayer: v.optional(v.number()),
    currency: v.optional(v.string()),
    location: v.optional(v.string()),
    message: v.optional(v.string()),
    status: v.optional(v.string()),
    matchroomId: v.optional(v.string()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    expiresAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  })
    .index("by_requestId", ["requestId"])
    .index("by_requestOwnerUid", ["requestOwnerUid"])
    .index("by_zoneOwnerUid", ["zoneOwnerUid"])
    .index("by_status", ["status"])
    .index("by_createdAt", ["createdAt"]),

  bookingIntents: defineTable({
    legacyId: v.optional(v.string()),
    matchroomId: v.string(),
    game: v.optional(v.string()),
    createdByUid: v.optional(v.string()),
    side: v.optional(v.string()),
    selectedSlots: v.optional(v.array(v.string())),
    invitees: v.optional(v.any()),
    pricing: v.optional(v.any()),
    approvals: v.optional(v.any()),
    status: v.optional(v.string()),
    paymentStatus: v.optional(v.string()),
    paymentMethod: v.optional(v.string()),
    expiresAt: v.optional(v.number()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  })
    .index("by_matchroomId", ["matchroomId"])
    .index("by_createdByUid", ["createdByUid"])
    .index("by_status", ["status"])
    .index("by_createdAt", ["createdAt"]),

  notifications: defineTable({
    legacyId: v.optional(v.string()),
    type: v.optional(v.string()),
    fromUid: v.optional(v.string()),
    fromUsername: v.optional(v.string()),
    toUid: v.optional(v.string()),
    status: v.optional(v.string()),
    isRead: v.optional(v.boolean()),
    title: v.optional(v.string()),
    message: v.optional(v.string()),
    reason: v.optional(v.string()),
    content: v.optional(v.string()),
    entityKey: v.optional(v.string()),
    meta: v.optional(v.any()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    expiresAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  })
    .index("by_toUid_createdAt", ["toUid", "createdAt"])
    .index("by_fromUid_createdAt", ["fromUid", "createdAt"])
    .index("by_status", ["status"])
    .index("by_type", ["type"]),

  reports: defineTable({
    legacyId: v.optional(v.string()),
    type: v.optional(v.string()),
    status: v.optional(v.string()),
    matchroomId: v.optional(v.string()),
    reportedUserId: v.optional(v.string()),
    game: v.optional(v.string()),
    title: v.optional(v.string()),
    reason: v.optional(v.string()),
    description: v.optional(v.string()),
    reporterUid: v.optional(v.string()),
    reporterUsername: v.optional(v.string()),
    resolvedByUid: v.optional(v.string()),
    resolvedAt: v.optional(v.number()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    legacy: v.optional(v.any()),
  })
    .index("by_status", ["status"])
    .index("by_createdAt", ["createdAt"])
    .index("by_reportedUserId", ["reportedUserId"])
    .index("by_matchroomId", ["matchroomId"]),
});
