import { getApiClient } from "../api/client";
export type { AuthResult, AuthUser } from "../repositories/firebase/authService";
export const currentUser: typeof import("../repositories/firebase/authService").currentUser = (...args) => getApiClient().auth.currentUser(...args);
export const onAuthStateChanged: typeof import("../repositories/firebase/authService").onAuthStateChanged = (...args) => getApiClient().auth.onAuthStateChanged(...args);
export const reauthenticateCurrentUser: typeof import("../repositories/firebase/authService").reauthenticateCurrentUser = (...args) => getApiClient().auth.reauthenticateCurrentUser(...args);
export const reloadCurrentUser: typeof import("../repositories/firebase/authService").reloadCurrentUser = (...args) => getApiClient().auth.reloadCurrentUser(...args);
export const sendPasswordReset: typeof import("../repositories/firebase/authService").sendPasswordReset = (...args) => getApiClient().auth.sendPasswordReset(...args);
export const signInWithEmail: typeof import("../repositories/firebase/authService").signInWithEmail = (...args) => getApiClient().auth.signInWithEmail(...args);
export const signOutUser: typeof import("../repositories/firebase/authService").signOutUser = (...args) => getApiClient().auth.signOutUser(...args);
export const signUpWithEmail: typeof import("../repositories/firebase/authService").signUpWithEmail = (...args) => getApiClient().auth.signUpWithEmail(...args);
export const updateCurrentUserPassword: typeof import("../repositories/firebase/authService").updateCurrentUserPassword = (...args) => getApiClient().auth.updateCurrentUserPassword(...args);
export const verifyCurrentUserEmail: typeof import("../repositories/firebase/authService").verifyCurrentUserEmail = (...args) => getApiClient().auth.verifyCurrentUserEmail(...args);
