import { getApiClient } from "../api/client";
export type { BookingIntent } from "../repositories/firebase/bookingService";
export { FAIR_BAND_DELTA_BY_GAME } from "../repositories/firebase/bookingService";
export const claimSeatTransaction: typeof import("../repositories/firebase/bookingService").claimSeatTransaction = (...args) => getApiClient().bookings.claimSeatTransaction(...args);
export const cleanupExpiredIntents: typeof import("../repositories/firebase/bookingService").cleanupExpiredIntents = (...args) => getApiClient().bookings.cleanupExpiredIntents(...args);
export const confirmBookingTransaction: typeof import("../repositories/firebase/bookingService").confirmBookingTransaction = (...args) => getApiClient().bookings.confirmBookingTransaction(...args);
export const createBookingIntent: typeof import("../repositories/firebase/bookingService").createBookingIntent = (...args) => getApiClient().bookings.createBookingIntent(...args);
export const createBookingIntentDetailed: typeof import("../repositories/firebase/bookingService").createBookingIntentDetailed = (...args) => getApiClient().bookings.createBookingIntentDetailed(...args);
export const generateIntentId: typeof import("../repositories/firebase/bookingService").generateIntentId = (...args) => getApiClient().bookings.generateIntentId(...args);
export const getBookingIntent: typeof import("../repositories/firebase/bookingService").getBookingIntent = (...args) => getApiClient().bookings.getBookingIntent(...args);
export const getHostCaptainUid: typeof import("../repositories/firebase/bookingService").getHostCaptainUid = (...args) => getApiClient().bookings.getHostCaptainUid(...args);
export const getSlotIdHash: typeof import("../repositories/firebase/bookingService").getSlotIdHash = (...args) => getApiClient().bookings.getSlotIdHash(...args);
export const isWithinFairnessBand: typeof import("../repositories/firebase/bookingService").isWithinFairnessBand = (...args) => getApiClient().bookings.isWithinFairnessBand(...args);
export const updateBookingIntentStatus: typeof import("../repositories/firebase/bookingService").updateBookingIntentStatus = (...args) => getApiClient().bookings.updateBookingIntentStatus(...args);
