import { getApiClient } from "../api/client";
export type { CreateTeamData, RemoveFriendData, RespondFriendRequestData, SendFriendRequestData, ServerResponse } from "../repositories/firebase/functions";
export const cancelUserPendingMatchroomRequests: typeof import("../repositories/firebase/functions").cancelUserPendingMatchroomRequests = (...args) => getApiClient().functions.cancelUserPendingMatchroomRequests(...args);
export const createTeam: typeof import("../repositories/firebase/functions").createTeam = (...args) => getApiClient().functions.createTeam(...args);
export const deleteTeam: typeof import("../repositories/firebase/functions").deleteTeam = (...args) => getApiClient().functions.deleteTeam(...args);
export const inviteToMatchroom: typeof import("../repositories/firebase/functions").inviteToMatchroom = (...args) => getApiClient().functions.inviteToMatchroom(...args);
export const inviteToTeam: typeof import("../repositories/firebase/functions").inviteToTeam = (...args) => getApiClient().functions.inviteToTeam(...args);
export const kickFromMatchroom: typeof import("../repositories/firebase/functions").kickFromMatchroom = (...args) => getApiClient().functions.kickFromMatchroom(...args);
export const leaveTeam: typeof import("../repositories/firebase/functions").leaveTeam = (...args) => getApiClient().functions.leaveTeam(...args);
export const removeFriend: typeof import("../repositories/firebase/functions").removeFriend = (...args) => getApiClient().functions.removeFriend(...args);
export const removeMember: typeof import("../repositories/firebase/functions").removeMember = (...args) => getApiClient().functions.removeMember(...args);
export const requestToJoinTeam: typeof import("../repositories/firebase/functions").requestToJoinTeam = (...args) => getApiClient().functions.requestToJoinTeam(...args);
export const respondFriendRequest: typeof import("../repositories/firebase/functions").respondFriendRequest = (...args) => getApiClient().functions.respondFriendRequest(...args);
export const respondToJoinRequest: typeof import("../repositories/firebase/functions").respondToJoinRequest = (...args) => getApiClient().functions.respondToJoinRequest(...args);
export const respondToMatchroomInvite: typeof import("../repositories/firebase/functions").respondToMatchroomInvite = (...args) => getApiClient().functions.respondToMatchroomInvite(...args);
export const respondToMatchroomJoinRequest: typeof import("../repositories/firebase/functions").respondToMatchroomJoinRequest = (...args) => getApiClient().functions.respondToMatchroomJoinRequest(...args);
export const respondToTeamInvite: typeof import("../repositories/firebase/functions").respondToTeamInvite = (...args) => getApiClient().functions.respondToTeamInvite(...args);
export const sendFriendRequest: typeof import("../repositories/firebase/functions").sendFriendRequest = (...args) => getApiClient().functions.sendFriendRequest(...args);
export const transferCaptain: typeof import("../repositories/firebase/functions").transferCaptain = (...args) => getApiClient().functions.transferCaptain(...args);
export const transferMatchroomCaptain: typeof import("../repositories/firebase/functions").transferMatchroomCaptain = (...args) => getApiClient().functions.transferMatchroomCaptain(...args);
