import { getApiClient } from "../api/client";
export type { Matchroom, Slot } from "../repositories/firebase/matchService";
export const adminCancelMatchroom: typeof import("../repositories/firebase/matchService").adminCancelMatchroom = (...args) => getApiClient().matchrooms.adminCancelMatchroom(...args);
export const cancelMatchJoinRequest: typeof import("../repositories/firebase/matchService").cancelMatchJoinRequest = (...args) => getApiClient().matchrooms.cancelMatchJoinRequest(...args);
export const createMatchroom: typeof import("../repositories/firebase/matchService").createMatchroom = (...args) => getApiClient().matchrooms.createMatchroom(...args);
export const deleteMatchroom: typeof import("../repositories/firebase/matchService").deleteMatchroom = (...args) => getApiClient().matchrooms.deleteMatchroom(...args);
export const findUserTimeConflict: typeof import("../repositories/firebase/matchService").findUserTimeConflict = (...args) => getApiClient().matchrooms.findUserTimeConflict(...args);
export const getMatchroom: typeof import("../repositories/firebase/matchService").getMatchroom = (...args) => getApiClient().matchrooms.getMatchroom(...args);
export const getMatchroomById: typeof import("../repositories/firebase/matchService").getMatchroomById = (...args) => getApiClient().matchrooms.getMatchroomById(...args);
export const getMatchrooms: typeof import("../repositories/firebase/matchService").getMatchrooms = (...args) => getApiClient().matchrooms.getMatchrooms(...args);
export const getUserMatchrooms: typeof import("../repositories/firebase/matchService").getUserMatchrooms = (...args) => getApiClient().matchrooms.getUserMatchrooms(...args);
export const isUserInActiveMatchroom: typeof import("../repositories/firebase/matchService").isUserInActiveMatchroom = (...args) => getApiClient().matchrooms.isUserInActiveMatchroom(...args);
export const joinMatchroom: typeof import("../repositories/firebase/matchService").joinMatchroom = (...args) => getApiClient().matchrooms.joinMatchroom(...args);
export const leaveMatchroom: typeof import("../repositories/firebase/matchService").leaveMatchroom = (...args) => getApiClient().matchrooms.leaveMatchroom(...args);
export const requestJoinMatchroom: typeof import("../repositories/firebase/matchService").requestJoinMatchroom = (...args) => getApiClient().matchrooms.requestJoinMatchroom(...args);
export const respondToMatchJoinRequest: typeof import("../repositories/firebase/matchService").respondToMatchJoinRequest = (...args) => getApiClient().matchrooms.respondToMatchJoinRequest(...args);
export const startMatch: typeof import("../repositories/firebase/matchService").startMatch = (...args) => getApiClient().matchrooms.startMatch(...args);
export const submitCaptainReport: typeof import("../repositories/firebase/matchService").submitCaptainReport = (...args) => getApiClient().matchrooms.submitCaptainReport(...args);
export const submitParticipantVote: typeof import("../repositories/firebase/matchService").submitParticipantVote = (...args) => getApiClient().matchrooms.submitParticipantVote(...args);
