import { getApiClient } from "../api/client";
export type { GameKey, GameSkillScore, MatchResultOutcome, SkillTier } from "../repositories/firebase/skillRatingService";
export { SKILL_THRESHOLDS } from "../repositories/firebase/skillRatingService";
export const applyMatchResult: typeof import("../repositories/firebase/skillRatingService").applyMatchResult = (...args) => getApiClient().skillRatings.applyMatchResult(...args);
export const calculateInitialRating: typeof import("../repositories/firebase/skillRatingService").calculateInitialRating = (...args) => getApiClient().skillRatings.calculateInitialRating(...args);
export const calculateRatingChange: typeof import("../repositories/firebase/skillRatingService").calculateRatingChange = (...args) => getApiClient().skillRatings.calculateRatingChange(...args);
export const calculateScoreFromAnswers: typeof import("../repositories/firebase/skillRatingService").calculateScoreFromAnswers = (...args) => getApiClient().skillRatings.calculateScoreFromAnswers(...args);
export const getTierFromRating: typeof import("../repositories/firebase/skillRatingService").getTierFromRating = (...args) => getApiClient().skillRatings.getTierFromRating(...args);
export const initializeSkillIfMissing: typeof import("../repositories/firebase/skillRatingService").initializeSkillIfMissing = (...args) => getApiClient().skillRatings.initializeSkillIfMissing(...args);
export const saveSelfAssessment: typeof import("../repositories/firebase/skillRatingService").saveSelfAssessment = (...args) => getApiClient().skillRatings.saveSelfAssessment(...args);
