import { getApiClient } from "../api/client";
export type { GetPublicTeamsOptions, Team, TeamMember } from "../repositories/firebase/teamService";
export const createTeam: typeof import("../repositories/firebase/teamService").createTeam = (...args) => getApiClient().teams.createTeam(...args);
export const deleteTeam: typeof import("../repositories/firebase/teamService").deleteTeam = (...args) => getApiClient().teams.deleteTeam(...args);
export const getPublicTeams: typeof import("../repositories/firebase/teamService").getPublicTeams = (...args) => getApiClient().teams.getPublicTeams(...args);
export const getTeamById: typeof import("../repositories/firebase/teamService").getTeamById = (...args) => getApiClient().teams.getTeamById(...args);
export const getUserTeams: typeof import("../repositories/firebase/teamService").getUserTeams = (...args) => getApiClient().teams.getUserTeams(...args);
export const getUserTeamsForGame: typeof import("../repositories/firebase/teamService").getUserTeamsForGame = (...args) => getApiClient().teams.getUserTeamsForGame(...args);
export const joinTeam: typeof import("../repositories/firebase/teamService").joinTeam = (...args) => getApiClient().teams.joinTeam(...args);
export const leaveTeam: typeof import("../repositories/firebase/teamService").leaveTeam = (...args) => getApiClient().teams.leaveTeam(...args);
export const requestToJoinTeam: typeof import("../repositories/firebase/teamService").requestToJoinTeam = (...args) => getApiClient().teams.requestToJoinTeam(...args);
export const updateTeamName: typeof import("../repositories/firebase/teamService").updateTeamName = (...args) => getApiClient().teams.updateTeamName(...args);
export const uploadTeamLogo: typeof import("../repositories/firebase/teamService").uploadTeamLogo = (...args) => getApiClient().teams.uploadTeamLogo(...args);
