import { getApiClient } from "../api/client";
export type { TeamChallengeVenueChoice, TeamMatchChallenge, TeamMatchChallengeStatus } from "../repositories/firebase/teamMatchService";
export const acceptTeamMatchChallenge: typeof import("../repositories/firebase/teamMatchService").acceptTeamMatchChallenge = (...args) => getApiClient().teamMatch.acceptTeamMatchChallenge(...args);
export const getCaptainedTeams: typeof import("../repositories/firebase/teamMatchService").getCaptainedTeams = (...args) => getApiClient().teamMatch.getCaptainedTeams(...args);
export const getChallengesForCaptain: typeof import("../repositories/firebase/teamMatchService").getChallengesForCaptain = (...args) => getApiClient().teamMatch.getChallengesForCaptain(...args);
export const getTeamMatchChallengeById: typeof import("../repositories/firebase/teamMatchService").getTeamMatchChallengeById = (...args) => getApiClient().teamMatch.getTeamMatchChallengeById(...args);
export const proposeTeamChallengeVenue: typeof import("../repositories/firebase/teamMatchService").proposeTeamChallengeVenue = (...args) => getApiClient().teamMatch.proposeTeamChallengeVenue(...args);
export const rejectTeamMatchChallenge: typeof import("../repositories/firebase/teamMatchService").rejectTeamMatchChallenge = (...args) => getApiClient().teamMatch.rejectTeamMatchChallenge(...args);
export const repairTeamChallengesForCaptain: typeof import("../repositories/firebase/teamMatchService").repairTeamChallengesForCaptain = (...args) => getApiClient().teamMatch.repairTeamChallengesForCaptain(...args);
export const repairTeamMatchChallenge: typeof import("../repositories/firebase/teamMatchService").repairTeamMatchChallenge = (...args) => getApiClient().teamMatch.repairTeamMatchChallenge(...args);
export const respondToTeamMatchChallenge: typeof import("../repositories/firebase/teamMatchService").respondToTeamMatchChallenge = (...args) => getApiClient().teamMatch.respondToTeamMatchChallenge(...args);
export const sendTeamMatchChallenge: typeof import("../repositories/firebase/teamMatchService").sendTeamMatchChallenge = (...args) => getApiClient().teamMatch.sendTeamMatchChallenge(...args);
export const subscribeTeamMatchChallenge: typeof import("../repositories/firebase/teamMatchService").subscribeTeamMatchChallenge = (...args) => getApiClient().teamMatch.subscribeTeamMatchChallenge(...args);
export const suggestTeamMatchChallengeAlternativeZone: typeof import("../repositories/firebase/teamMatchService").suggestTeamMatchChallengeAlternativeZone = (...args) => getApiClient().teamMatch.suggestTeamMatchChallengeAlternativeZone(...args);
