import { getApiClient } from "../api/client";
export type { OnboardingStep2Prefs, OnboardingStep3Platforms, OnboardingSummary, UserProfile } from "../repositories/firebase/userService";
export const fetchOnboardingSummary: typeof import("../repositories/firebase/userService").fetchOnboardingSummary = (...args) => getApiClient().users.fetchOnboardingSummary(...args);
export const getUserFriends: typeof import("../repositories/firebase/userService").getUserFriends = (...args) => getApiClient().users.getUserFriends(...args);
export const getUserProfile: typeof import("../repositories/firebase/userService").getUserProfile = (...args) => getApiClient().users.getUserProfile(...args);
export const getUserSportProfile: typeof import("../repositories/firebase/userService").getUserSportProfile = (...args) => getApiClient().users.getUserSportProfile(...args);
export const getUserSportRoleLabel: typeof import("../repositories/firebase/userService").getUserSportRoleLabel = (...args) => getApiClient().users.getUserSportRoleLabel(...args);
export const isEaIdAvailable: typeof import("../repositories/firebase/userService").isEaIdAvailable = (...args) => getApiClient().users.isEaIdAvailable(...args);
export const isEmailAvailable: typeof import("../repositories/firebase/userService").isEmailAvailable = (...args) => getApiClient().users.isEmailAvailable(...args);
export const isFaceitIdAvailable: typeof import("../repositories/firebase/userService").isFaceitIdAvailable = (...args) => getApiClient().users.isFaceitIdAvailable(...args);
export const isPhoneAvailable: typeof import("../repositories/firebase/userService").isPhoneAvailable = (...args) => getApiClient().users.isPhoneAvailable(...args);
export const isPsnIdAvailable: typeof import("../repositories/firebase/userService").isPsnIdAvailable = (...args) => getApiClient().users.isPsnIdAvailable(...args);
export const isSteamIdAvailable: typeof import("../repositories/firebase/userService").isSteamIdAvailable = (...args) => getApiClient().users.isSteamIdAvailable(...args);
export const isUsernameAvailable: typeof import("../repositories/firebase/userService").isUsernameAvailable = (...args) => getApiClient().users.isUsernameAvailable(...args);
export const isXboxIdAvailable: typeof import("../repositories/firebase/userService").isXboxIdAvailable = (...args) => getApiClient().users.isXboxIdAvailable(...args);
export const normalizePhoneForSave: typeof import("../repositories/firebase/userService").normalizePhoneForSave = (...args) => getApiClient().users.normalizePhoneForSave(...args);
export const refreshUserStats: typeof import("../repositories/firebase/userService").refreshUserStats = (...args) => getApiClient().users.refreshUserStats(...args);
export const saveOnboardingStep2: typeof import("../repositories/firebase/userService").saveOnboardingStep2 = (...args) => getApiClient().users.saveOnboardingStep2(...args);
export const saveOnboardingStep3Platforms: typeof import("../repositories/firebase/userService").saveOnboardingStep3Platforms = (...args) => getApiClient().users.saveOnboardingStep3Platforms(...args);
