import { ZoneAdminModule } from "./types";

export const ZONE_ADMIN_MODULES: ZoneAdminModule[] = [
  {
    id: "bookings_matchrooms",
    title: "Bookings & Matchrooms",
    description: "Requests, counter-offers, lifecycle, and payment state",
    route: "/zone/modules/bookings",
    icon: "bookings",
    tag: "Core",
  },
  {
    id: "resources",
    title: "Resources",
    description: "Per-branch seat and court allocation with live statuses",
    route: "/zone/modules/resources",
    icon: "resources",
  },
  {
    id: "pricing_promotions",
    title: "Pricing & Promotions",
    description: "Scheduled rules, discounts, and off-peak campaigns",
    route: "/zone/modules/pricing",
    icon: "pricing",
  },
  {
    id: "support_safety",
    title: "Support & Safety",
    description: "Complaints, tickets, warnings, and bans",
    route: "/zone/modules/support",
    icon: "support",
  },
  {
    id: "insights_security",
    title: "Insights & Security",
    description: "Operations KPIs, demand trends, and monitoring",
    route: "/zone/modules/insights",
    icon: "insights",
  },
  {
    id: "venue_settings",
    title: "Venue Settings",
    description: "Venue profile, contacts, branches, hours, and policies",
    route: "/zone/modules/settings",
    icon: "settings",
    tag: "Setup",
  },
  {
    id: "migration_tools",
    title: "Migration Tools",
    description: "Migration status, repair jobs, and retry controls",
    route: "/zone/modules/migration-tools",
    icon: "databaseMigration",
    tag: "System",
  },
  {
    id: "audit_security",
    title: "Audit & Security",
    description: "Change history for bookings, pricing, resources, and migrations",
    route: "/zone/modules/audit",
    icon: "auditTrail",
    tag: "System",
  },
  {
    id: "notifications_center",
    title: "Notifications Center",
    description: "Realtime alerts, reminders, and targeted updates",
    route: "/zone/modules/notifications",
    icon: "notifications",
  },
  {
    id: "wallet",
    title: "Wallet",
    description: "Earnings, matchroom payouts, and withdrawal requests",
    route: "/zone/wallet",
    icon: "wallet",
    tag: "Finance",
  },
];

