import { StyleSheet } from "react-native";
import { COLORS, FONTS, RADII, SPACING, TEXT_SIZES } from "../../../src/theme";

export default StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    segmentTabs: {
        marginBottom: SPACING.md,
    },
    tabTitle: {
        fontSize: 13,
        fontFamily: FONTS.body,
    },
    errorBox: {
        flexDirection: "row",
        alignItems: "center",
        borderColor: COLORS.error,
        borderWidth: 1,
        backgroundColor: "rgba(239, 83, 80, 0.1)",
        borderRadius: RADII.sm,
        padding: SPACING.sm,
        marginBottom: SPACING.md,
    },
    errorText: {
        color: COLORS.error,
        marginLeft: SPACING.xs,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        flex: 1,
    },
    content: {
        paddingBottom: SPACING.xxl + 24,
    },
    filtersToggle: {
        height: 48,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: RADII.md,
        backgroundColor: COLORS.cardDark,
        paddingHorizontal: SPACING.md,
        alignItems: "center",
        justifyContent: "space-between",
        flexDirection: "row",
        marginBottom: SPACING.sm,
    },
    filtersToggleLeft: {
        flexDirection: "row",
        alignItems: "center",
    },
    filtersToggleText: {
        marginLeft: SPACING.xs,
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    filtersWrap: {
        gap: SPACING.sm,
        marginBottom: SPACING.md,
    },
    filterChip: {
        minWidth: 84,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm - 1,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardBackground,
        marginRight: SPACING.sm,
        alignItems: "center",
        justifyContent: "center",
    },
    filterChipActive: {
        borderColor: COLORS.accent,
        backgroundColor: COLORS.cardDark,
    },
    filterChipText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: 13,
        textTransform: "capitalize",
    },
    filterChipTextActive: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontWeight: "700",
    },
    emptyText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    requestCard: {
        backgroundColor: COLORS.cardDark,
        borderColor: COLORS.cardBorder,
        borderWidth: 1,
        borderRadius: 20,
        padding: SPACING.md,
        marginBottom: SPACING.sm,
    },
    requestCardActive: {
        borderColor: COLORS.accent,
        backgroundColor: "rgba(66, 165, 245, 0.08)",
    },
    requestTopRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        gap: SPACING.sm,
    },
    requestTitle: {
        flex: 1,
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.label,
    },
    requestStatus: {
        color: COLORS.accent,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
        textTransform: "uppercase",
    },
    requestMeta: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginTop: 4,
    },
    flagRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        marginTop: SPACING.sm,
        gap: SPACING.xs,
    },
    flagPill: {
        paddingHorizontal: SPACING.sm,
        height: 24,
        borderRadius: RADII.pill,
        backgroundColor: "rgba(255,255,255,0.05)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.1)",
        justifyContent: "center",
        marginTop: SPACING.sm,
    },
    flagText: {
        color: COLORS.warning,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.xs + 1,
        textTransform: "uppercase",
    },
    detailsCard: {
        marginTop: SPACING.md,
        backgroundColor: COLORS.cardDark,
        borderColor: COLORS.cardBorder,
        borderWidth: 1,
        borderRadius: 20,
        padding: SPACING.md,
    },
    detailsTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.subheading,
        marginBottom: SPACING.sm,
    },
    detailsLine: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginBottom: 4,
    },
    actionsRow: {
        flexDirection: "row",
        gap: SPACING.sm,
        marginTop: SPACING.sm,
        marginBottom: SPACING.sm,
    },
    actionButton: {
        flex: 1,
        height: 46,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
    },
    acceptButton: {
        backgroundColor: COLORS.success,
    },
    rejectButton: {
        backgroundColor: COLORS.error,
    },
    counterButton: {
        backgroundColor: COLORS.accent,
        flex: 0,
        minWidth: 120,
        paddingHorizontal: SPACING.sm,
    },
    walkinCreateButton: {
        backgroundColor: COLORS.accent,
        marginTop: SPACING.sm,
    },
    actionText: {
        color: "#FFF",
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
    },
    formLabel: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginTop: SPACING.xs,
        marginBottom: SPACING.xs,
    },
    input: {
        height: 48,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.inputBackground,
        color: COLORS.text,
        paddingHorizontal: SPACING.md,
        paddingTop: 0,
        paddingBottom: 0,
        marginBottom: SPACING.sm,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.input,
        lineHeight: 20,
        includeFontPadding: false,
        textAlignVertical: "center",
    },
    inputMultiline: {
        height: 84,
        textAlignVertical: "top",
        paddingTop: SPACING.sm,
    },
    counterHeader: {
        marginTop: SPACING.md,
        marginBottom: SPACING.md,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    dateRow: {
        flexDirection: "row",
        gap: SPACING.sm,
        marginBottom: SPACING.sm,
    },
    dateField: {
        flex: 1,
        height: 48,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardBackground,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: SPACING.xs,
        paddingHorizontal: SPACING.sm,
    },
    dateFieldText: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.label,
    },
    matchroomCard: {
        backgroundColor: COLORS.cardDark,
        borderColor: COLORS.cardBorder,
        borderWidth: 1,
        borderRadius: 20,
        padding: SPACING.md,
        marginBottom: SPACING.sm,
    },
    matchroomCardFocused: {
        borderColor: COLORS.accent,
        backgroundColor: "rgba(66, 165, 245, 0.1)",
    },
    matchroomFocusedWrap: {
        borderWidth: 1,
        borderColor: COLORS.accent,
        borderRadius: 22, // Match card radius + padding
        padding: 2,
        marginBottom: SPACING.sm,
        backgroundColor: "rgba(66, 165, 245, 0.05)",
    },
    resultsCount: {
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm,
        marginBottom: SPACING.xs,
    },
    resultsCountText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    walkinChipOverlay: {
        marginTop: -6,
        alignSelf: "flex-start",
        marginLeft: SPACING.sm,
    },
    walkinChip: {
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: "rgba(255, 193, 7, 0.35)",
        backgroundColor: "rgba(255, 193, 7, 0.12)",
        paddingHorizontal: SPACING.sm,
        paddingVertical: 3,
    },
    walkinCard: {
        backgroundColor: COLORS.cardDark,
        borderColor: COLORS.cardBorder,
        borderWidth: 1,
        borderRadius: 20,
        padding: SPACING.md,
    },
    walkinTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.subheading,
    },
    walkinSubtitle: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginTop: 4,
        marginBottom: SPACING.sm,
    },
    chipScroll: {
        marginBottom: SPACING.sm,
    },
    formGrid: {
        flexDirection: "row",
        gap: SPACING.sm,
    },
    halfInput: {
        flex: 1,
    },
    walkinInfo: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginTop: SPACING.sm,
        marginBottom: SPACING.xs,
    },
    pickerOverlay: {
        flex: 1,
        justifyContent: "flex-end",
        paddingHorizontal: SPACING.md,
        paddingBottom: SPACING.md,
    },
    pickerBackdrop: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(0,0,0,0.7)",
    },
    pickerSheet: {
        backgroundColor: COLORS.cardBackground,
        borderTopLeftRadius: RADII.lg,
        borderTopRightRadius: RADII.lg,
        padding: SPACING.md,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
    },
    pickerHandle: {
        width: 44,
        height: 5,
        borderRadius: RADII.pill,
        backgroundColor: COLORS.cardBorder,
        alignSelf: "center",
        marginBottom: SPACING.sm,
    },
    pickerHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: SPACING.sm,
    },
    pickerTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.body,
    },
    pickerAction: {
        color: COLORS.accent,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.label,
    },
    calendarContainer: {
        backgroundColor: COLORS.cardBackground,
        borderRadius: RADII.md,
        padding: SPACING.md,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
    },
    calendarHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: SPACING.sm,
    },
    calendarNavButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: COLORS.cardDark,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
    },
    calendarNavText: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 18,
    },
    calendarTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.body,
    },
    weekdayRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: SPACING.xs,
    },
    weekdayLabel: {
        width: "14.28%",
        textAlign: "center",
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    calendarGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
    },
    dayCell: {
        width: "14.28%",
        height: 40,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 4,
        borderRadius: RADII.sm,
    },
    dayCellSelected: {
        borderWidth: 1,
        borderColor: COLORS.accent,
        backgroundColor: "transparent",
    },
    dayText: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    dayTextSelected: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
    },
    timePickerRow: {
        flexDirection: "row",
        gap: SPACING.md,
        marginTop: SPACING.sm,
    },
    timeColumn: {
        flex: 1,
        gap: SPACING.sm,
    },
    timeOption: {
        paddingVertical: 10,
        borderRadius: RADII.md,
        backgroundColor: COLORS.cardBackground,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        alignItems: "center",
    },
    timeOptionActive: {
        borderColor: COLORS.accent,
    },
    timeOptionText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    timeOptionTextActive: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
    },
});

