import { StyleSheet } from "react-native";
import { COLORS, CONTROL_SIZES, CTA, FONTS, RADII, SPACING, TEXT_SIZES } from "../../../src/theme";

export default StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    segmentTabs: {
        marginBottom: SPACING.md,
    },
    tabTitle: {
        fontSize: 12,
        fontFamily: FONTS.clean,
    },
    errorBox: {
        flexDirection: "row",
        alignItems: "center",
        borderColor: COLORS.error,
        borderWidth: 1,
        backgroundColor: "rgba(239, 83, 80, 0.1)",
        borderRadius: RADII.sm,
        padding: SPACING.sm,
        marginBottom: SPACING.md,
    },
    errorText: {
        color: COLORS.error,
        marginLeft: SPACING.xs,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        flex: 1,
    },
    content: {
        paddingBottom: SPACING.xxl + 24,
    },
    searchRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
        marginBottom: SPACING.md,
    },
    searchBar: {
        flex: 1,
        height: 48,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.inputBackground,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: SPACING.md,
    },
    searchInput: {
        flex: 1,
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.input,
        paddingVertical: 0,
        paddingHorizontal: SPACING.sm,
    },
    filterButton: {
        width: 48,
        height: 48,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.inputBackground,
        alignItems: "center",
        justifyContent: "center",
    },
    filterButtonPressed: {
        opacity: 0.9,
    },
    filterBadge: {
        position: "absolute",
        top: -4,
        right: -4,
        minWidth: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: COLORS.accent,
        borderWidth: 2,
        borderColor: COLORS.backgroundDark,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 4,
    },
    filterBadgeText: {
        color: "#FFF",
        fontFamily: FONTS.heading,
        fontSize: 10,
        fontWeight: "700",
    },
    filtersToggle: {
        height: 48,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: RADII.lg,
        backgroundColor: COLORS.cardDark,
        paddingHorizontal: SPACING.md,
        alignItems: "center",
        justifyContent: "space-between",
        flexDirection: "row",
        marginBottom: SPACING.sm,
    },
    filtersToggleLeft: {
        flexDirection: "row",
        alignItems: "center",
    },
    filtersToggleText: {
        marginLeft: SPACING.xs,
        color: COLORS.text,
        fontFamily: FONTS.interMedium,
        fontSize: TEXT_SIZES.caption,
    },
    filtersWrap: {
        gap: SPACING.sm,
        marginBottom: SPACING.md,
    },
    filterDrawer: {
        flex: 1,
    },
    filterDrawerContent: {
        flex: 1,
    },
    filtersDrawerBody: {
        paddingTop: SPACING.sm,
        gap: SPACING.md,
    },
    filterDrawerFooter: {
        backgroundColor: COLORS.cardDark,
    },
    filterSectionLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.interSemiBold,
        fontSize: TEXT_SIZES.caption,
        marginBottom: SPACING.xs,
        marginTop: SPACING.sm,
        textTransform: "uppercase",
    },
    filterChip: {
        minWidth: 84,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm - 1,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardDark,
        marginRight: SPACING.sm,
        alignItems: "center",
        justifyContent: "center",
    },
    filterChipActive: {
        borderColor: COLORS.accent,
        backgroundColor: `${COLORS.accent}14`,
    },
    filterChipText: {
        color: COLORS.muted,
        fontFamily: FONTS.interRegular,
        fontSize: 13,
        textTransform: "capitalize",
    },
    filterChipTextActive: {
        color: COLORS.accent,
        fontFamily: FONTS.interSemiBold,
    },
    emptyText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    emptyStateCard: {
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: CONTROL_SIZES.cardRadius + 2,
        backgroundColor: COLORS.cardDark,
        padding: SPACING.lg,
        alignItems: "center",
    },
    emptyStateTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.label,
        marginBottom: 4,
    },
    requestCard: {
        backgroundColor: COLORS.cardDark,
        borderColor: COLORS.cardBorder,
        borderWidth: 1,
        borderRadius: CONTROL_SIZES.cardRadius + 2,
        padding: SPACING.md,
        marginBottom: SPACING.sm,
    },
    requestCardActive: {
        borderColor: COLORS.accent,
        backgroundColor: "rgba(66, 165, 245, 0.08)",
    },
    requestTopRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        gap: SPACING.sm,
    },
    requestTitle: {
        flex: 1,
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.label,
    },
    requestStatus: {
        color: COLORS.accent,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
        textTransform: "uppercase",
    },
    requestMeta: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginTop: 4,
    },
    flagRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        marginTop: SPACING.sm,
        gap: SPACING.xs,
    },
    flagPill: {
        paddingHorizontal: SPACING.sm,
        height: 24,
        borderRadius: RADII.pill,
        backgroundColor: "rgba(255,255,255,0.05)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.1)",
        justifyContent: "center",
        marginTop: SPACING.sm,
    },
    flagText: {
        color: COLORS.warning,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.xs + 1,
        textTransform: "uppercase",
    },
    detailsCard: {
        marginTop: SPACING.md,
        backgroundColor: COLORS.cardDark,
        borderColor: COLORS.cardBorder,
        borderWidth: 1,
        borderRadius: CONTROL_SIZES.cardRadius + 2,
        padding: SPACING.md,
    },
    inlineActionsCard: {
        borderTopWidth: 1,
        borderTopColor: COLORS.cardBorder,
        paddingHorizontal: SPACING.md,
        paddingTop: SPACING.sm,
        paddingBottom: SPACING.md,
    },
    requestExpandedCard: {
        borderWidth: 1.5,
        borderColor: COLORS.accent,
        borderRadius: 20,
        backgroundColor: COLORS.cardDark,
        marginBottom: SPACING.sm,
        overflow: "hidden",
    },
    requestEmbeddedMatchroomCard: {
        marginBottom: 0,
        borderWidth: 0,
        borderRadius: 0,
        backgroundColor: "transparent",
    },
    pendingOfferPanel: {
        borderTopWidth: 1,
        borderTopColor: COLORS.cardBorder,
        padding: SPACING.md,
        gap: 4,
    },
    pendingOfferTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.label,
    },
    pendingOfferText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    pendingOfferExpiry: {
        color: COLORS.warning,
        fontFamily: FONTS.interSemiBold,
        fontSize: TEXT_SIZES.caption,
        marginTop: 4,
    },
    detailsTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.subheading,
        marginBottom: SPACING.sm,
    },
    detailsLine: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginBottom: 4,
    },
    actionsRow: {
        flexDirection: "row",
        gap: SPACING.xs,
        marginTop: SPACING.xs,
    },
    actionButton: {
        flex: 1,
        height: 46,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: 4,
        paddingHorizontal: SPACING.xs,
    },
    acceptButton: {
        backgroundColor: COLORS.success,
    },
    rejectButton: {
        backgroundColor: COLORS.error,
    },
    counterButton: {
        backgroundColor: COLORS.accent,
        paddingHorizontal: SPACING.xs,
    },
    walkinCreateButton: {
        ...CTA.primaryButton,
        marginTop: SPACING.sm,
        minHeight: 52,
    },
    actionText: {
        color: "#FFF",
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.xs + 1,
        textAlign: "center",
        flexShrink: 1,
    },
    walkinCreateText: {
        ...CTA.primaryButtonText,
        fontSize: TEXT_SIZES.label,
    },
    formLabel: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginTop: SPACING.xs,
        marginBottom: SPACING.xs,
    },
    input: {
        height: 48,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.inputBackground,
        color: COLORS.text,
        paddingHorizontal: SPACING.md,
        paddingTop: 0,
        paddingBottom: 0,
        marginBottom: SPACING.sm,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.input,
        lineHeight: 20,
        includeFontPadding: false,
        textAlignVertical: "center",
    },
    inputMultiline: {
        height: 84,
        textAlignVertical: "top",
        paddingTop: SPACING.sm,
    },
    counterHeader: {
        marginTop: SPACING.md,
        marginBottom: SPACING.md,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    dateRow: {
        flexDirection: "row",
        gap: SPACING.sm,
        marginBottom: SPACING.sm,
    },
    scheduleOptionCard: {
        backgroundColor: COLORS.cardDark,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: RADII.lg,
        padding: SPACING.md,
        marginBottom: SPACING.sm,
    },
    scheduleOptionHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: SPACING.xs,
    },
    removeOptionButton: {
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.cardBackground,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
    },
    addOptionButton: {
        minHeight: 48,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: COLORS.accent,
        backgroundColor: "rgba(66, 165, 245, 0.08)",
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: SPACING.xs,
        marginBottom: SPACING.sm,
    },
    addOptionText: {
        color: COLORS.accent,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
    },
    dateField: {
        flex: 1,
        height: 48,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardBackground,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: SPACING.xs,
        paddingHorizontal: SPACING.sm,
    },
    validationText: {
        color: COLORS.warning,
        fontFamily: FONTS.interMedium,
        fontSize: TEXT_SIZES.caption,
        lineHeight: 18,
    },
    dateFieldText: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.label,
    },
    matchroomCard: {
        backgroundColor: COLORS.cardDark,
        borderColor: COLORS.cardBorder,
        borderWidth: 1,
        borderRadius: 20,
        padding: SPACING.md,
        marginBottom: SPACING.sm,
    },
    matchroomCardFocused: {
        borderColor: COLORS.accent,
        backgroundColor: "rgba(66, 165, 245, 0.1)",
    },
    matchroomFocusedWrap: {
        borderWidth: 1.5,
        borderColor: COLORS.accent,
        borderRadius: 20, // Match card radius exactly
        padding: 0,
        marginBottom: SPACING.sm,
        backgroundColor: "rgba(66, 165, 245, 0.05)",
        overflow: "hidden",
    },
    matchroomCardCollapsed: {
        marginBottom: 0,
    },
    resultsCount: {
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm,
        marginBottom: SPACING.xs,
    },
    resultsCountText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    walkinMatchroomItem: {
        marginBottom: SPACING.sm,
    },
    walkinCard: {
        backgroundColor: COLORS.cardDark,
        borderColor: COLORS.cardBorder,
        borderWidth: 1,
        borderRadius: CONTROL_SIZES.cardRadius + 2,
        padding: SPACING.lg,
        marginBottom: SPACING.lg,
    },
    walkinTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.subheading,
    },
    walkinSubtitle: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginTop: 4,
        marginBottom: SPACING.md,
        lineHeight: 19,
    },
    chipScroll: {
        marginBottom: SPACING.sm,
    },
    formGrid: {
        flexDirection: "row",
        gap: SPACING.sm,
    },
    halfInput: {
        flex: 1,
    },
    walkinInfo: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginTop: SPACING.sm,
        marginBottom: SPACING.xs,
    },
    pickerOverlay: {
        flex: 1,
        justifyContent: "flex-end",
        paddingHorizontal: SPACING.md,
        paddingBottom: SPACING.md,
    },
    pickerBackdrop: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(0,0,0,0.7)",
    },
    pickerSheet: {
        backgroundColor: COLORS.cardBackground,
        borderTopLeftRadius: RADII.lg,
        borderTopRightRadius: RADII.lg,
        padding: SPACING.md,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        paddingBottom: SPACING.xl,
    },
    pickerHandle: {
        width: 44,
        height: 5,
        borderRadius: RADII.pill,
        backgroundColor: COLORS.cardBorder,
        alignSelf: "center",
        marginBottom: SPACING.sm,
    },
    pickerHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: SPACING.sm,
    },
    pickerTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.body,
    },
    pickerAction: {
        color: COLORS.accent,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.label,
    },
    calendarContainer: {
        backgroundColor: COLORS.cardBackground,
        borderRadius: RADII.md,
        padding: SPACING.md,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
    },
    calendarHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: SPACING.sm,
    },
    calendarNavButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: COLORS.cardDark,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
    },
    calendarNavText: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 18,
    },
    calendarTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.body,
    },
    weekdayRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: SPACING.xs,
    },
    weekdayLabel: {
        width: "14.28%",
        textAlign: "center",
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    calendarGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
    },
    dayCell: {
        width: "14.28%",
        height: 40,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 4,
        borderRadius: RADII.sm,
    },
    dayCellSelected: {
        borderWidth: 1,
        borderColor: COLORS.accent,
        backgroundColor: "transparent",
    },
    dayText: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    dayTextSelected: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
    },
    timePickerRow: {
        flexDirection: "row",
        gap: SPACING.md,
        marginTop: SPACING.sm,
    },
    timePickerScroll: {
        maxHeight: 460,
    },
    timePickerScrollContent: {
        paddingBottom: SPACING.lg,
    },
    timeColumn: {
        flex: 1,
        gap: SPACING.sm,
    },
    timeOption: {
        paddingVertical: 10,
        borderRadius: RADII.md,
        backgroundColor: COLORS.cardBackground,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        alignItems: "center",
    },
    timeOptionActive: {
        borderColor: COLORS.accent,
    },
    timeOptionText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    timeOptionTextActive: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
    },
    // Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.85)",
        justifyContent: "flex-end",
    },
    modalContent: {
        backgroundColor: COLORS.cardBackground,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
    },
    modalHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 24,
        borderBottomWidth: 1,
        borderColor: COLORS.cardBorder,
    },
    modalTitle: {
        color: COLORS.text,
        fontSize: 20,
        fontFamily: FONTS.heading,
        fontWeight: "bold",
    },
    modalSubtitle: {
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.caption,
        fontFamily: FONTS.body,
        marginTop: 2,
    },
    counterForm: {
        flexShrink: 1,
    },
    counterFormContent: {
        paddingHorizontal: SPACING.xl,
        paddingTop: SPACING.lg,
        paddingBottom: SPACING.md,
        gap: SPACING.md,
    },
    counterFooter: {
        paddingHorizontal: SPACING.xl,
        paddingTop: SPACING.sm,
    },
    modalActionsRow: {
        flexDirection: "row",
        gap: SPACING.sm,
    },
    modalActionButton: {
        flex: 1,
    },
    allocateSheet: {
        flexShrink: 1,
    },
    allocateBodyScroll: {
        flexShrink: 1,
        minHeight: 0,
    },
    allocateSheetBody: {
        paddingTop: SPACING.md,
        paddingBottom: SPACING.lg,
        gap: SPACING.md,
    },
    allocateSummaryCard: {
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: 18,
        backgroundColor: COLORS.cardDark,
        padding: SPACING.md,
        gap: 4,
    },
    allocateSheetTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.label,
    },
    allocateSheetMeta: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    allocateBranchWrap: {
        gap: SPACING.sm,
    },
    allocateSectionLabel: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
        textTransform: "uppercase",
    },
    allocateBranchChip: {
        minWidth: 96,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm - 1,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardBackground,
        marginRight: SPACING.sm,
        alignItems: "center",
        justifyContent: "center",
    },
    allocateBranchChipActive: {
        borderColor: COLORS.accent,
        backgroundColor: COLORS.cardDark,
    },
    allocateBranchChipText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    allocateBranchChipTextActive: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontWeight: "700",
    },
    allocateResourcesWrap: {
        gap: SPACING.sm,
    },
    allocateResourcesHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    allocateSelectionCount: {
        color: COLORS.accent,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
    },
    allocateLoadingWrap: {
        minHeight: 180,
        alignItems: "center",
        justifyContent: "center",
    },
    allocateResourceList: {
        paddingBottom: SPACING.md,
    },
    allocateEmptyText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    allocateResourceCard: {
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: 18,
        backgroundColor: COLORS.cardDark,
        padding: SPACING.md,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: SPACING.sm,
        marginBottom: SPACING.sm,
    },
    allocateResourceCardActive: {
        borderColor: COLORS.accent,
        backgroundColor: "rgba(66, 165, 245, 0.08)",
    },
    allocateResourceInfo: {
        flex: 1,
        gap: 4,
    },
    allocateResourceLabel: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.label,
    },
    allocateResourceMeta: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        textTransform: "capitalize",
    },
    allocateResourceTick: {
        width: 28,
        height: 28,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.cardBackground,
    },
    allocateResourceTickActive: {
        borderColor: COLORS.accent,
        backgroundColor: COLORS.accent,
    },
    allocateWarningCard: {
        flexDirection: "row",
        alignItems: "flex-start",
        gap: SPACING.xs,
        padding: SPACING.sm,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: COLORS.warning,
        backgroundColor: "rgba(255, 193, 7, 0.12)",
    },
    allocateWarningText: {
        flex: 1,
        color: COLORS.warning,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    allocateFooter: {
        paddingHorizontal: SPACING.xl,
        paddingTop: SPACING.sm,
        backgroundColor: COLORS.cardDark,
    },
    allocateSubmitButton: {
        ...CTA.primaryButton,
        minHeight: 52,
    },
    allocateSubmitButtonDisabled: {
        opacity: 0.45,
    },
    allocateSubmitText: {
        ...CTA.primaryButtonText,
        fontSize: TEXT_SIZES.label,
    },
});

