import { StyleSheet } from "react-native";
import { COLORS, FONTS, RADII, SPACING, TEXT_SIZES } from "../../../src/theme";

export default StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    loadingWrap: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.backgroundDark,
    },
    segmentTabs: {
        marginBottom: SPACING.md,
    },
    segmentTabText: {
        fontSize: TEXT_SIZES.caption,
    },
    liveBanner: {
        borderWidth: 1,
        borderColor: "rgba(0, 230, 118, 0.35)",
        backgroundColor: "rgba(0, 230, 118, 0.1)",
        borderRadius: 14,
        paddingHorizontal: SPACING.md,
        height: 40,
        alignItems: "center",
        flexDirection: "row",
        marginBottom: SPACING.md,
    },
    liveBannerText: {
        marginLeft: SPACING.xs,
        color: COLORS.successBright,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    content: {
        paddingBottom: SPACING.xxl + 22,
    },
    summaryGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: 22,
        backgroundColor: COLORS.cardDark,
        overflow: "hidden",
        marginBottom: SPACING.md,
    },
    summaryCard: {
        width: "50%",
        minHeight: 92,
        padding: SPACING.md,
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
        borderColor: COLORS.cardBorder,
    },
    summaryCardLeft: {
        borderRightWidth: 1,
    },
    summaryCardTop: {
        borderBottomWidth: 1,
    },
    summaryIconWrap: {
        width: 34,
        height: 34,
        borderRadius: 17,
        borderWidth: 1,
        alignItems: "center",
        justifyContent: "center",
    },
    summaryTextWrap: {
        flex: 1,
    },
    summaryValue: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.xl,
        marginTop: 2,
    },
    summaryLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    card: {
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        backgroundColor: COLORS.cardDark,
        borderRadius: 20,
        padding: SPACING.md,
        marginBottom: SPACING.md,
    },
    cardTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.subheading,
        marginBottom: SPACING.sm,
    },
    metricBlock: {
        paddingBottom: SPACING.sm,
        marginBottom: SPACING.sm,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(255,255,255,0.08)",
    },
    metricRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: SPACING.xs,
    },
    metricRowTight: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 2,
    },
    metricLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        flex: 1,
    },
    metricValue: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption + 1,
    },
    metricHint: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.xs + 1,
    },
    chipScroll: {
        marginBottom: SPACING.sm,
    },
    chip: {
        marginRight: SPACING.sm,
        minWidth: 84,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardBackground,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm - 1,
        justifyContent: "center",
        alignItems: "center",
    },
    chipActive: {
        borderColor: COLORS.accent,
        backgroundColor: COLORS.cardDark,
    },
    chipText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: 13,
    },
    chipTextActive: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontWeight: "700",
    },
    financeSummaryGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        marginBottom: SPACING.sm,
    },
    financeSummaryCard: {
        width: "48%",
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardBackground,
        borderRadius: RADII.md,
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.md,
        marginBottom: SPACING.sm,
    },
    financeSummaryValue: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.body,
        marginBottom: 2,
    },
    financeSummaryLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    barRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: SPACING.xs,
    },
    chartRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: SPACING.sm,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.08)",
        borderRadius: RADII.lg,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm,
        backgroundColor: "rgba(255,255,255,0.02)",
        gap: SPACING.sm,
    },
    chartRowActive: {
        borderColor: COLORS.accent,
        backgroundColor: "rgba(66, 165, 245, 0.1)",
    },
    barLabel: {
        width: 68,
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    branchBarLabel: {
        width: 112,
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    barLabelWide: {
        width: 112,
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    barTrack: {
        flex: 1,
        height: 8,
        borderRadius: RADII.pill,
        backgroundColor: "rgba(255,255,255,0.1)",
        overflow: "hidden",
    },
    barFill: {
        height: 8,
        borderRadius: RADII.pill,
        backgroundColor: COLORS.accent,
    },
    barValue: {
        width: 62,
        textAlign: "right",
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    barValueWide: {
        width: 96,
        textAlign: "right",
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    resourceInsightCard: {
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardBackground,
        borderRadius: RADII.lg,
        padding: SPACING.md,
        marginBottom: SPACING.sm,
    },
    resourceInsightHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
    },
    resourceInsightIcon: {
        width: 34,
        height: 34,
        borderRadius: 17,
        borderWidth: 1,
        borderColor: "rgba(66, 165, 245, 0.35)",
        backgroundColor: "rgba(66, 165, 245, 0.12)",
        alignItems: "center",
        justifyContent: "center",
    },
    resourceInsightTitleWrap: {
        flex: 1,
        minWidth: 0,
    },
    resourceInsightTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.body,
    },
    resourceInsightStats: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: SPACING.sm,
        marginTop: SPACING.sm,
    },
    resourceInsightStat: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.xs + 1,
    },
    emptyText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
});

