import { StyleSheet } from "react-native";
import { COLORS, CONTROL_SIZES, FONTS, RADII, SPACING, TEXT_SIZES } from "../../../src/theme";

export default StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    segmentTabs: {
        marginBottom: SPACING.md,
    },
    searchRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
        marginBottom: SPACING.md,
    },
    searchBar: {
        flex: 1,
        minWidth: 0,
        minHeight: 50,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: RADII.lg,
        backgroundColor: COLORS.cardDark,
        paddingHorizontal: SPACING.md,
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
    },
    searchInput: {
        flex: 1,
        minWidth: 0,
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.body,
        paddingVertical: 0,
    },
    filterButton: {
        width: 50,
        height: 50,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: RADII.lg,
        backgroundColor: COLORS.cardDark,
        alignItems: "center",
        justifyContent: "center",
    },
    filterButtonPressed: {
        opacity: 0.85,
        borderColor: COLORS.accent,
    },
    filterBadge: {
        position: "absolute",
        top: -5,
        right: -5,
        minWidth: 19,
        height: 19,
        borderRadius: 10,
        backgroundColor: COLORS.accent,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 4,
    },
    filterBadgeText: {
        color: "#FFF",
        fontFamily: FONTS.interSemiBold,
        fontSize: 10,
    },
    filterDrawer: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    filterDrawerContent: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    filtersDrawerBody: {
        paddingHorizontal: SPACING.lg,
        paddingBottom: SPACING.xl,
        gap: SPACING.lg,
    },
    filtersWrap: {
        gap: SPACING.md,
    },
    filterSectionLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.interSemiBold,
        fontSize: TEXT_SIZES.caption,
        letterSpacing: 0.8,
        textTransform: "uppercase",
    },
    filterChipWrap: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: SPACING.sm,
    },
    filterDrawerFooter: {
        flexDirection: "row",
        gap: SPACING.sm,
        backgroundColor: COLORS.backgroundDark,
    },
    content: {
        paddingBottom: SPACING.xxl + 28,
    },
    errorBox: {
        borderWidth: 1,
        borderColor: COLORS.error,
        backgroundColor: "rgba(239, 83, 80, 0.1)",
        borderRadius: RADII.sm,
        padding: SPACING.sm,
        marginBottom: SPACING.md,
    },
    errorText: {
        color: COLORS.error,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    noticeBox: {
        borderWidth: 1,
        borderColor: COLORS.warning,
        backgroundColor: "rgba(255, 193, 7, 0.12)",
        borderRadius: RADII.sm,
        padding: SPACING.sm,
        marginBottom: SPACING.md,
    },
    noticeText: {
        color: COLORS.warning,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    summaryGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: CONTROL_SIZES.cardRadius + 2,
        backgroundColor: COLORS.cardDark,
        overflow: "hidden",
        marginBottom: SPACING.md,
    },
    summaryCard: {
        width: "50%",
        minHeight: 62,
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.md,
    },
    summaryCardLeft: {
        borderRightWidth: StyleSheet.hairlineWidth,
        borderRightColor: COLORS.cardBorder,
    },
    summaryCardTop: {
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: COLORS.cardBorder,
    },
    summaryIconWrap: {
        width: 32,
        height: 32,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
    },
    summaryTextWrap: {
        flex: 1,
        minWidth: 0,
    },
    summaryValue: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 19,
        lineHeight: 23,
        marginTop: 1,
    },
    summaryLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.interMedium,
        fontSize: 11,
        lineHeight: 14,
    },
    formCard: {
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: CONTROL_SIZES.cardRadius + 2,
        backgroundColor: COLORS.cardDark,
        padding: SPACING.md,
        marginBottom: SPACING.md,
    },
    listCard: {
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: CONTROL_SIZES.cardRadius + 2,
        backgroundColor: COLORS.cardDark,
        padding: SPACING.md,
    },
    formTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.subheading,
        marginBottom: SPACING.sm,
    },
    fieldLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginBottom: SPACING.xs,
    },
    input: {
        height: 48,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.inputBackground,
        color: COLORS.text,
        paddingHorizontal: SPACING.md,
        paddingTop: 0,
        paddingBottom: 0,
        marginBottom: SPACING.md,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.input,
        lineHeight: 20,
        includeFontPadding: false,
        textAlignVertical: "center",
    },
    row: {
        flexDirection: "row",
        justifyContent: "space-between",
        gap: SPACING.sm,
        marginBottom: SPACING.md,
    },
    fieldColumn: {
        flex: 1,
    },
    chipScroll: {
        marginBottom: SPACING.sm,
    },
    chip: {
        marginRight: SPACING.sm,
        minWidth: 84,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm - 1,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardDark,
        justifyContent: "center",
        alignItems: "center",
    },
    chipActive: {
        borderColor: COLORS.accent,
        backgroundColor: `${COLORS.accent}14`,
    },
    chipText: {
        color: COLORS.muted,
        fontFamily: FONTS.interRegular,
        fontSize: 13,
    },
    chipTextActive: {
        color: COLORS.accent,
        fontFamily: FONTS.interSemiBold,
    },
    dateField: {
        flex: 1,
        height: 48,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardBackground,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: SPACING.xs,
        paddingHorizontal: SPACING.sm,
    },
    dateFieldText: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.label,
    },
    clearDateButton: {
        flex: 1,
        height: 44,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: COLORS.accent,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "rgba(66, 165, 245, 0.12)",
        flexDirection: "row",
        gap: SPACING.xs,
    },
    clearDateButtonPressed: {
        opacity: 0.85,
    },
    clearDateText: {
        color: COLORS.accent,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
    },
    daysWrap: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: SPACING.xs,
        marginTop: SPACING.xs,
        marginBottom: SPACING.md,
    },
    dayChip: {
        height: 30,
        minWidth: 44,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardBackground,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: SPACING.xs,
    },
    dayChipActive: {
        borderColor: COLORS.accent,
        backgroundColor: COLORS.cardDark,
    },
    dayChipText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    dayChipTextActive: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontWeight: "700",
    },
    saveButton: {
        height: 46,
        borderRadius: 14,
        backgroundColor: COLORS.accent,
        alignItems: "center",
        justifyContent: "center",
    },
    saveButtonDisabled: {
        opacity: 0.6,
    },
    saveButtonText: {
        color: "#FFF",
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
    },
    emptyText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    ruleRow: {
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: 14,
        backgroundColor: "rgba(255,255,255,0.04)",
        padding: SPACING.sm,
        marginBottom: SPACING.xs,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    ruleBody: {
        flex: 1,
        paddingRight: SPACING.xs,
    },
    ruleName: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
        marginBottom: 2,
    },
    ruleMeta: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.xs + 1,
    },
    ruleActions: {
        alignItems: "flex-end",
        gap: SPACING.xs,
    },
    deleteButton: {
        paddingHorizontal: SPACING.sm,
        height: 24,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.error,
        justifyContent: "center",
    },
    deleteText: {
        color: COLORS.error,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.xs + 1,
    },
    pickerOverlay: {
        flex: 1,
        justifyContent: "flex-end",
        paddingHorizontal: SPACING.md,
        paddingBottom: SPACING.md,
    },
    pickerBackdrop: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(0,0,0,0.7)",
    },
    pickerSheet: {
        backgroundColor: COLORS.cardBackground,
        borderTopLeftRadius: RADII.lg,
        borderTopRightRadius: RADII.lg,
        padding: SPACING.md,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
    },
    pickerHandle: {
        width: 44,
        height: 5,
        borderRadius: 999,
        backgroundColor: COLORS.cardBorder,
        alignSelf: "center",
        marginBottom: SPACING.sm,
    },
    pickerHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: SPACING.sm,
    },
    pickerTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.body,
    },
    pickerAction: {
        color: COLORS.accent,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.label,
    },
    calendarContainer: {
        backgroundColor: COLORS.cardBackground,
        borderRadius: RADII.md,
        padding: SPACING.md,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
    },
    calendarHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: SPACING.sm,
    },
    calendarNavButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: COLORS.cardDark,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
    },
    calendarNavText: {
        color: COLORS.text,
        fontSize: 18,
        fontFamily: FONTS.heading,
    },
    calendarTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.body,
    },
    weekdayRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: SPACING.xs,
    },
    weekdayLabel: {
        width: "14.28%",
        textAlign: "center",
        color: COLORS.muted,
        fontSize: TEXT_SIZES.caption,
        fontFamily: FONTS.body,
    },
    calendarGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
    },
    dayCell: {
        width: "14.28%",
        height: 40,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 4,
        borderRadius: RADII.sm,
    },
    dayCellSelected: {
        borderWidth: 1,
        borderColor: COLORS.accent,
        backgroundColor: "transparent",
    },
    dayText: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    dayTextSelected: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
    },
    timePickerRow: {
        flexDirection: "row",
        gap: SPACING.md,
        marginTop: SPACING.sm,
    },
    timeColumn: {
        flex: 1,
        gap: SPACING.sm,
    },
    timeColumnScroll: {
        flex: 1,
    },
    timeColumnContent: {
        gap: SPACING.sm,
        paddingBottom: SPACING.sm,
    },
    timeOption: {
        paddingVertical: 10,
        borderRadius: RADII.md,
        backgroundColor: COLORS.cardBackground,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        alignItems: "center",
    },
    timeOptionActive: {
        backgroundColor: "transparent",
        borderColor: COLORS.accent,
    },
    timeOptionText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    timeOptionTextActive: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
    },
});


