import { StyleSheet } from "react-native";
import { COLORS, FONTS, RADII, SPACING, TEXT_SIZES } from "../../../src/theme";

export default StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    errorBox: {
        borderWidth: 1,
        borderColor: COLORS.error,
        borderRadius: RADII.sm,
        backgroundColor: "rgba(239, 83, 80, 0.1)",
        padding: SPACING.sm,
        marginBottom: SPACING.md,
    },
    errorText: {
        color: COLORS.error,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    noticeBox: {
        borderWidth: 1,
        borderColor: COLORS.warning,
        borderRadius: RADII.sm,
        backgroundColor: "rgba(255, 193, 7, 0.12)",
        padding: SPACING.sm,
        marginBottom: SPACING.md,
    },
    noticeText: {
        color: COLORS.warning,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    segmentTabs: {
        marginBottom: SPACING.md,
    },
    filtersToggle: {
        height: 48,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: RADII.md,
        backgroundColor: COLORS.cardDark,
        paddingHorizontal: SPACING.md,
        alignItems: "center",
        justifyContent: "space-between",
        flexDirection: "row",
        marginBottom: SPACING.md,
    },
    filtersToggleLeft: {
        flexDirection: "row",
        alignItems: "center",
    },
    filtersToggleText: {
        marginLeft: SPACING.xs,
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    fieldLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginBottom: SPACING.xs,
    },
    filterRow: {
        marginBottom: SPACING.md,
    },
    branchChip: {
        marginRight: SPACING.sm,
        minWidth: 84,
        backgroundColor: COLORS.cardBackground,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm - 1,
        justifyContent: "center",
        alignItems: "center",
    },
    branchChipActive: {
        borderColor: COLORS.accent,
        backgroundColor: COLORS.cardDark,
    },
    branchChipText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: 13,
    },
    branchChipTextActive: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontWeight: "700",
    },
    loadingWrap: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
    },
    content: {
        paddingBottom: SPACING.xxl + 28,
    },
    summaryGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: SPACING.sm,
        marginBottom: SPACING.md,
    },
    summaryCard: {
        width: "48%",
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: 20,
        backgroundColor: COLORS.cardDark,
        paddingVertical: SPACING.sm,
        alignItems: "center",
    },
    summaryValue: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.xl,
    },
    summaryLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    chipScroll: {
        marginBottom: SPACING.md,
    },
    filterChip: {
        marginRight: SPACING.sm,
        minWidth: 84,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardBackground,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm - 1,
        justifyContent: "center",
        alignItems: "center",
    },
    filterChipActive: {
        borderColor: COLORS.accent,
        backgroundColor: COLORS.cardDark,
    },
    filterChipText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: 13,
        textTransform: "capitalize",
    },
    filterChipTextActive: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontWeight: "700",
    },
    allocateCard: {
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: 20,
        backgroundColor: COLORS.cardDark,
        padding: SPACING.md,
        marginBottom: SPACING.md,
    },
    allocateTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.subheading,
        marginBottom: SPACING.xs,
    },
    requestChip: {
        marginRight: SPACING.sm,
        minWidth: 84,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardBackground,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm - 1,
        justifyContent: "center",
        alignItems: "center",
    },
    requestChipActive: {
        borderColor: COLORS.accent,
        backgroundColor: COLORS.cardDark,
    },
    requestChipText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: 13,
    },
    requestChipTextActive: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontWeight: "700",
    },
    allocateMeta: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginTop: SPACING.xs,
    },
    allocateMetaWarn: {
        color: COLORS.warning,
    },
    allocateMetaGood: {
        color: COLORS.successBright,
    },
    selectionActionsRow: {
        flexDirection: "row",
        gap: SPACING.sm,
        marginTop: SPACING.sm,
        marginBottom: SPACING.sm,
    },
    selectionAction: {
        flex: 1,
        height: 40,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.accent,
        backgroundColor: "rgba(66, 165, 245, 0.14)",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: SPACING.md,
    },
    selectionActionPressed: {
        opacity: 0.85,
    },
    selectionActionText: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: 13,
        fontWeight: "700",
    },
    bulkStatusWrap: {
        marginBottom: SPACING.sm,
    },
    bulkStatusScroll: {
        flexGrow: 0,
    },
    bulkStatusRow: {
        flexDirection: "row",
        alignItems: "center",
    },
    bulkStatusButton: {
        minWidth: 84,
        marginRight: SPACING.sm,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm - 1,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardBackground,
        alignItems: "center",
        justifyContent: "center",
    },
    bulkStatusButtonPressed: {
        opacity: 0.85,
    },
    bulkStatusButtonDisabled: {
        opacity: 0.5,
    },
    bulkStatusButtonText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: 13,
        textTransform: "capitalize",
    },
    allocateButton: {
        marginTop: SPACING.sm,
        height: 46,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.accent,
    },
    allocateButtonDisabled: {
        opacity: 0.6,
    },
    allocateButtonText: {
        color: "#FFF",
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
    },
    emptyText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginTop: SPACING.md,
    },
    grid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        gap: SPACING.sm,
    },
    resourceCard: {
        width: "48%",
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: 20,
        backgroundColor: COLORS.cardDark,
        padding: SPACING.md,
    },
    resourceCardSelected: {
        borderColor: COLORS.accent,
        backgroundColor: "rgba(66, 165, 245, 0.1)",
    },
    resourceLabel: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
    },
    resourceMeta: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.xs + 1,
        marginTop: 2,
    },
    statusRow: {
        marginTop: SPACING.sm,
        flexDirection: "row",
        flexWrap: "wrap",
        gap: SPACING.xs,
    },
    statusAction: {
        minWidth: 68,
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.xs + 1,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        borderRadius: RADII.pill,
        backgroundColor: COLORS.cardBackground,
        justifyContent: "center",
        alignItems: "center",
    },
    statusActionActive: {
        borderColor: COLORS.accent,
        backgroundColor: COLORS.cardDark,
    },
    statusActionText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption - 1,
        textTransform: "capitalize",
    },
    statusActionTextActive: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontWeight: "700",
    },
});

