import { StyleSheet } from "react-native";
import { COLORS, CONTROL_SIZES, FONTS, RADII, SPACING, TEXT_SIZES } from "../../../src/theme";

export default StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    errorBox: {
        borderWidth: 1,
        borderColor: COLORS.error,
        borderRadius: RADII.sm,
        backgroundColor: "rgba(239, 83, 80, 0.1)",
        padding: SPACING.sm,
        marginBottom: SPACING.md,
    },
    errorText: {
        color: COLORS.error,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    noticeBox: {
        borderWidth: 1,
        borderColor: COLORS.warning,
        borderRadius: RADII.sm,
        backgroundColor: "rgba(255, 193, 7, 0.12)",
        padding: SPACING.sm,
        marginBottom: SPACING.md,
    },
    noticeText: {
        color: COLORS.warning,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    segmentTabs: {
        marginBottom: SPACING.md,
    },
    searchRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
        marginBottom: SPACING.md,
    },
    searchBar: {
        flex: 1,
        minHeight: 50,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: RADII.lg,
        backgroundColor: COLORS.cardDark,
        paddingHorizontal: SPACING.md,
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
    },
    searchInput: {
        flex: 1,
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.body,
        paddingVertical: 0,
    },
    filterButton: {
        width: 50,
        height: 50,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: RADII.lg,
        backgroundColor: COLORS.cardDark,
        alignItems: "center",
        justifyContent: "center",
    },
    filterButtonPressed: {
        opacity: 0.85,
        borderColor: COLORS.accent,
    },
    filterBadge: {
        position: "absolute",
        top: -5,
        right: -5,
        minWidth: 19,
        height: 19,
        borderRadius: 10,
        backgroundColor: COLORS.accent,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 4,
    },
    filterBadgeText: {
        color: "#FFF",
        fontFamily: FONTS.interSemiBold,
        fontSize: 10,
    },
    filterDrawer: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    filterDrawerContent: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    filtersDrawerBody: {
        paddingHorizontal: SPACING.lg,
        paddingBottom: SPACING.xl,
        gap: SPACING.lg,
    },
    filtersWrap: {
        gap: SPACING.md,
    },
    filterSectionLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.interSemiBold,
        fontSize: TEXT_SIZES.caption,
        letterSpacing: 0.8,
        textTransform: "uppercase",
    },
    filterChipWrap: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: SPACING.sm,
    },
    filterDrawerFooter: {
        flexDirection: "row",
        gap: SPACING.sm,
        backgroundColor: COLORS.backgroundDark,
    },
    filtersToggle: {
        height: 48,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: RADII.lg,
        backgroundColor: COLORS.cardDark,
        paddingHorizontal: SPACING.md,
        alignItems: "center",
        justifyContent: "space-between",
        flexDirection: "row",
        marginBottom: SPACING.md,
    },
    filtersToggleLeft: {
        flexDirection: "row",
        alignItems: "center",
    },
    filtersToggleText: {
        marginLeft: SPACING.xs,
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    fieldLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginBottom: SPACING.xs,
    },
    filterRow: {
        marginBottom: SPACING.md,
    },
    branchChip: {
        marginRight: SPACING.sm,
        minWidth: 84,
        backgroundColor: COLORS.cardDark,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm - 1,
        justifyContent: "center",
        alignItems: "center",
    },
    branchChipActive: {
        borderColor: COLORS.accent,
        backgroundColor: COLORS.cardDark,
    },
    branchChipText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: 13,
    },
    branchChipTextActive: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontWeight: "700",
    },
    loadingWrap: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
    },
    content: {
        paddingBottom: SPACING.xxl + 28,
    },
    summaryGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: CONTROL_SIZES.cardRadius + 2,
        backgroundColor: COLORS.cardDark,
        overflow: "hidden",
        marginBottom: SPACING.md,
    },
    summaryCard: {
        width: "50%",
        minHeight: 62,
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.md,
    },
    summaryCardLeft: {
        borderRightWidth: StyleSheet.hairlineWidth,
        borderRightColor: COLORS.cardBorder,
    },
    summaryCardTop: {
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: COLORS.cardBorder,
    },
    summaryIconWrap: {
        width: 32,
        height: 32,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
    },
    summaryTextWrap: {
        flex: 1,
        minWidth: 0,
    },
    summaryValue: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 19,
        lineHeight: 23,
        marginTop: 1,
    },
    summaryLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.interMedium,
        fontSize: 11,
        lineHeight: 14,
    },
    chipScroll: {
        marginBottom: SPACING.md,
    },
    filterChip: {
        minWidth: 84,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardDark,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm - 1,
        justifyContent: "center",
        alignItems: "center",
    },
    filterChipActive: {
        borderColor: COLORS.accent,
        backgroundColor: `${COLORS.accent}18`,
    },
    filterChipText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: 13,
        textTransform: "capitalize",
    },
    filterChipTextActive: {
        color: COLORS.accent,
        fontFamily: FONTS.body,
        fontWeight: "700",
    },
    allocateCard: {
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: CONTROL_SIZES.cardRadius + 2,
        backgroundColor: COLORS.cardDark,
        padding: SPACING.md,
        marginBottom: SPACING.md,
    },
    allocateTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.subheading,
        marginBottom: SPACING.xs,
    },
    requestChip: {
        marginRight: SPACING.sm,
        minWidth: 84,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardBackground,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm - 1,
        justifyContent: "center",
        alignItems: "center",
    },
    requestChipActive: {
        borderColor: COLORS.accent,
        backgroundColor: COLORS.cardDark,
    },
    requestChipText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: 13,
    },
    requestChipTextActive: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontWeight: "700",
    },
    allocateMeta: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
        marginTop: SPACING.xs,
    },
    allocateMetaWarn: {
        color: COLORS.warning,
    },
    allocateMetaGood: {
        color: COLORS.successBright,
    },
    selectionActionsRow: {
        flexDirection: "row",
        gap: SPACING.sm,
        marginTop: SPACING.sm,
        marginBottom: SPACING.sm,
    },
    selectionAction: {
        flex: 1,
        height: 40,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        backgroundColor: COLORS.cardDark,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: SPACING.md,
    },
    selectionActionActive: {
        borderColor: COLORS.accent,
        backgroundColor: "rgba(66, 165, 245, 0.2)",
    },
    selectionActionPressed: {
        opacity: 0.85,
    },
    selectionActionText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: 13,
        fontWeight: "700",
    },
    selectionActionTextActive: {
        color: COLORS.text,
    },
    selectionPanel: {
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: CONTROL_SIZES.cardRadius + 2,
        backgroundColor: COLORS.cardDark,
        padding: SPACING.md,
        marginBottom: SPACING.md,
        gap: SPACING.sm,
    },
    selectionPanelHeader: {
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: SPACING.sm,
    },
    selectionPanelTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
    },
    selectionPanelMeta: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.interRegular,
        fontSize: TEXT_SIZES.xs + 1,
        marginTop: 2,
    },
    selectionInlineActions: {
        flexDirection: "row",
        gap: SPACING.xs,
        flexShrink: 0,
    },
    selectionMiniAction: {
        minHeight: 32,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        backgroundColor: COLORS.backgroundDark,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: SPACING.sm,
    },
    selectionMiniActionActive: {
        borderColor: COLORS.accent,
        backgroundColor: `${COLORS.accent}18`,
    },
    selectionMiniActionText: {
        color: COLORS.muted,
        fontFamily: FONTS.interSemiBold,
        fontSize: TEXT_SIZES.xs + 1,
    },
    selectionMiniActionTextActive: {
        color: COLORS.accent,
    },
    selectionPanelSubLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.interSemiBold,
        fontSize: 11,
        textTransform: "uppercase",
        letterSpacing: 0.6,
    },
    bulkStatusWrap: {
        marginBottom: SPACING.sm,
    },
    bulkStatusScroll: {
        flexGrow: 0,
    },
    bulkStatusRow: {
        flexDirection: "row",
        alignItems: "center",
    },
    bulkStatusRowCompact: {
        flexDirection: "row",
        alignItems: "center",
        paddingTop: 2,
    },
    bulkStatusButton: {
        minWidth: 84,
        marginRight: SPACING.sm,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm - 1,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        backgroundColor: COLORS.cardDark,
        alignItems: "center",
        justifyContent: "center",
    },
    bulkStatusButtonPressed: {
        opacity: 0.85,
    },
    bulkStatusButtonDisabled: {
        opacity: 0.5,
    },
    bulkStatusButtonText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: 13,
        textTransform: "capitalize",
    },
    allocateButton: {
        marginTop: SPACING.sm,
        height: 46,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.accent,
    },
    allocateButtonDisabled: {
        opacity: 0.6,
    },
    allocateButtonText: {
        color: "#FFF",
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
    },
    emptyText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.interMedium,
        fontSize: TEXT_SIZES.caption,
        marginTop: SPACING.md,
    },
    sectionStack: {
        gap: SPACING.md,
    },
    accordionCard: {
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: 18,
        backgroundColor: COLORS.cardDark,
        overflow: "hidden",
    },
    accordionHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: SPACING.sm,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.md,
    },
    accordionHeaderTextWrap: {
        flex: 1,
    },
    accordionTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.subheading,
    },
    accordionMeta: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.interRegular,
        fontSize: TEXT_SIZES.caption,
        marginTop: 2,
    },
    accordionSchedule: {
        color: COLORS.accent,
        fontFamily: FONTS.interSemiBold,
        fontSize: TEXT_SIZES.xs + 1,
        marginTop: 4,
    },
    sectionBody: {
        borderTopWidth: 1,
        borderTopColor: COLORS.cardBorder,
        paddingHorizontal: SPACING.md,
        paddingBottom: SPACING.md,
    },
    roomStack: {
        marginTop: SPACING.xs,
    },
    roomCard: {
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.cardBorder,
    },
    roomHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: SPACING.sm,
        paddingVertical: SPACING.xs,
    },
    roomHeaderTextWrap: {
        flex: 1,
    },
    roomHeaderActions: {
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.xs,
    },
    roomTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
    },
    roomMeta: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.xs + 1,
        marginTop: 2,
    },
    roomSchedule: {
        color: COLORS.accent,
        fontFamily: FONTS.interSemiBold,
        fontSize: TEXT_SIZES.xs + 1,
        marginTop: 2,
    },
    roomSelectButton: {
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.xs + 1,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        backgroundColor: COLORS.cardDark,
    },
    roomSelectButtonActive: {
        borderColor: COLORS.accent,
        backgroundColor: "rgba(66, 165, 245, 0.2)",
    },
    roomSelectButtonText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.xs + 1,
        fontWeight: "700",
    },
    roomSelectButtonTextActive: {
        color: COLORS.text,
    },
    grid: {
        flexDirection: "column",
        gap: SPACING.sm,
        marginTop: SPACING.sm,
    },
    resourceCard: {
        width: "100%",
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: 14,
        backgroundColor: COLORS.backgroundDark,
        padding: SPACING.sm,
    },
    resourceCardSelected: {
        borderColor: COLORS.accent,
        backgroundColor: "rgba(66, 165, 245, 0.1)",
    },
    resourceLabel: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
    },
    resourceMeta: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.xs + 1,
        marginTop: 2,
    },
    statusRow: {
        marginTop: SPACING.sm,
        flexDirection: "row",
        flexWrap: "wrap",
        gap: SPACING.xs,
    },
    statusAction: {
        minWidth: 68,
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.xs + 1,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: RADII.pill,
        backgroundColor: COLORS.cardDark,
        justifyContent: "center",
        alignItems: "center",
    },
    statusActionActive: {
        borderColor: COLORS.accent,
        backgroundColor: `${COLORS.accent}18`,
    },
    statusActionText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption - 1,
        textTransform: "capitalize",
    },
    statusActionTextActive: {
        color: COLORS.accent,
        fontFamily: FONTS.interSemiBold,
    },
});

