export const KARACHI_AREAS = [
  'Bahadurabad',
  'Clifton Block 1',
  'Clifton Block 2',
  'Clifton Block 3',
  'Clifton Block 4',
  'Clifton Block 5',
  'Clifton Block 6',
  'DHA Phase 1',
  'DHA Phase 2',
  'DHA Phase 3',
  'DHA Phase 4',
  'DHA Phase 5',
  'DHA Phase 6',
  'DHA Phase 7',
  'DHA Phase 8',
  'Federal B Area Block 10',
  'Federal B Area Block 4',
  'Gulshan e Iqbal Block 1',
  'Gulshan e Iqbal Block 13 A',
  'Gulshan e Iqbal Block 13 B',
  'Gulshan e Iqbal Block 13 D',
  'Gulshan e Iqbal Block 2',
  'Gulshan e Iqbal Block 3',
  'Gulshan e Iqbal Block 4',
  'Gulshan e Iqbal Block 5',
  'Gulshan e Iqbal Block 6',
  'Gulshan e Iqbal Block 7',
  'Korangi',
  'Korangi Creek',
  'Landhi',
  'Liaquatabad',
  'Malir Cantt',
  'Model Colony',
  'Nazimabad',
  'North Karachi Sector 11 A',
  'North Karachi Sector 11 B',
  'North Karachi Sector 11 C',
  'North Nazimabad Block A',
  'North Nazimabad Block B',
  'North Nazimabad Block C',
  'PECHS Block 2',
  'PECHS Block 3',
  'PECHS Block 6',
  'Saddar',
  'Scheme 33',
  'Shahrah e Faisal',
  'Surjani Town',
  'Tariq Road',
  'Others Karachi',
] as const;

export type KarachiArea = (typeof KARACHI_AREAS)[number];
