import { StyleSheet } from 'react-native';
import { COLORS, FONTS, RADII, SHADOWS, SPACING, TEXT_SIZES } from '../../../src/theme';

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.backgroundDark,
  },
  screenContent: {
    flex: 1,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
  },
  headerWrap: {
    paddingTop: SPACING.lg,
  },
  content: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.lg,
    paddingBottom: SPACING.xl,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
  },
  infoBanner: {
    backgroundColor: COLORS.cardDark,
    borderRadius: RADII.lg,
    padding: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    marginBottom: SPACING.md,
    ...SHADOWS.cardSoft,
  },
  infoTitle: {
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: TEXT_SIZES.body,
    marginBottom: SPACING.xs,
  },
  infoSubtitle: {
    color: COLORS.muted,
    fontFamily: FONTS.body,
    fontSize: TEXT_SIZES.caption,
  },
  messageList: {
    flexGrow: 1,
  },
  contextWrapper: {
    marginBottom: SPACING.lg,
  },
  contextCard: {
    backgroundColor: COLORS.cardDark,
    borderRadius: RADII.lg,
    padding: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    ...SHADOWS.cardSoft,
  },
  contextTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SPACING.xs,
  },
  contextGame: {
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: TEXT_SIZES.body,
  },
  contextStatusPill: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADII.pill,
    backgroundColor: COLORS.accent + '20',
    borderWidth: 1,
    borderColor: COLORS.accent + '40',
  },
  contextStatusText: {
    color: COLORS.accent,
    fontFamily: FONTS.heading,
    fontSize: 11,
    textTransform: 'capitalize',
  },
  contextVenue: {
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: TEXT_SIZES.subheading,
    marginBottom: 4,
  },
  contextTime: {
    color: COLORS.muted,
    fontFamily: FONTS.body,
    fontSize: TEXT_SIZES.caption,
  },
  bubbleRow: {
    marginBottom: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'flex-end',
    width: '100%',
  },
  bubbleRowIncoming: {
    justifyContent: 'flex-start',
  },
  bubbleRowOutgoing: {
    justifyContent: 'flex-end',
  },
  bubbleContainer: {
    flexShrink: 1,
    maxWidth: '80%',
  },
  bubbleContainerIncoming: {
    alignItems: 'flex-start',
  },
  bubbleContainerOutgoing: {
    alignItems: 'flex-end',
  },
  bubbleTouchable: {
    maxWidth: '100%',
  },
  avatarWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.overlayLight,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: SPACING.sm,
    marginBottom: 2,
  },
  avatarWrapRight: {
    marginRight: 0,
    marginLeft: SPACING.sm,
  },
  avatarText: {
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: 12,
  },
  bubbleIncoming: {
    alignSelf: 'flex-start',
    backgroundColor: COLORS.cardDark,
    borderRadius: RADII.lg,
    borderTopLeftRadius: RADII.sm,
    paddingVertical: SPACING.sm + 2,
    paddingHorizontal: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    ...SHADOWS.cardSoft,
  },
  bubbleOutgoing: {
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(66,165,245,0.2)',
    borderRadius: RADII.lg,
    borderTopRightRadius: RADII.sm,
    paddingVertical: SPACING.sm + 2,
    paddingHorizontal: SPACING.md,
    borderWidth: 1,
    borderColor: 'rgba(66,165,245,0.45)',
    ...SHADOWS.cardSoft,
  },
  bubbleSender: {
    color: COLORS.textSecondary,
    fontSize: 11,
    fontFamily: FONTS.body,
    marginBottom: 2,
  },
  bubbleText: {
    color: COLORS.text,
    fontSize: TEXT_SIZES.body,
    fontFamily: FONTS.body,
    lineHeight: 20,
    paddingLeft: 0,
  },
  bubbleTime: {
    color: COLORS.muted,
    fontSize: 10,
    fontFamily: FONTS.body,
    marginTop: 6,
    alignSelf: 'flex-end',
  },
  deletedText: {
    color: COLORS.muted,
    fontSize: TEXT_SIZES.body,
    fontFamily: FONTS.body,
    fontStyle: 'italic',
  },
  replyChip: {
    backgroundColor: COLORS.overlayLight,
    borderRadius: RADII.md,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 6,
    marginBottom: SPACING.xs,
  },
  replyLabel: {
    color: COLORS.textSecondary,
    fontSize: 10,
    fontFamily: FONTS.body,
    marginBottom: 2,
  },
  replySnippet: {
    color: COLORS.text,
    fontSize: 12,
    fontFamily: FONTS.body,
  },
  bubbleStatus: {
    color: COLORS.accent,
    fontSize: 10,
    fontFamily: FONTS.body,
    marginTop: 6,
    alignSelf: 'flex-end',
  },
  seenByText: {
    color: COLORS.textSecondary,
    fontSize: 10,
    fontFamily: FONTS.body,
    marginTop: 4,
    alignSelf: 'flex-end',
  },
  inputBar: {
    paddingHorizontal: 0,
    paddingTop: SPACING.sm,
    backgroundColor: COLORS.backgroundDark,
    borderTopWidth: 1,
    borderTopColor: COLORS.cardBorder,
    width: '100%',
  },
  inputInner: {
    paddingHorizontal: SPACING.md,
    width: '100%',
  },
  replyBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    marginBottom: SPACING.xs,
    borderRadius: RADII.md,
    backgroundColor: COLORS.cardDark,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  replyContent: {
    flex: 1,
  },
  replyTitle: {
    color: COLORS.textSecondary,
    fontSize: 10,
    fontFamily: FONTS.body,
    marginBottom: 2,
  },
  replyText: {
    color: COLORS.text,
    fontSize: 12,
    fontFamily: FONTS.body,
  },
  replyClose: {
    padding: 6,
  },
  quickChips: {
    gap: SPACING.sm,
    paddingBottom: SPACING.sm,
    paddingHorizontal: 2,
  },
  quickChip: {
    paddingHorizontal: SPACING.md,
    paddingVertical: 6,
    borderRadius: RADII.pill,
    backgroundColor: COLORS.overlayLight,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  quickChipText: {
    color: COLORS.text,
    fontSize: 12,
    fontFamily: FONTS.body,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    width: '100%',
  },
  input: {
    flex: 1,
    backgroundColor: COLORS.cardDark,
    borderRadius: RADII.lg,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    color: COLORS.text,
    fontFamily: FONTS.body,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    minHeight: 44,
  },
  sendButton: {
    backgroundColor: COLORS.accent,
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    ...SHADOWS.accentSoft,
  },
  sendButtonPressed: {
    opacity: 0.9,
  },
  sendButtonDisabled: {
    opacity: 0.65,
  },
});
