import type { ComponentType } from "react";
import type { SvgProps } from "react-native-svg";
import {
  Armchair,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  BadgeCheck,
  BadgeDollarSign,
  Ban,
  Banknote,
  BarChart3,
  Bell,
  BellRing,
  Bolt,
  Boxes,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CircleUser,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  Compass,
  Construction,
  Copy,
  CreditCard,
  Crosshair,
  Crown,
  DatabaseZap,
  Download,
  Eye,
  EyeOff,
  FileClock,
  FileText,
  Flag,
  Gavel,
  Gamepad2,
  Gauge,
  Grid2X2,
  History,
  Home,
  Hourglass,
  Image as ImageIcon,
  Inbox,
  Info,
  KeyRound,
  LayoutDashboard,
  LifeBuoy,
  Link2,
  ListChecks,
  Lock,
  LockKeyhole,
  LogOut,
  Mail,
  MailCheck,
  Map,
  MapPin,
  MapPinned,
  Menu,
  MessageCircle,
  Mic,
  Monitor,
  MonitorCog,
  MoreHorizontal,
  MoreVertical,
  Package,
  Paperclip,
  Pause,
  Pencil,
  Phone,
  Pin,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  ReceiptText,
  RefreshCcw,
  Reply,
  Search,
  SearchX,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  SmilePlus,
  Sparkles,
  Star,
  Store,
  Swords,
  Ticket,
  TimerOff,
  Trash2,
  TriangleAlert,
  Trophy,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  UserRound,
  UserRoundMinus,
  UsersRound,
  Wallet,
  WalletCards,
  Wrench,
  X,
  XCircle,
  Zap,
} from "lucide-react-native";

type IconComponent = ComponentType<SvgProps & { size?: number | string; strokeWidth?: number }>;

export const AppIcons = {
  back: ArrowLeft,
  next: ChevronRight,
  menu: Menu,

  home: Home,
  discover: Compass,
  profile: CircleUser,
  notifications: Bell,
  search: Search,
  filters: SlidersHorizontal,

  matchroom: Gamepad2,
  players: UsersRound,
  teams: Shield,
  zone: MapPin,

  wallet: Wallet,
  schedule: CalendarClock,
  chat: MessageCircle,
  settings: Settings,

  dashboard: LayoutDashboard,
  branch: Building2,
  bookings: CalendarCheck,
  resources: MonitorCog,
  resourcesAlt: Boxes,
  pricing: Banknote,
  pricingAlt: BadgeDollarSign,
  support: LifeBuoy,
  insights: BarChart3,
  audit: ShieldCheck,
  reports: Flag,

  success: CheckCircle2,
  error: XCircle,
  warning: TriangleAlert,
  create: PlusCircle,
  invite: UserPlus,
  removeUser: UserMinus,
  delete: Trash2,
  edit: Pencil,
  share: Share2,
  start: PlayCircle,

  send: Send,
  attach: Paperclip,
  voice: Mic,
  image: ImageIcon,
  file: FileText,
  reply: Reply,
  pin: Pin,
  reaction: SmilePlus,
  play: Play,
  pause: Pause,

  password: LockKeyhole,
  email: Mail,
  phone: Phone,
  reset: KeyRound,
  verified: BadgeCheck,
  mailVerified: MailCheck,
  username: AtSign,
  city: MapPin,
  areas: MapPinned,
  age: Calendar,

  price: Banknote,
  skill: Gauge,
  challenge: Swords,
  shooter: Crosshair,
  captain: Crown,
  logout: LogOut,

  pending: Hourglass,
  clock: Clock3,
  expired: TimerOff,
  cancelled: Ban,
  locked: Lock,
  status: CircleDot,
  checklist: ListChecks,

  business: Building2,
  review: ClipboardCheck,
  role: UserCog,
  platform: Link2,
  activeGame: CircleCheck,
  inactiveGame: CircleDashed,

  migration: Wrench,
  databaseMigration: DatabaseZap,
  auditTrail: FileClock,

  payment: CreditCard,
  paymentWallet: WalletCards,
  counterOffer: RefreshCcw,
  ticket: Ticket,
  seat: Armchair,

  monitor: Monitor,

  // Existing MaterialIcon name compatibility aliases.
  "access-time": Clock3,
  "account-balance-wallet": Wallet,
  add: Plus,
  "add-circle": PlusCircle,
  "add-circle-outline": PlusCircle,
  "alternate-email": AtSign,
  "arrow-back": ArrowLeft,
  "arrow-drop-down": ChevronDown,
  "arrow-forward": ArrowRight,
  "attach-money": Banknote,
  "bar-chart": BarChart3,
  block: Ban,
  bolt: Zap,
  "broadcast-on-personal": BellRing,
  cake: Calendar,
  "calendar-month": Calendar,
  "calendar-today": Calendar,
  cancel: XCircle,
  "chat-bubble-outline": MessageCircle,
  check: Check,
  "check-circle": CheckCircle2,
  "chevron-right": ChevronRight,
  close: X,
  construction: Construction,
  "delete-sweep": Trash2,
  "delete-outline": Trash2,
  "emoji-events": Trophy,
  "error-outline": CircleAlert,
  event: CalendarCheck,
  "event-seat": Armchair,
  "expand-less": ChevronDown,
  "expand-more": ChevronDown,
  "exit-to-app": LogOut,
  "file-download": Download,
  forum: MessageCircle,
  gavel: Gavel,
  group: UsersRound,
  "group-off": UserRoundMinus,
  groups: UsersRound,
  "groups-2": UsersRound,
  "grid-view": Grid2X2,
  "hourglass-empty": Hourglass,
  "hourglass-top": Hourglass,
  inbox: Inbox,
  info: Info,
  "info-outline": Info,
  "insert-drive-file": FileText,
  inventory: Package,
  "inventory-2": Boxes,
  "keyboard-arrow-down": ArrowDown,
  "keyboard-arrow-up": ArrowUp,
  launch: ArrowRight,
  link: Link2,
  "content-copy": Copy,
  "location-on": MapPin,
  lock: Lock,
  "lock-outline": LockKeyhole,
  "mark-email-unread": MailCheck,
  map: Map,
  mood: SmilePlus,
  "more-horiz": MoreHorizontal,
  "more-vert": MoreVertical,
  "notifications-active": BellRing,
  "notifications-none": Bell,
  payments: WalletCards,
  people: UsersRound,
  person: UserRound,
  "person-add": UserPlus,
  "person-add-alt": UserPlus,
  "person-add-alt-1": UserPlus,
  "person-add-disabled": UserMinus,
  "person-off": UserMinus,
  "person-outline": UserRound,
  call: Phone,
  "phone-android": Phone,
  photo: ImageIcon,
  "photo-camera": ImageIcon,
  place: MapPin,
  policy: ShieldCheck,
  "pending-actions": ClipboardList,
  "push-pin": Pin,
  "radio-button-unchecked": CircleDashed,
  "receipt-long": ReceiptText,
  refresh: RefreshCcw,
  "report-gmailerrorred": TriangleAlert,
  "report-problem": Flag,
  "search-off": SearchX,
  security: ShieldCheck,
  sensors: Gauge,
  "sports-cricket": Trophy,
  "sports-esports": Gamepad2,
  sports: Trophy,
  "sports-kabaddi": Swords,
  "sports-mma": Swords,
  "sports-soccer": Gamepad2,
  "sports-tennis": Swords,
  "star-border": Star,
  "star-half": Star,
  star: Star,
  stars: Sparkles,
  store: Store,
  storefront: Building2,
  "store-mall-directory": Building2,
  "swap-horiz": RefreshCcw,
  sync: RefreshCcw,
  "tips-and-updates": LifeBuoy,
  "trending-up": BarChart3,
  tune: SlidersHorizontal,
  "verified-user": ShieldCheck,
  visibility: Eye,
  "visibility-off": EyeOff,
  "videogame-asset": Gamepad2,
  "military-tech": Trophy,
} as const satisfies Record<string, IconComponent>;

export type AppIconName = keyof typeof AppIcons;
