import { StyleSheet } from "react-native";
import { COLORS, FONTS, RADII, SPACING } from "../../src/theme";

export default StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    tabs: {
        marginBottom: SPACING.md,
    },
    content: {
        paddingBottom: SPACING.xxl,
    },
    balanceCard: {
        backgroundColor: COLORS.cardDark,
        borderRadius: RADII.lg,
        borderWidth: 1,
        borderColor: COLORS.accent + "55",
        padding: SPACING.lg,
        marginBottom: SPACING.md,
    },
    balanceLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: 12,
        textTransform: "uppercase",
        marginBottom: 4,
    },
    balanceValue: {
        color: COLORS.accent,
        fontFamily: FONTS.heading,
        fontSize: 30,
    },
    addFundsCard: {
        backgroundColor: COLORS.cardDark,
        borderRadius: RADII.lg,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        padding: SPACING.md,
        marginBottom: SPACING.md,
    },
    addFundsTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 15,
        marginBottom: 2,
    },
    addFundsSubtext: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: 12,
        marginBottom: SPACING.sm,
    },
    quickAmountRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        marginBottom: SPACING.sm,
    },
    quickAmountBtn: {
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: RADII.pill,
        paddingHorizontal: 10,
        paddingVertical: 6,
        marginRight: SPACING.xs,
        marginBottom: SPACING.xs,
        backgroundColor: COLORS.overlayLight,
    },
    quickAmountBtnActive: {
        borderColor: COLORS.accent,
        backgroundColor: COLORS.accent + "16",
    },
    quickAmountBtnPressed: {
        opacity: 0.85,
    },
    quickAmountText: {
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: 12,
        fontWeight: "700",
    },
    addFundsRow: {
        flexDirection: "row",
        alignItems: "center",
    },
    amountInput: {
        flex: 1,
        backgroundColor: COLORS.overlayLight,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: RADII.md,
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: 14,
        paddingHorizontal: 10,
        paddingVertical: 10,
        marginRight: SPACING.sm,
    },
    addFundsBtn: {
        minWidth: 108,
        backgroundColor: COLORS.accent,
        borderRadius: RADII.md,
        paddingHorizontal: 12,
        paddingVertical: 10,
        alignItems: "center",
        justifyContent: "center",
    },
    addFundsBtnDisabled: {
        opacity: 0.6,
    },
    addFundsBtnPressed: {
        opacity: 0.85,
    },
    addFundsBtnText: {
        color: "#FFF",
        fontFamily: FONTS.heading,
        fontSize: 12,
        fontWeight: "700",
        textTransform: "uppercase",
    },
    summaryCard: {
        backgroundColor: COLORS.cardDark,
        borderRadius: RADII.lg,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        padding: SPACING.lg,
        marginBottom: SPACING.md,
    },
    summaryTitle: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: 12,
        textTransform: "uppercase",
        marginBottom: 4,
    },
    summaryValue: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 30,
    },
    summarySubText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: 12,
        marginTop: 4,
    },
    statsRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: SPACING.md,
    },
    statCard: {
        flex: 1,
        backgroundColor: COLORS.cardDark,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        padding: SPACING.md,
        marginRight: SPACING.sm,
    },
    statCardLast: {
        marginRight: 0,
    },
    statLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: 11,
        marginBottom: 4,
    },
    statValue: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 18,
    },
    transactionCard: {
        backgroundColor: COLORS.cardDark,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        padding: SPACING.md,
        marginBottom: SPACING.sm,
    },
    transactionTopRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 6,
    },
    transactionTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 14,
        flex: 1,
        marginRight: SPACING.sm,
    },
    transactionAmount: {
        color: COLORS.successBright,
        fontFamily: FONTS.heading,
        fontSize: 13,
    },
    transactionMeta: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: 12,
        marginBottom: 2,
    },
    statusPill: {
        alignSelf: "flex-start",
        marginTop: 6,
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: RADII.pill,
        borderWidth: 1,
    },
    statusText: {
        fontFamily: FONTS.body,
        fontSize: 10,
        textTransform: "uppercase",
        fontWeight: "700",
    },
    emptyCard: {
        backgroundColor: COLORS.cardDark,
        borderRadius: RADII.lg,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        padding: SPACING.lg,
        alignItems: "center",
    },
    emptyTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 16,
        marginBottom: 6,
    },
    emptyText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: 13,
        textAlign: "center",
    },
});
