import { StyleSheet } from "react-native";
import { COLORS, CONTROL_SIZES, FONTS, RADII, SPACING, TEXT_SIZES } from "../../../src/theme";

export default StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    screenContent: {
        flex: 1,
        paddingTop: 10,
        paddingBottom: 0,
    },
    zoneAdmincontainer: {
        paddingBottom: SPACING.lg,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: COLORS.backgroundDark,
    },
    noZoneContainer: {
        flex: 1,
        justifyContent: "center",
        paddingBottom: SPACING.xl,
    },
    noZoneCard: {
        paddingVertical: SPACING.xxl,
    },
    rejectedReasonWrap: {
        marginTop: SPACING.md,
        alignItems: "center",
    },
    rejectReason: {
        color: COLORS.error,
        fontFamily: FONTS.interRegular,
        fontSize: TEXT_SIZES.caption,
        textAlign: "center",
    },
    iconButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        backgroundColor: COLORS.cardDark,
    },
    iconButtonPressed: {
        opacity: 0.85,
    },
    headerActionsRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
    },
    notificationBadge: {
        position: "absolute",
        top: -4,
        right: -6,
        minWidth: 20,
        height: 20,
        paddingHorizontal: 4,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.error,
        borderWidth: 2,
        borderColor: COLORS.backgroundDark,
    },
    notificationBadgeText: {
        color: "#fff",
        fontFamily: FONTS.heading,
        fontSize: 11,
    },
    heroCard: {
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: CONTROL_SIZES.cardRadius + 2,
        backgroundColor: COLORS.cardDark,
        padding: SPACING.lg,
        marginBottom: SPACING.md,
    },
    heroRow: {
        flexDirection: "row",
        alignItems: "center",
    },
    avatarIconWrap: {
        width: 58,
        height: 58,
        borderRadius: 18,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: `${COLORS.accent}14`,
        borderWidth: 1,
        borderColor: `${COLORS.accent}55`,
    },
    heroTextWrap: {
        marginLeft: SPACING.md,
        flex: 1,
    },
    heroEyebrow: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.interMedium,
        fontSize: 11,
        textTransform: "uppercase",
        letterSpacing: 1,
    },
    heroTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 22,
        marginTop: 2,
    },
    heroSubtitle: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.interRegular,
        fontSize: TEXT_SIZES.caption,
        marginTop: 2,
    },
    tagsRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        marginTop: SPACING.md,
        gap: SPACING.sm,
    },
    snapshotPanel: {
        width: "100%",
        flexDirection: "row",
        flexWrap: "wrap",
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderRadius: CONTROL_SIZES.cardRadius + 2,
        backgroundColor: COLORS.cardDark,
        overflow: "hidden",
        marginBottom: SPACING.md,
    },
    snapshotItem: {
        width: "50%",
        minHeight: 62,
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.md,
    },
    snapshotItemLeft: {
        borderRightWidth: StyleSheet.hairlineWidth,
        borderRightColor: COLORS.cardBorder,
    },
    snapshotItemTop: {
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: COLORS.cardBorder,
    },
    snapshotIconWrap: {
        width: 32,
        height: 32,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
    },
    snapshotTextWrap: {
        flex: 1,
        minWidth: 0,
    },
    snapshotLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.interMedium,
        fontSize: 11,
        lineHeight: 14,
    },
    snapshotValue: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 19,
        lineHeight: 23,
        marginTop: 1,
    },
    section: {
        marginTop: SPACING.lg,
    },
    matchroomsWrap: {
        gap: SPACING.sm,
    },
    moduleGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        alignItems: "stretch",
    },
    moduleCard: {
        width: "48.5%",
        minHeight: 122,
        marginBottom: SPACING.md,
    },
});
