import { StyleSheet } from "react-native";

import { COLORS, FONTS, RADII, SHADOWS, SPACING, TEXT_SIZES } from "../../../src/theme";

export default StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    scrollContent: {
        paddingTop: 0,
    },
    loadingContainer: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.backgroundDark,
    },
    headerIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        backgroundColor: COLORS.cardDark,
    },
    profileCard: {
        marginTop: 0,
        alignItems: "center",
        ...SHADOWS.cardSoft,
    },
    avatar: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: COLORS.accent,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: SPACING.md,
    },
    avatarText: {
        color: COLORS.text,
        fontSize: TEXT_SIZES.xxl,
        fontFamily: FONTS.heading,
        fontWeight: "700",
    },
    profileName: {
        maxWidth: "100%",
        color: COLORS.text,
        fontSize: TEXT_SIZES.subheading,
        fontFamily: FONTS.heading,
        fontWeight: "600",
        marginBottom: SPACING.xs,
    },
    profileUsername: {
        maxWidth: "100%",
        color: COLORS.muted,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.body,
        marginBottom: SPACING.xs,
    },
    profileEmail: {
        maxWidth: "100%",
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.caption,
        fontFamily: FONTS.body,
    },
    profileMeta: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        flexWrap: "wrap",
        marginTop: SPACING.sm,
        gap: SPACING.md,
    },
    profileMetaItem: {
        maxWidth: "100%",
        flexDirection: "row",
        alignItems: "center",
    },
    profileMetaText: {
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.caption,
        marginLeft: SPACING.xs,
    },
    profileStatusRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "center",
        gap: SPACING.sm,
        marginTop: SPACING.md,
    },
    section: {
        marginTop: SPACING.xl,
    },
    branchesScrollContainer: {
        paddingBottom: SPACING.sm,
    },
    branchCard: {
        width: 282,
        height: 108,
        marginRight: SPACING.md,
    },
    branchCardInner: {
        height: 108,
        flexDirection: "row",
        alignItems: "center",
        padding: SPACING.md,
        overflow: "hidden",
    },
    branchIcon: {
        width: 42,
        height: 42,
        borderRadius: RADII.sm,
        backgroundColor: COLORS.overlayMedium,
        alignItems: "center",
        justifyContent: "center",
        marginRight: SPACING.md,
    },
    branchInfo: {
        flex: 1,
        minWidth: 0,
        marginRight: SPACING.sm,
    },
    branchTitleRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.xs,
        minHeight: 22,
    },
    branchName: {
        flex: 1,
        minWidth: 0,
        color: COLORS.text,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.heading,
        fontWeight: "600",
    },
    primaryBadge: {
        borderWidth: 1,
        borderColor: "rgba(66,165,245,0.35)",
        backgroundColor: "rgba(66,165,245,0.12)",
        borderRadius: RADII.pill,
        paddingHorizontal: 6,
        paddingVertical: 2,
    },
    primaryText: {
        color: COLORS.accent,
        fontSize: 9,
        fontFamily: FONTS.interSemiBold,
        textTransform: "uppercase",
    },
    branchDetailRow: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: SPACING.xs,
        gap: 3,
    },
    branchLocation: {
        flex: 1,
        minWidth: 0,
        color: COLORS.muted,
        fontSize: TEXT_SIZES.caption,
        fontFamily: FONTS.body,
    },
    branchInventory: {
        color: COLORS.accent,
        fontSize: TEXT_SIZES.xs + 1,
        fontFamily: FONTS.body,
        marginTop: 2,
    },
    branchAddress: {
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.xs,
        fontFamily: FONTS.body,
        marginTop: 1,
    },
    emptyBranchCard: {
        width: 292,
        height: 92,
        opacity: 0.75,
    },
    emptyBranchCardInner: {
        height: "100%",
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: COLORS.cardBackground,
        borderStyle: "dashed",
    },
    branchIconInactive: {
        width: 44,
        height: 44,
        borderRadius: RADII.md,
        backgroundColor: COLORS.overlayLight,
        alignItems: "center",
        justifyContent: "center",
        marginRight: SPACING.md,
    },
    emptyBranchTitle: {
        color: COLORS.muted,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.heading,
        fontWeight: "600",
    },
    emptyBranchText: {
        color: COLORS.accent,
        fontSize: TEXT_SIZES.caption,
        fontFamily: FONTS.body,
        marginTop: 2,
    },
    emptyWrap: {
        flex: 1,
        justifyContent: "center",
    },
});
