import { StyleSheet } from "react-native";

import { COLORS, FONTS, RADII, SHADOWS, SPACING, TEXT_SIZES } from "../../../src/theme";

export default StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    scrollContent: {
        paddingTop: 10,
    },
    loadingContainer: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.backgroundDark,
    },
    headerIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        backgroundColor: COLORS.cardDark,
    },
    profileCard: {
        marginTop: 0,
        alignItems: "center",
        ...SHADOWS.cardSoft,
    },
    avatar: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: COLORS.accent,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: SPACING.md,
    },
    avatarText: {
        color: COLORS.text,
        fontSize: TEXT_SIZES.xxl,
        fontFamily: FONTS.heading,
        fontWeight: "700",
    },
    profileName: {
        maxWidth: "100%",
        color: COLORS.text,
        fontSize: TEXT_SIZES.subheading,
        fontFamily: FONTS.heading,
        fontWeight: "600",
        marginBottom: SPACING.xs,
    },
    profileUsername: {
        maxWidth: "100%",
        color: COLORS.muted,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.body,
        marginBottom: SPACING.xs,
    },
    profileEmail: {
        maxWidth: "100%",
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.caption,
        fontFamily: FONTS.body,
    },
    profileMeta: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        flexWrap: "wrap",
        marginTop: SPACING.sm,
        gap: SPACING.md,
    },
    profileMetaItem: {
        maxWidth: "100%",
        flexDirection: "row",
        alignItems: "center",
    },
    profileMetaText: {
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.caption,
        marginLeft: SPACING.xs,
    },
    profileStatusRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "center",
        gap: SPACING.sm,
        marginTop: SPACING.md,
    },
    section: {
        marginTop: SPACING.xl,
    },
    branchesScrollContainer: {
        paddingBottom: SPACING.sm,
    },
    branchCard: {
        width: 282,
        height: 108,
        marginRight: SPACING.md,
    },
    branchCardInner: {
        height: 108,
        flexDirection: "row",
        alignItems: "center",
        padding: SPACING.md,
        overflow: "hidden",
    },
    branchIcon: {
        width: 42,
        height: 42,
        borderRadius: RADII.sm,
        backgroundColor: COLORS.overlayMedium,
        alignItems: "center",
        justifyContent: "center",
        marginRight: SPACING.md,
    },
    branchInfo: {
        flex: 1,
        minWidth: 0,
        marginRight: SPACING.sm,
    },
    branchTitleRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.xs,
        minHeight: 22,
    },
    branchName: {
        flex: 1,
        minWidth: 0,
        color: COLORS.text,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.heading,
        fontWeight: "600",
    },
    primaryBadge: {
        borderWidth: 1,
        borderColor: "rgba(66,165,245,0.35)",
        backgroundColor: "rgba(66,165,245,0.12)",
        borderRadius: RADII.pill,
        paddingHorizontal: 6,
        paddingVertical: 2,
    },
    primaryText: {
        color: COLORS.accent,
        fontSize: 9,
        fontFamily: FONTS.interSemiBold,
        textTransform: "uppercase",
    },
    branchDetailRow: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: SPACING.xs,
        gap: 3,
    },
    branchLocation: {
        flex: 1,
        minWidth: 0,
        color: COLORS.muted,
        fontSize: TEXT_SIZES.caption,
        fontFamily: FONTS.body,
    },
    branchInventory: {
        color: COLORS.accent,
        fontSize: TEXT_SIZES.xs + 1,
        fontFamily: FONTS.body,
        marginTop: 2,
    },
    branchAddress: {
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.xs,
        fontFamily: FONTS.body,
        marginTop: 1,
    },
    emptyBranchCard: {
        width: 292,
        height: 92,
        opacity: 0.75,
    },
    emptyBranchCardInner: {
        height: "100%",
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: COLORS.cardBackground,
        borderStyle: "dashed",
    },
    branchIconInactive: {
        width: 44,
        height: 44,
        borderRadius: RADII.md,
        backgroundColor: COLORS.overlayLight,
        alignItems: "center",
        justifyContent: "center",
        marginRight: SPACING.md,
    },
    emptyBranchTitle: {
        color: COLORS.muted,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.heading,
        fontWeight: "600",
    },
    emptyBranchText: {
        color: COLORS.accent,
        fontSize: TEXT_SIZES.caption,
        fontFamily: FONTS.body,
        marginTop: 2,
    },
    emptyWrap: {
        flex: 1,
        justifyContent: "center",
    },
    branchActionsRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-start",
        marginBottom: SPACING.md,
    },
    withdrawInlineButton: {
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.xs,
        minHeight: 40,
        borderWidth: 1,
        borderColor: "rgba(66,165,245,0.45)",
        backgroundColor: "rgba(66,165,245,0.10)",
        borderRadius: RADII.pill,
        paddingHorizontal: SPACING.md,
    },
    withdrawInlineText: {
        color: COLORS.accent,
        fontFamily: FONTS.interSemiBold,
        fontSize: TEXT_SIZES.caption,
    },
    withdrawDialog: {
        backgroundColor: COLORS.cardDark,
    },
    withdrawBody: {
        gap: SPACING.md,
    },
    withdrawLabel: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.interSemiBold,
        fontSize: TEXT_SIZES.caption,
        textTransform: "uppercase",
        letterSpacing: 0.7,
    },
    withdrawBranchWrap: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: SPACING.sm,
    },
    withdrawBranchChip: {
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        backgroundColor: COLORS.cardBackground,
        borderRadius: RADII.pill,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm,
    },
    withdrawBranchChipActive: {
        borderColor: COLORS.accent,
        backgroundColor: `${COLORS.accent}14`,
    },
    withdrawBranchChipText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    withdrawBranchChipTextActive: {
        color: COLORS.accent,
        fontFamily: FONTS.interSemiBold,
    },
    withdrawInputBox: {
        minHeight: 52,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.inputBackground,
        borderRadius: RADII.lg,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: SPACING.md,
        gap: SPACING.sm,
    },
    withdrawCurrency: {
        color: COLORS.accent,
        fontFamily: FONTS.interSemiBold,
        fontSize: TEXT_SIZES.caption,
    },
    withdrawInput: {
        flex: 1,
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.input,
        paddingVertical: 0,
    },
    logoutButton: {
        marginTop: SPACING.lg,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: SPACING.sm,
    },
    logoutButtonText: {
        color: COLORS.error,
        fontFamily: FONTS.interSemiBold,
        fontSize: TEXT_SIZES.body,
    },
    withdrawWarning: {
        color: COLORS.error,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    withdrawFooter: {
        flexDirection: "row",
        gap: SPACING.sm,
    },
    withdrawAction: {
        flex: 1,
        minHeight: 48,
        borderRadius: RADII.lg,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
    },
    withdrawCancelAction: {
        borderColor: COLORS.cardBorder,
        backgroundColor: COLORS.cardBackground,
    },
    withdrawSubmitAction: {
        borderColor: COLORS.accent,
        backgroundColor: COLORS.accent,
    },
    withdrawSubmitDisabled: {
        opacity: 0.45,
    },
    withdrawCancelText: {
        color: COLORS.text,
        fontFamily: FONTS.interSemiBold,
        fontSize: TEXT_SIZES.caption,
    },
    withdrawSubmitText: {
        color: "#FFF",
        fontFamily: FONTS.interSemiBold,
        fontSize: TEXT_SIZES.caption,
    },
});
