import { StyleSheet } from 'react-native';
import { COLORS, FONTS, RADII, SHADOWS, SPACING } from '../../../src/theme';

export default StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    screenContent: {
        paddingTop: SPACING.sm,
        paddingBottom: 0,
    },
    container: {
        paddingBottom: SPACING.md,
    },

    // 🔥 TOP SECTION: Personalized Header
    header: {
        paddingBottom: SPACING.lg,
        backgroundColor: COLORS.backgroundDark,
    },
    profileCard: {
        width: '100%',
        backgroundColor: COLORS.cardDark,
        borderRadius: RADII.xl,
        borderWidth: 1,
        borderColor: COLORS.accent + '55',
        padding: SPACING.lg,
        ...SHADOWS.accentSoft,
    },
    profileTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: SPACING.md,
    },
    avatarContainer: {
        position: 'relative',
        marginRight: SPACING.md,
    },
    avatar: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: '#2A2A2A',
        borderWidth: 2,
        borderColor: COLORS.accent,
    },
    onlineIndicator: {
        position: 'absolute',
        bottom: 2,
        right: 2,
        width: 14,
        height: 14,
        borderRadius: 7,
        backgroundColor: COLORS.successBright,
        borderWidth: 2,
        borderColor: COLORS.backgroundDark,
    },
    welcomeText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: 10,
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 2,
    },
    username: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 20,
        letterSpacing: 0.5,
    },
    notificationBell: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: COLORS.cardDark,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
    },
    notificationBadge: {
        position: 'absolute',
        top: -4,
        right: -6,
        backgroundColor: COLORS.error,
        borderRadius: 10,
        minWidth: 20,
        height: 20,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 4,
        borderWidth: 2,
        borderColor: COLORS.background,
    },
    notificationBadgeText: {
        color: '#FFF',
        fontSize: 11,
        fontWeight: '700',
    },
    menuButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: COLORS.cardDark,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
    },
    notificationDot: {
        position: 'absolute',
        top: 8,
        right: 10,
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: COLORS.error,
        borderWidth: 1,
        borderColor: COLORS.cardDark,
    },
    tagsRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    tag: {
        backgroundColor: 'rgba(255,255,255,0.05)',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 100,
        marginRight: 8,
        marginBottom: 6,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
    tagText: {
        color: COLORS.textSecondary,
        fontSize: 10,
        fontFamily: FONTS.body,
        fontWeight: '600',
    },

    // 📍 SECTION 1: Quick Actions
    section: {
        marginTop: SPACING.xl,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: SPACING.md,
    },
    sectionTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 18,
        letterSpacing: 0.5,
        marginBottom: SPACING.md,
    },
    seeAllText: {
        color: COLORS.accent,
        fontSize: 12,
        fontFamily: FONTS.body,
        fontWeight: '600',
    },

    quickActionsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    quickActionBtn: {
        width: '48%',
        minHeight: 120,
        backgroundColor: COLORS.cardDark,
        paddingVertical: SPACING.lg,
        paddingHorizontal: SPACING.md,
        borderRadius: 20,
        marginBottom: SPACING.md,
        flexDirection: 'column',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        borderWidth: 1,
        elevation: 4,
    },
    quickActionIconContainer: {
        width: 48,
        height: 48,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
    },
    quickActionText: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 14,
        fontWeight: '600',
    },

    // 🔔 SECTION 2: Alerts & Notifications (Catchy Redesign)
    notificationCard: {
        backgroundColor: '#1A1A1A',
        padding: SPACING.md,
        borderRadius: 16,
        marginBottom: SPACING.sm,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.05)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    notificationIconBox: {
        width: 40,
        height: 40,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
    notificationContent: {
        flex: 1,
    },
    notificationText: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 13,
        marginBottom: 4,
        lineHeight: 18,
    },
    notificationTime: {
        color: COLORS.textSecondary,
        fontSize: 11,
        fontWeight: '600',
    },

    // 🔥 SECTION 3: Nearby Matchrooms (Refined Layout)
    nearbyCard: {
        backgroundColor: COLORS.cardDark,
        borderRadius: 20,
        padding: SPACING.md,
        marginBottom: SPACING.md,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
    },
    nearbyCardHeader: {
        marginBottom: 8,
    },
    nearbyGame: {
        color: COLORS.accent,
        fontSize: 11,
        fontFamily: FONTS.heading,
        fontWeight: '700',
        textTransform: 'uppercase',
        marginBottom: 10,
    },
    bookSlotBtn: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: COLORS.accent,
        backgroundColor: 'rgba(66, 165, 245, 0.1)',
    },
    bookSlotText: {
        color: COLORS.accent,
        fontSize: 10,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    nearbyTitleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    nearbyTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 16,
        flex: 1,
        marginRight: 8,
    },
    nearbyInfoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    nearbyDistance: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    nearbyDistanceText: {
        color: COLORS.textSecondary,
        fontSize: 11,
        fontFamily: FONTS.body,
        marginLeft: 4,
        fontWeight: '600',
    },
    nearbyTime: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    nearbyTimeText: {
        color: COLORS.textSecondary,
        fontSize: 11,
        fontFamily: FONTS.body,
        marginLeft: 4,
        fontWeight: '600',
    },
    nearbyBottomRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    priceTag: {
        backgroundColor: 'rgba(0, 230, 118, 0.15)',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(0, 230, 118, 0.3)',
    },
    priceTagText: {
        color: COLORS.successBright,
        fontFamily: FONTS.heading,
        fontSize: 13,
        fontWeight: '700',
    },
    roleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'nowrap',
        overflow: 'hidden',
        flex: 1,
        marginRight: 8,
    },
    roleTag: {
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 6,
        borderWidth: 1,
        marginRight: 6,
        backgroundColor: 'rgba(239, 83, 80, 0.1)',
        borderColor: 'rgba(239, 83, 80, 0.3)',
    },
    roleText: {
        color: COLORS.error,
        fontSize: 10,
        fontFamily: FONTS.body,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    moreRolesText: {
        color: COLORS.textSecondary,
        fontSize: 10,
        fontWeight: '600',
    },

    // 🎮 SECTION 4: Recommended (Refined)
    recommendedCard: {
        width: 220,
        backgroundColor: COLORS.cardDark,
        borderRadius: 20,
        padding: 16,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        marginRight: 12,
    },
    recommendedHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    recommendedGame: {
        color: COLORS.accent,
        fontSize: 11,
        fontFamily: FONTS.heading,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    matchScoreBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    matchScoreText: {
        color: '#FFF',
        fontSize: 10,
        fontWeight: '700',
        marginLeft: 4,
    },
    recommendedTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 15,
        marginBottom: 16,
        height: 40,
    },
    recommendedFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 'auto',
    },

    // 📅 SECTION 6: Upcoming (New Design)
    upcomingCard: {
        backgroundColor: COLORS.cardDark,
        borderRadius: 16,
        padding: SPACING.md,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: COLORS.accent + '40',
    },
    upcomingLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    upcomingTimeBox: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 50,
    },
    upcomingTimeBig: {
        color: COLORS.text,
        fontSize: 16,
        fontWeight: '700',
        fontFamily: FONTS.heading,
    },
    upcomingTimeSmall: {
        color: COLORS.textSecondary,
        fontSize: 10,
        textTransform: 'uppercase',
    },
    upcomingVerticalLine: {
        width: 1,
        height: 30,
        backgroundColor: COLORS.cardBorder,
        marginHorizontal: 12,
    },
    upcomingGame: {
        color: COLORS.accent,
        fontSize: 10,
        fontWeight: '700',
        marginBottom: 2,
    },
    upcomingTitle: {
        color: COLORS.text,
        fontSize: 14,
        fontFamily: FONTS.heading,
        marginBottom: 2,
    },
    upcomingPlayers: {
        color: COLORS.textSecondary,
        fontSize: 11,
    },
    upcomingActionBtn: {
        backgroundColor: COLORS.accent,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
    },
    upcomingActionText: {
        color: '#FFF',
        fontSize: 11,
        fontWeight: '700',
    },

    // 💰 SECTION 8: Wallet
    walletCard: {
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#1A1A1A',
        overflow: 'hidden',
    },
    walletContent: {
        zIndex: 1,
    },
    walletLabel: {
        color: COLORS.textSecondary,
        fontSize: 12,
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 4,
    },
    walletBalance: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 28,
        textShadowColor: 'rgba(66, 165, 245, 0.5)',
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 10,
    },
    walletIconContainer: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: 'rgba(66, 165, 245, 0.1)',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(66, 165, 245, 0.3)',
    },

    // 🎖 SECTION 9: Stats
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    statCard: {
        flex: 1,
        backgroundColor: COLORS.cardDark,
        paddingVertical: 16,
        paddingHorizontal: 8,
        borderRadius: 12,
        marginRight: 8,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
    },
    statValue: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 18,
        marginBottom: 2,
    },
    statLabel: {
        color: COLORS.textSecondary,
        fontSize: 10,
        textTransform: 'uppercase',
    },
});
