import { StyleSheet } from "react-native";

import {
  COLORS,
  CONTROL_SIZES,
  FONTS,
  RADII,
  SPACING,
  TEXT_SIZES,
} from "../../../src/theme";

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.backgroundDark,
  },
  screenContent: {
    paddingTop: 10,
    paddingBottom: 0,
  },
  container: {
    paddingBottom: SPACING.lg,
  },
  contentWrap: {
    flex: 1,
  },
  headerBar: {
    marginBottom: SPACING.sm,
  },
  verificationBanner: {
    backgroundColor: "rgba(255, 193, 7, 0.12)",
    borderColor: "rgba(255, 193, 7, 0.35)",
    borderWidth: 1,
    borderRadius: CONTROL_SIZES.cardRadius,
    padding: SPACING.lg,
    marginBottom: SPACING.lg,
  },
  verificationBannerHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  verificationBannerTitle: {
    color: COLORS.warning,
    fontFamily: FONTS.heading,
    fontSize: TEXT_SIZES.lg,
  },
  verificationBannerText: {
    color: COLORS.text,
    fontFamily: FONTS.interRegular,
    fontSize: 13,
    lineHeight: 20,
  },
  verificationBannerActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    marginTop: SPACING.md,
  },
  verificationPrimaryButton: {
    minWidth: 148,
  },
  verificationSecondaryButton: {
    minWidth: 148,
  },
  dashboardLocked: {
    opacity: 0.72,
  },
  dashboardLockState: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: SPACING.xs,
    backgroundColor: COLORS.overlayLight,
    borderColor: COLORS.cardBorder,
    borderWidth: 1,
    borderRadius: RADII.pill,
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginBottom: SPACING.md,
  },
  dashboardLockStateText: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.interMedium,
    fontSize: 12,
  },
  header: {
    paddingBottom: SPACING.md,
  },
  profileCard: {
    width: "100%",
    borderRadius: CONTROL_SIZES.cardRadius + 2,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    padding: SPACING.lg,
    backgroundColor: COLORS.cardDark,
  },
  profileTopRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: SPACING.md,
  },
  profileTextWrap: {
    flex: 1,
  },
  avatarContainer: {
    position: "relative",
    marginRight: SPACING.md,
  },
  avatar: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: COLORS.surfaceHighlight,
    borderWidth: 1,
    borderColor: `${COLORS.accent}55`,
  },
  onlineIndicator: {
    position: "absolute",
    bottom: 1,
    right: 1,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: COLORS.successBright,
    borderWidth: 2,
    borderColor: COLORS.backgroundDark,
  },
  welcomeText: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.interMedium,
    fontSize: 11,
    marginBottom: 4,
  },
  username: {
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: 22,
  },
  profileAccentBar: {
    width: 42,
    height: 4,
    borderRadius: RADII.pill,
    backgroundColor: COLORS.accent,
    marginBottom: SPACING.md,
  },
  notificationBell: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.cardDark,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  headerActionsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  friendBell: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.cardDark,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  headerActionDisabled: {
    opacity: 0.35,
  },
  friendBadge: {
    position: "absolute",
    top: -4,
    right: -6,
    backgroundColor: COLORS.successBright,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
    borderWidth: 2,
    borderColor: COLORS.backgroundDark,
  },
  friendBadgeText: {
    color: "#0B1016",
    fontSize: 11,
    fontWeight: "700",
  },
  notificationBadge: {
    position: "absolute",
    top: -4,
    right: -6,
    backgroundColor: COLORS.error,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
    borderWidth: 2,
    borderColor: COLORS.backgroundDark,
  },
  notificationBadgeText: {
    color: "#FFF",
    fontSize: 11,
    fontWeight: "700",
  },
  menuButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.cardDark,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  tagsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  tag: {
    marginRight: 0,
    marginBottom: 0,
  },
  tagText: {
    color: COLORS.textSecondary,
    fontSize: 11,
    fontFamily: FONTS.interMedium,
  },
  section: {
    marginTop: SPACING.xl,
  },
  quickActionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  quickActionBtn: {
    width: "48.5%",
    marginBottom: SPACING.md,
  },
  quickActionCard: {
    minHeight: 116,
    borderRadius: CONTROL_SIZES.cardRadius + 2,
    justifyContent: "space-between",
    borderColor: COLORS.cardBorder,
    padding: SPACING.md + 2,
  },
  quickActionIconContainer: {
    width: 46,
    height: 46,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
  },
  quickActionText: {
    color: COLORS.text,
    fontFamily: FONTS.interSemiBold,
    fontSize: 16,
  },
  notificationCard: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  notificationCardInner: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: SPACING.md,
  },
  notificationCardPressed: {
    opacity: 0.92,
  },
  notificationIconBox: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
    borderWidth: 1,
  },
  notificationContent: {
    flex: 1,
    paddingTop: 2,
  },
  notificationText: {
    color: COLORS.text,
    fontFamily: FONTS.interSemiBold,
    fontSize: 14,
    marginBottom: 6,
    lineHeight: 20,
  },
  notificationMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  notificationTime: {
    color: COLORS.textSecondary,
    fontSize: 12,
    fontFamily: FONTS.interMedium,
  },
  notificationCta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  notificationCtaText: {
    color: COLORS.accent,
    fontSize: 12,
    fontFamily: FONTS.interSemiBold,
  },
  alertsSectionBody: {
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
  },
  nearbyCard: {
    marginBottom: SPACING.md,
  },
  nearbyCardInner: {
    borderRadius: CONTROL_SIZES.cardRadius + 2,
    padding: SPACING.md + 2,
    borderColor: COLORS.cardBorder,
  },
  nearbyMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  nearbyGame: {
    color: COLORS.accent,
    fontSize: 11,
    fontFamily: FONTS.interSemiBold,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  nearbyStatusTag: {
    alignSelf: "auto",
    minHeight: 28,
  },
  nearbyStatusText: {
    fontSize: 11,
    fontFamily: FONTS.interSemiBold,
  },
  bookSlotBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: RADII.pill,
    borderWidth: 1,
    borderColor: `${COLORS.accent}50`,
    backgroundColor: `${COLORS.accent}10`,
  },
  bookSlotText: {
    color: COLORS.accent,
    fontSize: 11,
    fontFamily: FONTS.interSemiBold,
  },
  nearbyTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
    gap: SPACING.sm,
  },
  nearbyTitle: {
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: 18,
    flex: 1,
  },
  nearbyInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  nearbyDistance: {
    flexDirection: "row",
    alignItems: "center",
  },
  nearbyDistanceText: {
    color: COLORS.textSecondary,
    fontSize: 12,
    fontFamily: FONTS.interRegular,
    marginLeft: 4,
  },
  nearbyBottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: SPACING.sm,
  },
  nearbyGamesRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 12,
    gap: 8,
  },
  nearbyGameChip: {
    marginRight: 0,
    minHeight: 28,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  nearbyGameChipText: {
    color: COLORS.textSecondary,
    fontSize: 11,
    fontFamily: FONTS.interMedium,
  },
  nearbyCapacityText: {
    flex: 1,
    color: COLORS.textSecondary,
    fontSize: 12,
    fontFamily: FONTS.interRegular,
  },
  priceTag: {
    backgroundColor: `${COLORS.successBright}12`,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: RADII.pill,
    borderWidth: 1,
    borderColor: `${COLORS.successBright}2E`,
  },
  priceTagText: {
    color: COLORS.successBright,
    fontFamily: FONTS.interSemiBold,
    fontSize: 12,
  },
  glancePanel: {
    padding: SPACING.md,
    borderRadius: CONTROL_SIZES.cardRadius + 2,
    gap: SPACING.lg,
  },
  glanceHighlightGrid: {
    flexDirection: "column",
    gap: SPACING.sm,
  },
  glanceHighlightPressable: {
    width: "100%",
  },
  glanceHighlightCard: {
    minHeight: 92,
    borderRadius: CONTROL_SIZES.cardRadius - 2,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    backgroundColor: "rgba(255,255,255,0.02)",
    padding: SPACING.md,
    gap: SPACING.xs,
  },
  glanceHighlightHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  glanceHighlightTitleWrap: {
    flex: 1,
    gap: 6,
  },
  glanceHighlightLabel: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.interMedium,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  glanceHighlightMetaWrap: {
    alignItems: "flex-end",
    gap: 8,
  },
  glanceHighlightIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${COLORS.accent}12`,
    borderWidth: 1,
    borderColor: `${COLORS.accent}20`,
  },
  glanceHighlightAction: {
    color: COLORS.accent,
    fontFamily: FONTS.interSemiBold,
    fontSize: 11,
  },
  glanceHighlightValue: {
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: 22,
  },
  glanceHighlightDetail: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.interRegular,
    fontSize: 12,
    lineHeight: 18,
    maxWidth: "82%",
  },
  glanceMiniStatsRow: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  glanceMiniStat: {
    flex: 1,
    borderRadius: CONTROL_SIZES.cardRadius - 4,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    backgroundColor: "rgba(255,255,255,0.02)",
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.sm,
    alignItems: "center",
    gap: 2,
  },
  glanceMiniStatValue: {
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: 22,
  },
  glanceMiniStatLabel: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.interMedium,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  teamCard: {
    marginBottom: SPACING.md,
  },
  teamCardInner: {
    borderRadius: CONTROL_SIZES.cardRadius + 2,
    padding: SPACING.md + 2,
    borderColor: COLORS.cardBorder,
  },
  teamCardPressed: {
    opacity: 0.92,
  },
  teamTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  teamIdentityWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    marginRight: SPACING.sm,
  },
  teamAvatarWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: `${COLORS.accent}38`,
    backgroundColor: `${COLORS.accent}12`,
    alignItems: "center",
    justifyContent: "center",
    marginRight: SPACING.sm,
  },
  teamTextWrap: {
    flex: 1,
  },
  teamName: {
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: 16,
    marginBottom: 2,
  },
  teamSubtext: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.interRegular,
    fontSize: 12,
  },
  teamGamePill: {
    alignSelf: "auto",
    minHeight: 28,
  },
  teamGamePillText: {
    color: COLORS.accent,
    fontFamily: FONTS.interSemiBold,
    fontSize: 11,
  },
  teamMembersRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  teamMembersText: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.interRegular,
    fontSize: 12,
  },
  teamMembersCount: {
    color: COLORS.text,
    fontFamily: FONTS.interSemiBold,
    fontSize: 13,
  },
  teamProgressTrack: {
    height: 8,
    borderRadius: RADII.pill,
    backgroundColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
    marginBottom: 12,
  },
  teamProgressFill: {
    height: "100%",
    borderRadius: RADII.pill,
    backgroundColor: COLORS.accent,
  },
  teamBottomRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  teamStatsText: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.interRegular,
    fontSize: 12,
  },
  teamOpenPill: {
    alignSelf: "auto",
    minHeight: 28,
  },
  teamOpenPillText: {
    fontFamily: FONTS.interSemiBold,
    fontSize: 11,
  },
});
