import { Dimensions, StyleSheet } from 'react-native';
import { COLORS, CTA, FONTS, RADII, SHADOWS, SPACING, TEXT_SIZES } from '../../../src/theme';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLORS.background,
    },
    header: {
        paddingBottom: SPACING.lg,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.divider,
    },
    headerTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.heading,
        marginBottom: SPACING.lg,
        lineHeight: 34,
    },
    searchBar: {
        backgroundColor: COLORS.inputBackground,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: SPACING.md,
        marginVertical: SPACING.sm,
        height: 48,
    },
    searchInput: {
        flex: 1,
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.input,
        paddingVertical: 0,
        paddingHorizontal: SPACING.sm,
    },
    filterToggle: {
        marginLeft: 10,
    },
    filterOptionsScroll: {
        flexGrow: 0,
    },
    filtersPanel: {
        paddingBottom: SPACING.md,
        backgroundColor: COLORS.background,
    },
    filterSection: {
        marginBottom: 15,
    },
    filterLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: COLORS.text,
        marginBottom: 8,
    },
    optionChip: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 999,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.cardBackground,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm - 1,
        marginRight: SPACING.sm,
        marginBottom: 5,
    },
    optionChipActive: {
        backgroundColor: '#1e2a38',
        borderColor: COLORS.accent,
    },
    optionChipText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.label - 1,
    },
    optionChipTextActive: {
        color: COLORS.text,
    },
    locationDropdown: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: COLORS.surface,
        borderRadius: 12,
        paddingHorizontal: 15,
        height: 50,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
    },
    locationDropdownActive: {
        borderColor: COLORS.accent,
        backgroundColor: COLORS.accent + '10',
    },
    locationDropdownText: {
        color: COLORS.text,
        fontSize: 15,
    },
    locationDropdownTextActive: {
        color: COLORS.accent,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
    },
    lockBadge: {
        backgroundColor: COLORS.error,
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 2,
    },
    lockBadgeText: {
        color: '#FFF',
        fontSize: 10,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
    },
    nearbyCard: {
        backgroundColor: COLORS.cardBackground,
        borderRadius: RADII.md,
        padding: SPACING.md,
        marginBottom: SPACING.md,
        borderWidth: 1,
        borderColor: COLORS.divider,
        ...SHADOWS.cardSoft,
    },
    nearbyTitleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    nearbyGame: {
        color: COLORS.accent,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.xs,
        textTransform: 'uppercase',
    },
    nearbyTitle: {
        flex: 1,
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.subheading,
        marginRight: SPACING.md,
    },
    bookSlotBtn: {
        paddingHorizontal: 12,
        paddingVertical: 5,
        borderRadius: 8,
        backgroundColor: COLORS.accent + '33',
        borderWidth: 1.5,
        borderColor: COLORS.accent + '80',
    },
    bookSlotText: {
        color: COLORS.accent,
        fontSize: 10,
        fontFamily: FONTS.heading,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    // Specialized action buttons
    requestBtn: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        backgroundColor: COLORS.accent + '33',
        borderWidth: 1.5,
        borderColor: COLORS.accent,
    },
    requestBtnText: {
        color: COLORS.accent,
        fontSize: 10,
        fontFamily: FONTS.heading,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    requestedBtn: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
        backgroundColor: COLORS.warning + '25',
        borderWidth: 1.5,
        borderColor: COLORS.warning + '80',
    },
    requestedBtnText: {
        color: COLORS.warning,
        fontSize: 10,
        fontFamily: FONTS.heading,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    joinedBtn: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
        backgroundColor: COLORS.success + '25',
        borderWidth: 1.5,
        borderColor: COLORS.success + '80',
    },
    joinedBtnText: {
        color: COLORS.success,
        fontSize: 10,
        fontFamily: FONTS.heading,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    viewBtn: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
        backgroundColor: COLORS.overlayMedium,
        borderWidth: 1.5,
        borderColor: COLORS.divider,
    },
    viewBtnText: {
        color: COLORS.text,
        fontSize: 10,
        fontFamily: FONTS.heading,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    nearbyInfoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    nearbyDistance: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    nearbyDistanceText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    nearbyTime: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    nearbyTimeText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption,
    },
    nearbyBottomRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 4,
    },
    roleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    roleTag: {
        backgroundColor: COLORS.overlayLight,
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 4,
    },
    roleText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: 10,
    },
    skillTag: {
        backgroundColor: COLORS.accent + '15',
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 4,
    },
    skillText: {
        color: COLORS.accent,
        fontFamily: FONTS.heading,
        fontSize: 10,
        fontWeight: 'bold',
    },
    moreRolesText: {
        color: COLORS.textSecondary,
        fontSize: 10,
        fontFamily: FONTS.body,
    },
    priceTagContainer: {
        backgroundColor: COLORS.success + '15',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: COLORS.success + '30',
    },
    priceTagText: {
        color: COLORS.success,
        fontFamily: FONTS.heading,
        fontSize: 11,
        fontWeight: 'bold',
    },
    matchScoreBadge: {
        backgroundColor: '#FFD54F20',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 2,
    },
    matchScoreText: {
        color: '#FFD54F',
        fontSize: 10,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
    },
    resultsCount: {
        paddingTop: SPACING.md,
        paddingBottom: SPACING.sm,
    },
    resultsCountText: {
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.caption,
    },
    listContent: {
        paddingBottom: 100,
    },
    emptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 60,
        paddingHorizontal: 40,
    },
    emptyStateIcon: {
        marginBottom: 20,
        opacity: 0.8,
    },
    emptyStateTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: COLORS.text,
        marginBottom: 8,
    },
    emptyStateSubtitle: {
        fontSize: 14,
        color: COLORS.textSecondary,
        textAlign: 'center',
        lineHeight: 20,
    },
    emptyContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 60,
    },
    emptyTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: COLORS.text,
    },
    emptySubtitle: {
        fontSize: 14,
        color: COLORS.muted,
    },
    gameFiltersScroll: {
        marginTop: SPACING.sm,
    },
    gameFiltersContent: {
        paddingRight: SPACING.md,
    },
    fabWrapper: {
        position: 'absolute',
        right: SPACING.xl,
        zIndex: 20,
        elevation: 12,
        pointerEvents: 'box-none',
    },
    fab: {
        ...CTA.fabButton,
    },
    resetButton: {
        padding: 5,
    },
    resetButtonText: {
        color: COLORS.accent,
        fontSize: 14,
        fontWeight: '600',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.7)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: COLORS.surface,
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
        padding: 20,
        maxHeight: '80%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: COLORS.text,
    },
    modalSearchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.background,
        borderRadius: 12,
        paddingHorizontal: 12,
        height: 48,
        marginBottom: 15,
    },
    modalSearchInput: {
        flex: 1,
        marginLeft: 10,
        color: COLORS.text,
        fontSize: 15,
    },
    modalListItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.divider,
    },
    modalListItemText: {
        fontSize: 16,
        color: COLORS.text,
    },
    modalListItemTextActive: {
        color: COLORS.accent,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
    }
});
