import { StyleSheet } from "react-native";

import {
  COLORS,
  FONTS,
  RADII,
  SHADOWS,
  SPACING,
  SURFACES,
  TEXT_SIZES,
} from "../theme";

export default StyleSheet.create({
  searchFilterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  searchBar: {
    minHeight: 48,
    flex: 1,
    borderRadius: RADII.lg,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    backgroundColor: COLORS.cardDark,
    paddingHorizontal: SPACING.md,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  searchInput: {
    flex: 1,
    color: COLORS.text,
    fontFamily: FONTS.montserratRegular,
    fontSize: TEXT_SIZES.body,
    paddingVertical: 0,
    minWidth: 0,
  },
  filterButton: {
    width: 48,
    minHeight: 48,
    borderRadius: RADII.md,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    backgroundColor: COLORS.cardDark,
    alignItems: "center",
    justifyContent: "center",
  },
  filterBadge: {
    position: "absolute",
    top: 5,
    right: 5,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 5,
    backgroundColor: COLORS.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  filterBadgeText: {
    color: "#FFFFFF",
    fontFamily: FONTS.interSemiBold,
    fontSize: 10,
    lineHeight: 12,
  },
  filterDrawer: {
    flex: 1,
    backgroundColor: COLORS.backgroundDark,
  },
  filterDrawerContent: {
    flex: 1,
  },
  filterDrawerBody: {
    gap: SPACING.lg,
  },
  filterDrawerFooterRow: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  filterDrawerFooterButton: {
    flex: 1,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
    marginBottom: SPACING.sm,
  },
  sectionHeaderCompact: {
    marginBottom: SPACING.sm,
  },
  sectionHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  sectionTitle: {
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: TEXT_SIZES.lg,
    letterSpacing: 0,
  },
  sectionSubtitle: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.interRegular,
    fontSize: TEXT_SIZES.caption,
    marginTop: 4,
    lineHeight: 17,
  },
  sectionAction: {
    color: COLORS.accent,
    fontFamily: FONTS.interSemiBold,
    fontSize: TEXT_SIZES.caption,
  },
  metricCard: {
    flex: 1,
    minWidth: 150,
    minHeight: 102,
    justifyContent: "space-between",
    padding: SPACING.md + 2,
  },
  metricCardTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  metricIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${COLORS.accent}12`,
    borderWidth: 1,
    borderColor: `${COLORS.accent}38`,
  },
  metricValue: {
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: 24,
  },
  metricLabel: {
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: TEXT_SIZES.label,
  },
  metricSubtitle: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.interRegular,
    fontSize: TEXT_SIZES.caption,
    lineHeight: 17,
  },
  quickActionPressable: {
    width: "100%",
  },
  pressedCard: {
    opacity: 0.92,
    transform: [{ scale: 0.985 }],
  },
  adminQuickActionCard: {
    width: "100%",
    flex: 1,
    minHeight: 116,
    justifyContent: "space-between",
    padding: SPACING.md + 2,
  },
  quickActionTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    minWidth: 0,
  },
  quickActionIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: `${COLORS.accent}38`,
    backgroundColor: `${COLORS.accent}12`,
  },
  quickActionTitle: {
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: TEXT_SIZES.label,
    lineHeight: 18,
    marginTop: SPACING.md,
  },
  quickActionDescription: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.interRegular,
    fontSize: TEXT_SIZES.caption,
    lineHeight: 16,
    marginTop: 4,
  },
  quickActionTextWrap: {
    minWidth: 0,
  },
  listCard: {
    gap: SPACING.md,
    padding: SPACING.md + 2,
  },
  listCardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  listCardHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  listCardTitle: {
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: TEXT_SIZES.lg,
  },
  listCardSubtitle: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.interRegular,
    fontSize: TEXT_SIZES.caption,
    lineHeight: 18,
    marginTop: 4,
  },
  infoStack: {
    gap: SPACING.sm,
  },
  infoLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: SPACING.md,
  },
  infoLabel: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.body,
    fontSize: TEXT_SIZES.caption + 1,
    flex: 1,
  },
  infoValue: {
    color: COLORS.text,
    fontFamily: FONTS.body,
    fontSize: TEXT_SIZES.caption + 1,
    flex: 1,
    textAlign: "right",
  },
  actionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  emptyCard: {
    paddingVertical: SPACING.xl,
    borderRadius: RADII.xl,
  },
  emptyIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: SURFACES.muted,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    marginBottom: SPACING.md,
  },
  emptyTitle: {
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: TEXT_SIZES.lg,
    textAlign: "center",
  },
  emptyDescription: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.interRegular,
    fontSize: TEXT_SIZES.caption + 1,
    textAlign: "center",
    lineHeight: 20,
    marginTop: SPACING.sm,
  },
  noticeCard: {
    ...SHADOWS.cardSoft,
  },
});
