import { StyleSheet } from "react-native";
import { COLORS, FONTS, RADII, SHADOWS, SPACING, TEXT_SIZES } from "../../src/theme";

export default StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    content: {
        paddingHorizontal: 0,
        paddingBottom: SPACING.xxl + 20,
        gap: SPACING.md,
        alignItems: "stretch",
    },
    loaderWrap: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
    },
    emptyText: {
        color: COLORS.muted,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.body,
    },
    card: {
        alignSelf: "stretch",
        width: "100%",
        backgroundColor: COLORS.cardDark,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.08)",
        borderRadius: RADII.lg,
        padding: SPACING.md,
        ...SHADOWS.cardSoft,
    },
    title: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.subheading + 2,
        marginBottom: SPACING.sm,
    },
    meta: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.caption + 1,
        marginBottom: 4,
        lineHeight: 18,
    },
    statusRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: SPACING.sm,
    },
    pendingBadge: {
        borderWidth: 1,
        borderColor: "rgba(255, 193, 7, 0.4)",
        backgroundColor: "rgba(255, 193, 7, 0.14)",
        borderRadius: RADII.pill,
        minHeight: 26,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 10,
    },
    pendingBadgeText: {
        color: COLORS.warning,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
    },
    sectionHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: SPACING.xs,
    },
    sectionTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.body + 1,
    },
    chatButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        borderWidth: 1,
        borderColor: "rgba(66, 165, 245, 0.3)",
        backgroundColor: "rgba(66, 165, 245, 0.12)",
        alignItems: "center",
        justifyContent: "center",
    },
    chatButtonDisabled: {
        borderColor: "rgba(255,255,255,0.2)",
        backgroundColor: "rgba(255,255,255,0.06)",
    },
    chatButtonPressed: {
        opacity: 0.85,
    },
    primaryButton: {
        marginTop: SPACING.sm,
        minHeight: 46,
        borderRadius: RADII.md,
        backgroundColor: COLORS.accent,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: SPACING.md,
    },
    primaryButtonPressed: {
        opacity: 0.9,
    },
    primaryButtonDisabled: {
        opacity: 0.55,
    },
    primaryButtonText: {
        color: "#FFFFFF",
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.body,
        fontWeight: "700",
    },
    challengeActionButton: {
        marginTop: SPACING.sm,
    },
    rejectButton: {
        marginTop: SPACING.sm,
        minHeight: 46,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: "rgba(244, 67, 54, 0.45)",
        backgroundColor: "rgba(244, 67, 54, 0.12)",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: SPACING.md,
    },
    rejectButtonText: {
        color: COLORS.error,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.body,
    },
    inlineButton: {
        marginTop: SPACING.sm,
        alignSelf: "flex-start",
        minHeight: 34,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: "rgba(66, 165, 245, 0.35)",
        backgroundColor: "rgba(66, 165, 245, 0.1)",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: SPACING.md,
    },
    inlineButtonText: {
        color: COLORS.accent,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption + 1,
    },
    chipsWrap: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
        marginTop: 4,
    },
    chip: {
        borderWidth: 1,
        borderColor: "rgba(66, 165, 245, 0.32)",
        backgroundColor: "rgba(66, 165, 245, 0.1)",
        borderRadius: RADII.pill,
        minHeight: 32,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 12,
    },
    chipText: {
        color: COLORS.accent,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
    },
    lineupPanel: {
        marginTop: SPACING.sm,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        backgroundColor: COLORS.cardBackground,
        borderRadius: RADII.md,
        padding: SPACING.md,
        gap: SPACING.sm,
    },
    lineupTitle: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.body,
        fontWeight: "700",
    },
    lineupGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
    },
    lineupChip: {
        minHeight: 34,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        backgroundColor: COLORS.overlayMedium,
        paddingHorizontal: 12,
        paddingVertical: 6,
        alignItems: "center",
        justifyContent: "center",
    },
    lineupChipSelected: {
        borderColor: COLORS.accent,
        backgroundColor: `${COLORS.accent}18`,
    },
    lineupChipSub: {
        borderColor: `${COLORS.successBright}55`,
    },
    lineupChipText: {
        color: COLORS.textSecondary,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption,
    },
    lineupChipTextSelected: {
        color: COLORS.text,
    },
    lineupSubText: {
        color: COLORS.successBright,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.xs,
        marginTop: 2,
    },
    rejectedBanner: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        borderWidth: 1,
        borderColor: "rgba(244, 67, 54, 0.4)",
        backgroundColor: "rgba(244, 67, 54, 0.12)",
        borderRadius: RADII.md,
        padding: SPACING.sm,
    },
    rejectedText: {
        color: COLORS.error,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.caption + 1,
    },
});

