import { StyleSheet } from 'react-native';
import { COLORS, RADII, SHADOWS, SPACING, TEXT_SIZES } from '../../../src/theme';

export default StyleSheet.create({
    container: {
        width: '100%',
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: SPACING.md,
    },
    memberCard: {
        width: '47.5%', // 2 columns with gap
        backgroundColor: COLORS.cardDark,
        borderRadius: RADII.lg,
        padding: SPACING.md,
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.sm,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        ...SHADOWS.cardSoft,
    },
    captainCard: {
        borderColor: `${COLORS.warning}80`,
        backgroundColor: `${COLORS.warning}08`,
    },
    pressed: {
        opacity: 0.8,
    },
    emptySlot: {
        width: '47.5%',
        backgroundColor: 'transparent',
        borderRadius: RADII.lg,
        padding: SPACING.md,
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.sm,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderStyle: 'dashed',
        opacity: 0.5,
    },
    avatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: COLORS.surfaceHighlight,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: COLORS.accent,
        position: 'relative',
    },
    captainBadge: {
        position: 'absolute',
        top: -4,
        right: -4,
        backgroundColor: COLORS.warning,
        borderRadius: 10,
        width: 20,
        height: 20,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: COLORS.cardDark,
    },
    avatarText: {
        fontSize: TEXT_SIZES.lg,
        fontWeight: '700',
        color: COLORS.text,
    },
    memberInfo: {
        flex: 1,
        gap: 4,
    },
    memberName: {
        fontSize: TEXT_SIZES.label,
        color: COLORS.text,
        fontWeight: '600',
    },
    roleContainer: {
        alignSelf: 'flex-start',
    },
    roleText: {
        fontSize: TEXT_SIZES.xs,
        color: COLORS.accent,
        backgroundColor: `${COLORS.accent}15`,
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: RADII.xs,
        overflow: 'hidden',
    },
    youBadge: {
        alignSelf: 'flex-start',
        backgroundColor: `${COLORS.success}15`,
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: RADII.xs,
    },
    youText: {
        fontSize: TEXT_SIZES.xs,
        fontWeight: '700',
        color: COLORS.success,
    },
    emptyIcon: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        borderStyle: 'dashed',
    },
    emptyText: {
        fontSize: TEXT_SIZES.label,
        color: COLORS.muted,
        fontWeight: '500',
    },
});
