import { StyleSheet } from 'react-native';
import { COLORS, CTA, FONTS, RADII, SHADOWS, SPACING, TEXT_SIZES } from '../../src/theme';

export default StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    screenContent: {
        paddingBottom: 0,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 18,
        backgroundColor: COLORS.backgroundDark,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.cardBorder,
    },
    backButton: {
        marginRight: SPACING.md,
        padding: 4,
    },
    headerTitle: {
        color: COLORS.text,
        fontSize: TEXT_SIZES.subheading,
        fontFamily: FONTS.heading,
    },
    content: {
        paddingBottom: 0,
    },
    adminContent: {
        paddingBottom: 0,
    },

    // Main Info Card
    mainCard: {
        marginBottom: SPACING.lg,
    },
    gameDateRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: SPACING.sm,
    },
    gameBadge: {
        backgroundColor: COLORS.accent,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: RADII.sm,
        marginRight: SPACING.sm,
    },
    gameText: {
        color: '#FFF',
        fontSize: 10,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    dateText: {
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.caption,
        fontFamily: FONTS.body,
    },
    title: {
        color: COLORS.text,
        fontSize: 26,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
        marginBottom: 8,
        lineHeight: 34,
    },
    description: {
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.body,
        lineHeight: 22,
    },

    // Info Grid (Location, Price, etc)
    infoGrid: {
        flexDirection: 'column',
        gap: 12,
        marginBottom: SPACING.xl,
        backgroundColor: 'rgba(255,255,255,0.02)',
        padding: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
    },
    infoItem: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
    },
    infoIcon: {
        marginRight: SPACING.sm,
    },
    infoLabel: {
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.xs,
        fontFamily: FONTS.body,
        textTransform: 'uppercase',
    },
    infoValue: {
        color: COLORS.text,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.heading,
        fontWeight: '700',
    },

    // Banners
    banner: {
        padding: SPACING.md,
        borderRadius: RADII.sm,
        marginBottom: SPACING.lg,
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.sm,
    },
    expiredBanner: {
        backgroundColor: COLORS.error,
    },
    lockedBanner: {
        backgroundColor: COLORS.warning,
    },
    qrCard: {
        backgroundColor: COLORS.cardDark,
        borderRadius: 16,
        padding: SPACING.lg,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        marginBottom: SPACING.lg,
    },
    qrHeader: {
        marginBottom: SPACING.md,
    },
    qrTitle: {
        color: COLORS.text,
        fontSize: 16,
        fontFamily: FONTS.heading,
        marginBottom: 4,
    },
    qrSubtitle: {
        color: COLORS.muted,
        fontSize: 12,
        fontFamily: FONTS.body,
    },
    qrBody: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.lg,
    },
    qrInfo: {
        flex: 1,
    },
    qrCodeLabel: {
        color: COLORS.muted,
        fontSize: 12,
        fontFamily: FONTS.body,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    qrCodeValue: {
        color: COLORS.text,
        fontSize: 20,
        fontFamily: FONTS.heading,
        marginTop: 4,
        marginBottom: 6,
    },
    qrHint: {
        color: COLORS.textSecondary,
        fontSize: 11,
        fontFamily: FONTS.body,
    },
    bannerText: {
        color: '#FFF',
        flex: 1,
        fontSize: TEXT_SIZES.label,
        fontFamily: FONTS.heading,
        fontWeight: '500',
    },

    // Section Headers
    sectionTitle: {
        color: COLORS.text,
        fontSize: TEXT_SIZES.subheading,
        fontFamily: FONTS.heading,
        marginBottom: SPACING.md,
    },
    sectionMetaText: {
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.caption,
        fontFamily: FONTS.body,
    },

    // Roles / Players
    playersContainer: {
        backgroundColor: COLORS.cardDark,
        borderRadius: RADII.md,
        padding: SPACING.md,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        marginBottom: SPACING.xl,
    },
    playerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: SPACING.sm,
        paddingBottom: SPACING.sm,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.overlayLight,
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: COLORS.overlayMedium,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: SPACING.md,
    },
    avatarText: {
        color: COLORS.text,
        fontSize: 16,
        fontWeight: 'bold',
    },
    playerInfo: {
        flex: 1,
    },
    playerName: {
        color: COLORS.text,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.heading,
    },
    playerRole: {
        color: COLORS.accent,
        fontSize: TEXT_SIZES.caption,
        fontFamily: FONTS.body,
    },
    hostBadge: {
        backgroundColor: COLORS.overlayLight,
        paddingHorizontal: 4,
        paddingVertical: 1,
        borderRadius: 4,
        marginLeft: 6,
    },
    hostText: {
        color: COLORS.textSecondary,
        fontSize: 10,
        fontWeight: 'bold',
    },

    // Footer Actions
    body: {
        flex: 1,
    },
    buttonWrapper: {
        marginTop: SPACING.md,
    },
    buttonContent: {
        width: '100%',
    },
    floatingActionBar: {
        position: 'absolute',
        left: 0,
        right: 0,
        zIndex: 100,
        elevation: 100,
    },
    headerActionButton: {
        padding: 2,
    },
    headerActionPressed: {
        opacity: 0.72,
    },
    footerButtonPressed: {
        ...CTA.primaryButtonPressed,
    },
    footerRow: {
        flexDirection: 'row',
        gap: SPACING.md,
        alignItems: 'center',
    },
    footerAction: {
        flex: 1,
    },
    pendingRequestsCard: {
        marginTop: SPACING.lg,
    },
    joinButton: {
        backgroundColor: COLORS.accent,
        paddingVertical: 14,
        borderRadius: RADII.md,
        alignItems: 'center',
        ...SHADOWS.accentStrong,
    },
    joinButtonText: {
        color: '#FFF',
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
    },
    joinedButton: {
        backgroundColor: COLORS.overlayLight,
        paddingVertical: 14,
        borderRadius: RADII.md,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
    },
    joinedText: {
        color: COLORS.text,
        fontFamily: FONTS.heading,
        fontSize: 14,
        fontWeight: 'bold',
    },
    secondaryButton: {
        backgroundColor: 'transparent',
        paddingVertical: 14,
        borderRadius: RADII.md,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: COLORS.error + '50',
    },
    secondaryButtonText: {
        color: COLORS.error,
        fontSize: 14,
        fontFamily: FONTS.heading,
        fontWeight: 'bold', // Match weight with primary buttons
    },
    warningActionButton: {
        borderColor: `${COLORS.warning}55`,
        backgroundColor: `${COLORS.warning}14`,
    },
    warningActionText: {
        color: COLORS.warning,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
    },
    forceCancelButton: {
        marginTop: SPACING.xs,
    },
    fullButton: {
        backgroundColor: COLORS.overlayMedium,
        paddingVertical: 14,
        borderRadius: RADII.md,
        alignItems: 'center',
    },
    fullText: {
        color: COLORS.textSecondary,
        fontWeight: 'bold',
    },
    getRequestButton: {
        width: '100%',
        ...CTA.primaryButton,
    },
    getRequestButtonText: {
        ...CTA.primaryButtonText,
    },
    cancelRequestButton: {
        backgroundColor: COLORS.error + '15',
        width: '100%',
        minHeight: 56,
        borderWidth: 1.5,
        borderColor: COLORS.error + '60',
        paddingVertical: 14,
        borderRadius: RADII.md,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelRequestButtonText: {
        color: COLORS.error,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },

    // Role Selection Modal
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.8)',
        justifyContent: 'flex-end', // Align friend modal to bottom
    },
    modalContent: {
        backgroundColor: COLORS.cardBackground,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 24,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.cardBorder,
    },
    modalTitle: {
        color: COLORS.text,
        fontSize: 20,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
    },
    roleOption: {
        padding: SPACING.md,
        backgroundColor: COLORS.overlayLight,
        borderRadius: RADII.sm,
        marginBottom: SPACING.sm,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    roleOptionSelected: {
        borderColor: COLORS.accent,
        backgroundColor: 'rgba(66, 165, 245, 0.1)',
    },
    roleOptionText: {
        color: COLORS.text,
        fontSize: TEXT_SIZES.body,
        textAlign: 'center',
    },
    modalActions: {
        flexDirection: 'row',
        gap: SPACING.md,
        marginTop: SPACING.md,
    },
    modalButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: RADII.sm,
        alignItems: 'center',
    },
    cancelButton: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: COLORS.overlayMedium,
    },
    confirmButton: {
        backgroundColor: COLORS.accent,
    },

    // Join Code Modal Specifics
    codeSubtext: {
        color: COLORS.textSecondary,
        textAlign: 'center',
        marginBottom: SPACING.lg,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.label,
    },
    codeInput: {
        backgroundColor: COLORS.inputBackground,
        color: COLORS.text,
        padding: SPACING.md,
        borderRadius: RADII.sm,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        fontSize: TEXT_SIZES.input,
        textAlign: 'center',
        marginBottom: SPACING.xl,
        fontFamily: FONTS.body,
    },
    statusBanner: {
        padding: SPACING.md,
        borderRadius: RADII.sm,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.overlayLight,
    },
    statusText: {
        color: COLORS.accent,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.label,
        fontWeight: 'bold',
    },
    assessmentMessage: {
        color: COLORS.textSecondary,
        textAlign: 'center',
        marginBottom: SPACING.xl,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.body,
    },
    loadingContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.backgroundDark,
    },
    // Team Comparison / Slot System
    teamsWrapper: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: SPACING.lg,
        marginBottom: SPACING.xl,
    },
    teamContainer: {
        backgroundColor: COLORS.cardBackground,
        borderRadius: 24,
        padding: 20,
        // Removed borders and shadows for a cleaner look
    },
    teamTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: SPACING.md,
        paddingBottom: SPACING.xs,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.overlayLight,
    },
    teamTitle: {
        color: COLORS.text,
        fontSize: TEXT_SIZES.label,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
    },
    captainBadge: {
        backgroundColor: COLORS.warning + '20',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: COLORS.warning + '40',
    },
    captainText: {
        color: COLORS.warning,
        fontSize: 8,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    slotRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderRadius: 18,
        marginBottom: 8,
        backgroundColor: 'rgba(255,255,255,0.02)', // Minimal background
        // Shadows removed per request
    },
    slotAvatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: COLORS.cardBorder,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.1)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    slotAvatarText: {
        color: COLORS.text,
        fontSize: 16,
        fontFamily: FONTS.heading,
        fontWeight: '900',
        letterSpacing: 0.5,
    },
    slotInfo: {
        flex: 1,
    },
    slotName: {
        color: COLORS.text,
        fontSize: 15,
        fontFamily: FONTS.heading,
        fontWeight: '700',
        letterSpacing: 0.3,
    },
    slotRoleName: {
        color: COLORS.accent,
        fontSize: 11,
        fontFamily: FONTS.body,
        marginTop: 2,
        opacity: 0.8,
    },
    emptySlotName: {
        color: COLORS.textSecondary,
        fontSize: 13,
        fontFamily: FONTS.body,
        fontStyle: 'italic',
        opacity: 0.6,
    },
    joinSlotButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.cardDark,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: COLORS.accent,
        minWidth: 0,
    },
    requestedSlotButton: {
        backgroundColor: COLORS.cardDark,
        borderColor: COLORS.accent,
    },
    requestedSlotText: {
        color: COLORS.text,
        fontWeight: 'bold',
    },
    rejectedSlotButton: {
        backgroundColor: COLORS.cardDark,
        borderColor: COLORS.error,
    },
    rejectedSlotText: {
        color: COLORS.error,
        fontWeight: 'bold',
    },
    joinSlotText: {
        color: COLORS.text,
        fontSize: 13,
        fontFamily: FONTS.body,
        fontWeight: 'bold',
    },
    inviteSlotButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.cardDark,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: COLORS.accent,
        minWidth: 0,
    },
    inviteSlotText: {
        color: COLORS.text,
        fontSize: 13,
        fontFamily: FONTS.body,
        fontWeight: 'bold',
    },
    friendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        marginHorizontal: 16,
        marginBottom: 8,
        backgroundColor: 'rgba(255,255,255,0.03)',
        borderRadius: 16,
    },
    friendAvatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: COLORS.overlayLight,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
    },
    friendName: {
        color: COLORS.text,
        fontSize: 16,
        fontFamily: FONTS.heading,
        fontWeight: '500',
        flex: 1,
    },
    sendInviteButton: {
        backgroundColor: COLORS.accent,
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 10,
    },
    sendInviteText: {
        color: '#FFF',
        fontSize: 13,
        fontFamily: FONTS.heading,
        fontWeight: '600',
    },
    friendListEmpty: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
    },
    emptyModalText: {
        color: COLORS.muted,
        fontSize: 14,
        marginTop: 12,
        textAlign: 'center',
    },
    // Complain Styles
    complainBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        minHeight: 56,
        backgroundColor: COLORS.error + '10',
        borderWidth: 1,
        borderColor: COLORS.error + '40',
        paddingHorizontal: SPACING.lg,
        paddingVertical: 14,
        borderRadius: RADII.md,
        marginTop: SPACING.sm,
        gap: 8,
    },
    complainBtnText: {
        color: COLORS.error,
        fontSize: 13,
        fontFamily: FONTS.heading,
        fontWeight: '800',
        textTransform: 'uppercase',
        letterSpacing: 1.2,
    },
    modalSubtitle: {
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.caption,
        fontFamily: FONTS.body,
        marginTop: 2,
    },
    input: {
        backgroundColor: COLORS.overlayLight,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        padding: SPACING.md,
        color: COLORS.text,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.body,
    },
    modalFormContent: {
        paddingHorizontal: SPACING.xl,
        paddingTop: SPACING.lg,
        paddingBottom: SPACING.md,
        gap: SPACING.md,
    },
    modalSectionCard: {
        backgroundColor: COLORS.cardBackground,
        borderRadius: RADII.lg,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        padding: SPACING.lg,
        gap: SPACING.sm,
    },
    modalHelperText: {
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.caption,
        fontFamily: FONTS.body,
        lineHeight: 18,
    },
    modalChipWrap: {
        flexDirection: "row",
        flexWrap: "wrap",
        marginTop: 2,
    },
    textArea: {
        minHeight: 120,
        textAlignVertical: 'top',
    },
    modalTextArea: {
        minHeight: 96,
        textAlignVertical: "top",
    },
    modalFooter: {
        paddingHorizontal: SPACING.xl,
    },
    modalActionsRow: {
        flexDirection: "row",
        gap: SPACING.sm,
    },
    modalActionButton: {
        flex: 1,
        minHeight: 50,
    },
    modalActionText: {
        color: '#FFF',
        fontSize: 16,
        fontFamily: FONTS.heading,
        fontWeight: '800',
        letterSpacing: 0.5,
    },
    reasonChip: {
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: RADII.pill,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        marginRight: 8,
        marginBottom: 8,
        backgroundColor: COLORS.overlayLight,
    },
    reasonChipActive: {
        borderColor: COLORS.error,
        backgroundColor: COLORS.error + '20',
    },
    reasonText: {
        color: COLORS.textSecondary,
        fontSize: 13,
        fontFamily: FONTS.medium,
    },
    reasonTextActive: {
        color: COLORS.error,
        fontWeight: 'bold',
    },
    cardLabel: {
        color: COLORS.textSecondary,
        fontSize: 12,
        fontFamily: FONTS.heading,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },

    // Suggest Alternative Modal
    suggestDateRow: {
        flexDirection: 'row',
        gap: SPACING.sm,
    },
    suggestDateField: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: COLORS.overlayLight,
        borderRadius: RADII.md,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        paddingVertical: 14,
        paddingHorizontal: SPACING.md,
    },
    suggestDateFieldText: {
        color: COLORS.text,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.body,
    },
    suggestSubmitButton: {
        backgroundColor: COLORS.warning,
        padding: 16,
        borderRadius: RADII.md,
        alignItems: 'center',
        marginTop: SPACING.xl,
        shadowColor: COLORS.warning,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
});

