import { StyleSheet } from 'react-native';
import { COLORS, FONTS, RADII, SHADOWS, SPACING, TEXT_SIZES } from '../../src/theme';

export default StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: COLORS.backgroundDark,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 18,
        backgroundColor: COLORS.background,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.cardBorder,
    },
    backButton: {
        marginRight: SPACING.md,
        padding: 4,
    },
    headerTitle: {
        color: COLORS.text,
        fontSize: TEXT_SIZES.subheading,
        fontFamily: FONTS.heading,
    },
    content: {
        paddingBottom: 100,
    },

    // Main Info Card
    mainCard: {
        marginBottom: SPACING.lg,
    },
    gameDateRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: SPACING.sm,
    },
    gameBadge: {
        backgroundColor: COLORS.accent,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: RADII.sm,
        marginRight: SPACING.sm,
    },
    gameText: {
        color: '#FFF',
        fontSize: 10,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    dateText: {
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.caption,
        fontFamily: FONTS.body,
    },
    title: {
        color: COLORS.text,
        fontSize: 26,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
        marginBottom: 8,
        lineHeight: 34,
    },
    description: {
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.body,
        lineHeight: 22,
    },

    // Info Grid (Location, Price, etc)
    infoGrid: {
        flexDirection: 'column',
        gap: 12,
        marginBottom: SPACING.xl,
        backgroundColor: 'rgba(255,255,255,0.02)',
        padding: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
    },
    infoItem: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
    },
    infoIcon: {
        marginRight: SPACING.sm,
    },
    infoLabel: {
        color: COLORS.textSecondary,
        fontSize: TEXT_SIZES.xs,
        fontFamily: FONTS.body,
        textTransform: 'uppercase',
    },
    infoValue: {
        color: COLORS.text,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.heading,
        fontWeight: '700',
    },

    // Banners
    banner: {
        padding: SPACING.md,
        borderRadius: RADII.sm,
        marginBottom: SPACING.lg,
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.sm,
    },
    expiredBanner: {
        backgroundColor: COLORS.error,
    },
    lockedBanner: {
        backgroundColor: COLORS.warning,
    },
    qrCard: {
        backgroundColor: COLORS.cardDark,
        borderRadius: 16,
        padding: SPACING.lg,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        marginBottom: SPACING.lg,
    },
    qrHeader: {
        marginBottom: SPACING.md,
    },
    qrTitle: {
        color: COLORS.text,
        fontSize: 16,
        fontFamily: FONTS.heading,
        marginBottom: 4,
    },
    qrSubtitle: {
        color: COLORS.muted,
        fontSize: 12,
        fontFamily: FONTS.body,
    },
    qrBody: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.lg,
    },
    qrInfo: {
        flex: 1,
    },
    qrCodeLabel: {
        color: COLORS.muted,
        fontSize: 12,
        fontFamily: FONTS.body,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    qrCodeValue: {
        color: COLORS.text,
        fontSize: 20,
        fontFamily: FONTS.heading,
        marginTop: 4,
        marginBottom: 6,
    },
    qrHint: {
        color: COLORS.textSecondary,
        fontSize: 11,
        fontFamily: FONTS.body,
    },
    bannerText: {
        color: '#FFF',
        flex: 1,
        fontSize: TEXT_SIZES.label,
        fontFamily: FONTS.heading,
        fontWeight: '500',
    },

    // Section Headers
    sectionTitle: {
        color: COLORS.text,
        fontSize: TEXT_SIZES.subheading,
        fontFamily: FONTS.heading,
        marginBottom: SPACING.md,
    },

    // Roles / Players
    playersContainer: {
        backgroundColor: COLORS.cardDark,
        borderRadius: RADII.md,
        padding: SPACING.md,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        marginBottom: SPACING.xl,
    },
    playerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: SPACING.sm,
        paddingBottom: SPACING.sm,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.overlayLight,
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: COLORS.overlayMedium,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: SPACING.md,
    },
    avatarText: {
        color: COLORS.text,
        fontSize: 16,
        fontWeight: 'bold',
    },
    playerInfo: {
        flex: 1,
    },
    playerName: {
        color: COLORS.text,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.heading,
    },
    playerRole: {
        color: COLORS.accent,
        fontSize: TEXT_SIZES.caption,
        fontFamily: FONTS.body,
    },
    hostBadge: {
        backgroundColor: COLORS.overlayLight,
        paddingHorizontal: 4,
        paddingVertical: 1,
        borderRadius: 4,
        marginLeft: 6,
    },
    hostText: {
        color: COLORS.textSecondary,
        fontSize: 10,
        fontWeight: 'bold',
    },

    // Footer Actions
    footer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: COLORS.cardDark,
        padding: SPACING.screenPadding,
        borderTopWidth: 1,
        borderTopColor: COLORS.overlayLight,
        paddingBottom: SPACING.lg + 20,
        zIndex: 10000,
        elevation: 10000,
    },
    footerRow: {
        flexDirection: 'row',
        gap: SPACING.md,
        alignItems: 'center',
    },
    joinButton: {
        backgroundColor: COLORS.accent,
        paddingVertical: 14,
        borderRadius: RADII.md,
        alignItems: 'center',
        ...SHADOWS.accentStrong,
    },
    joinButtonText: {
        color: '#FFF',
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
    },
    joinedButton: {
        backgroundColor: COLORS.success + '15',
        paddingVertical: 14,
        borderRadius: RADII.md,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: COLORS.success + '50',
    },
    joinedText: {
        color: COLORS.success,
        fontFamily: FONTS.heading,
        fontSize: 14,
        fontWeight: 'bold',
    },
    secondaryButton: {
        backgroundColor: 'transparent',
        paddingVertical: 14,
        borderRadius: RADII.md,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: COLORS.error + '50',
    },
    secondaryButtonText: {
        color: COLORS.error,
        fontSize: 14,
        fontFamily: FONTS.heading,
        fontWeight: 'bold', // Match weight with primary buttons
    },
    fullButton: {
        backgroundColor: COLORS.overlayMedium,
        paddingVertical: 14,
        borderRadius: RADII.md,
        alignItems: 'center',
    },
    fullText: {
        color: COLORS.textSecondary,
        fontWeight: 'bold',
    },
    getRequestButton: {
        backgroundColor: COLORS.accent,
        paddingVertical: 14,
        borderRadius: RADII.md,
        alignItems: 'center',
        ...SHADOWS.accentStrong,
    },
    getRequestButtonText: {
        color: '#FFF',
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    cancelRequestButton: {
        backgroundColor: COLORS.error + '15',
        borderWidth: 1.5,
        borderColor: COLORS.error + '60',
        paddingVertical: 14,
        borderRadius: RADII.md,
        alignItems: 'center',
    },
    cancelRequestButtonText: {
        color: COLORS.error,
        fontSize: TEXT_SIZES.body,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },

    // Role Selection Modal
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.8)',
        justifyContent: 'flex-end', // Align friend modal to bottom
    },
    modalContent: {
        backgroundColor: COLORS.cardBackground,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        minHeight: '60%',
        maxHeight: '90%',
        paddingBottom: 40,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 24,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.cardBorder,
    },
    modalTitle: {
        color: COLORS.text,
        fontSize: 20,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
    },
    roleOption: {
        padding: SPACING.md,
        backgroundColor: COLORS.overlayLight,
        borderRadius: RADII.sm,
        marginBottom: SPACING.sm,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    roleOptionSelected: {
        borderColor: COLORS.accent,
        backgroundColor: 'rgba(66, 165, 245, 0.1)',
    },
    roleOptionText: {
        color: COLORS.text,
        fontSize: TEXT_SIZES.body,
        textAlign: 'center',
    },
    modalActions: {
        flexDirection: 'row',
        gap: SPACING.md,
        marginTop: SPACING.md,
    },
    modalButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: RADII.sm,
        alignItems: 'center',
    },
    cancelButton: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: COLORS.overlayMedium,
    },
    confirmButton: {
        backgroundColor: COLORS.accent,
    },

    // Join Code Modal Specifics
    codeSubtext: {
        color: COLORS.textSecondary,
        textAlign: 'center',
        marginBottom: SPACING.lg,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.label,
    },
    codeInput: {
        backgroundColor: COLORS.inputBackground,
        color: COLORS.text,
        padding: SPACING.md,
        borderRadius: RADII.sm,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        fontSize: TEXT_SIZES.input,
        textAlign: 'center',
        marginBottom: SPACING.xl,
        fontFamily: FONTS.body,
    },
    statusBanner: {
        padding: SPACING.md,
        borderRadius: RADII.sm,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.overlayLight,
    },
    statusText: {
        color: COLORS.accent,
        fontFamily: FONTS.heading,
        fontSize: TEXT_SIZES.label,
        fontWeight: 'bold',
    },
    assessmentMessage: {
        color: COLORS.textSecondary,
        textAlign: 'center',
        marginBottom: SPACING.xl,
        fontFamily: FONTS.body,
        fontSize: TEXT_SIZES.body,
    },
    loadingContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.background,
    },
    // Team Comparison / Slot System
    teamsWrapper: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: SPACING.lg,
        marginBottom: SPACING.xl,
    },
    teamContainer: {
        backgroundColor: COLORS.cardBackground,
        borderRadius: 24,
        padding: 20,
        // Removed borders and shadows for a cleaner look
    },
    teamTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: SPACING.md,
        paddingBottom: SPACING.xs,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.overlayLight,
    },
    teamTitle: {
        color: COLORS.text,
        fontSize: TEXT_SIZES.label,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
    },
    captainBadge: {
        backgroundColor: COLORS.warning + '20',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: COLORS.warning + '40',
    },
    captainText: {
        color: COLORS.warning,
        fontSize: 8,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    slotRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderRadius: 18,
        marginBottom: 8,
        backgroundColor: 'rgba(255,255,255,0.02)', // Minimal background
        // Shadows removed per request
    },
    slotAvatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: COLORS.cardBorder,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.1)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    slotAvatarText: {
        color: COLORS.text,
        fontSize: 16,
        fontFamily: FONTS.heading,
        fontWeight: '900',
        letterSpacing: 0.5,
    },
    slotInfo: {
        flex: 1,
    },
    slotName: {
        color: COLORS.text,
        fontSize: 15,
        fontFamily: FONTS.heading,
        fontWeight: '700',
        letterSpacing: 0.3,
    },
    slotRoleName: {
        color: COLORS.accent,
        fontSize: 11,
        fontFamily: FONTS.body,
        marginTop: 2,
        opacity: 0.8,
    },
    emptySlotName: {
        color: COLORS.textSecondary,
        fontSize: 13,
        fontFamily: FONTS.body,
        fontStyle: 'italic',
        opacity: 0.6,
    },
    joinSlotButton: {
        backgroundColor: COLORS.accent,
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderRadius: 8,
        elevation: 2,
    },
    joinSlotText: {
        color: '#FFF',
        fontSize: 11,
        fontFamily: FONTS.heading,
        fontWeight: 'bold',
    },
    inviteSlotButton: {
        backgroundColor: 'rgba(66, 165, 245, 0.1)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(66, 165, 245, 0.3)',
    },
    inviteSlotText: {
        color: COLORS.accent,
        fontSize: 11,
        fontFamily: FONTS.heading,
        fontWeight: '600',
    },
    friendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        marginHorizontal: 16,
        marginBottom: 8,
        backgroundColor: 'rgba(255,255,255,0.03)',
        borderRadius: 16,
    },
    friendAvatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: COLORS.overlayLight,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
    },
    friendName: {
        color: COLORS.text,
        fontSize: 16,
        fontFamily: FONTS.heading,
        fontWeight: '500',
        flex: 1,
    },
    sendInviteButton: {
        backgroundColor: COLORS.accent,
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 10,
    },
    sendInviteText: {
        color: '#FFF',
        fontSize: 13,
        fontFamily: FONTS.heading,
        fontWeight: '600',
    },
    friendListEmpty: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
    },
    emptyModalText: {
        color: COLORS.muted,
        fontSize: 14,
        marginTop: 12,
        textAlign: 'center',
    },
});
